### ISSUE TITLE
Abort viewing server on window close

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#102]
Would it be possible to abort the local server which is spun up upon `pretext view` once the window closes?  This would be helpful when we integrate with VSCode and other text editors.  We will want a command there that after building opens a window to localhost at the correct port, but there won't be an easy way to remind the user to cancel the server.

**Comment by oscarlevin** [comment]
Maybe we can close this?  What I have now for the vs-code extension is that calling `pretext view` tells the user that the server will remain running until they close vs-code (the command calls `pretext view [target]` silently otherwise).  I'm not sure if this is a very bad idea though.

**Comment by StevenClontz** [comment]
In practice I haven't seen/heard of any issues with the `pretext view` server related to this, so we can reopen if we get a relevant report.
