### ISSUE TITLE
configuration file

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#11]

**Comment by StevenClontz** [comment]
Since you mentioned `.pretext.cfg` in #18, I'll ask here:

- What format will this file be? Unless there's a strong reason otherwise, I'd like it to be XML like our other PreTeXt documents (despite preferring JSON and YAML in general).
- Will this be hidden from the user (as you imply with the filename)? I had imagined it'd be visible, but I'm open to hiding it.
- Another implication you made that I really like: whether the working directory represents a PreTeXt project or not is determined solely by the presence/absence of a config file, since it can provide all other information about the project (where the source is, where the output goes, etc.)
- When we do this, I want to be slow about adding extra configurations. I'd rather focus on giving great support for a conventional configuration first, and then trickle in other tweaks based on community request.

**Comment by StevenClontz** [comment]
Notes from the old `ROADMAP.md` (which I'm currently refactoring into issues:)

> ### Configuration
> 
> Save project-based options in a config file for that project.  The script reads global default options (are there any?) then options from local (project) config file, then options from command line.  One command line option is to save command line options to local config file.
> 
> Reasonable options to put in this file:
> 
> * location of pretext/xsl (for using dev version)
> * name/location of publisher file
> * custom xsl
> * string params
> * output location
> * name of main ptx file

**Comment by oscarlevin** [comment]
Initial stab at 563d59b.  Implemented using the [click-config-file](https://pypi.org/project/click-config-file/) package.  

The new behavior is as follows: whenever a user supplies an option that would be reasonable to save, the variable value is saved automatically in `.ptxconfig` in whatever directory `pretext` is called.  These values are then used as the default when the option is not specified.  

Is this reasonable behavior?   Should the user be required to select an option (`--save-config`) to update the config file?  There might be times when an author wants to experiment with different stringparams or use a different publisher file without needing to re-enter the original.  

Should there be a `--clear-config` option that resets all options to default?  

What else?

**Comment by StevenClontz** [comment]
Nice find on `click-config-file`. Having a ready-made library is making me more comfortable with the idea of not using XML for this purpose; otherwise I'd lean towards sticking to one data format.

I'm concerned about the silent saving/using of non-standard defaults. What about:

- `pretext [CMD] [options] -s` or `pretext [CMD] [options] --save-custom-defaults`
    - In addition to running the command, saves all the options as the user's custom defaults (replacing all previous settings, so passing no other options would clear defaults)
- `pretext [CMD] [options] -c` or `pretext [CMD] [options] --use-custom-defaults`
    - Uses the custom defaults, and provided options override those (but aren't saved unless `-s` also passed).
    - Prints out the custom defaults used to remind user.
- `pretext [CMD] [options]`
    - Ignores custom defaults

Also it looks like there's currently no namespacing in `.ptxconfig` for various commands, which might cause conflicts down the road.

**Comment by StevenClontz** [comment]
An argument against using `click-config-file` (maybe): if we roll our own configuration file, we have flexibility to store other kinds of data, and using the config file for other purposes. One idea I had: when running any CLI command, we look up the filesystem for a `.ptxconfig` file beginning with the current working directory, and if we find it, that's considered the root of the current project. That way if I run `pretext build` while in the `source/images` subdirectory, things still work correctly.

**Comment by StevenClontz** [comment]
One other thought that I realized today. I have a build script that calls [the development version of] `pretext build` as a subprocess. If I was to share that build script with another user, who might have set different defaults, my build script might be broken. So while I'd still prefer having the use of saved defaults being "opt-in" with a short `-c` flag which would address this, we alternatively at least need some kind of flag to "opt-out", e.g. `--ignore-custom-defaults`.

**Comment by StevenClontz** [comment]
Bug to fix: make sure configs for different subcommands don't bleed into each other.

**Comment by StevenClontz** [comment]
(At some point) it'd be convenient if, when using custom defaults, we printed what they are. E.g. maybe `pretext build -c` runs the custom defaults, but the first thing it does is print `pretext build all --output=foo` or whatever those custom settings are, to remind the user what's going on.

**Comment by oscarlevin** [comment]
More work at fbe2020.  New behavior:

- User can specify the name of the config file (default is .ptxconfig) or write --config None to not use any config file.  This allows for saving multiple configurations, or using standard defaults.
- User specified options are only saved to config file with the -sc/--save-config flag set.  When it is, the config file is also printed to the terminal.
- Under the hood, the --config and --save-config click.options are now specified at the start of cli.py and called in the two functions that use them.  The utils.write_config() function also includes some output to the terminal.

Is this good enough?  I'm not opposed to adding a --ignore-saved-configuration or similar, but the list of options is getting long as it is.  I do think that it is helpful to not have to specify that we want to apply a particular configuration file by default.
