### ISSUE TITLE
Fix default diagrams and  ensure YouTube thumbnails

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#124]
via Sean F

> Just for fun I dropped a YouTube video into the Hello World TBIL assignment.
Something is not set up correctly in thumbnail generation. Here's the
traceback.

```
Traceback (most recent call last):
   File "/home/user/.local/bin/pretext", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line
829, in __call__
     return self.main(*args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line
782, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line
1259, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line
1066, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line
610, in invoke
     return callback(*args, **kwargs)
   File "/home/user/.local/lib/python3.8/site-packages/pretext/cli.py",
line 167, in build
project.build(target_name,webwork,diagrams,diagrams_format,only_assets)
   File
"/home/user/.local/lib/python3.8/site-packages/pretext/project.py", line
207, in build
     builder.diagrams(target.source(), target.publication(),
target.generated_dir(), target.stringparams(), diagrams_format)
   File
"/home/user/.local/lib/python3.8/site-packages/pretext/build.py", line
100, in diagrams
     core.youtube_thumbnail(
TypeError: youtube_thumbnail() got an unexpected keyword argument
'outformat'
```

> Oh, I think maybe I see why: with pretext-cli, the only allowed
outformats are svg, pdf, eps, and tex. But YouTube thumbnails require
png outformat (and Asymptote will require html).

**Comment by oscarlevin** [comment]
Also fix asymptote call to user `server`

**Comment by oscarlevin** [comment]
Keeping track of what has been done in upcoming PR:
- core.youtube_thumbnail had an extra argument.  We don't get to specify the output format.  
- same with preview images.
- added `method='server'` to asymptote_conversion call (had to update core commit)

Defaults: 
- PDF
  - latex-image: no
  - sage: pdf
  - asy: pdf
- HTML
  - latex-image: svg
  - sage: svg
  - asy: html

**Comment by StevenClontz** [comment]
To summarize my understanding of our chat with Rob, we only need to support one assumed output format for each type of diagram per target format (e.g. sage builds to pdf for latex and pdf targets, but svg for HTML targets).

We could also support building every output format possible by looping through all the target formats, but I don't think this is super important.

**Comment by StevenClontz** [comment]
I went ahead and cut [0.4rc0](https://pypi.org/project/pretextbook/0.4rc0/) to install for TBIL users and hopefully hear back with any issues. We'll get this last improvement into rc1 next week.

**Comment by oscarlevin** [comment]
That's what I took away as well.  Further updates:

- cleaned up signature of core.latex_image_conversion
- added a dictionary for default formats in build.formats
- build diagrams now generates each image found in source into the format from said dictionary matching the build target.
- Should be easy to add epub-svg and epub-kindle to dictionary when we are ready to add that.  Slides?
- `--diagrams-format` now accepts "defaults" or "all", and those are the things we build.

**Comment by StevenClontz** [comment]
> I went ahead and cut 0.4rc0 to install for TBIL users and hopefully hear back with any issues.

And good thing I did - looks like I broke `pretext view --watch` at some point.

Going to push an rc1 with this issue closed...

**Comment by StevenClontz** [comment]
https://pypi.org/project/pretextbook/0.4rc1/
