### ISSUE TITLE
`pretext --targets` outputs a list of valid targets from manifest

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#127]
This is a little bit of a developer request.  For the VS Code pretext-tools, I have currently hard coded in html and pdf as build targets.  But ideally, the targets that the user can select should be those for which there are aliases in the project manifest.  Now I could figure out how node lets you read in and parse the xml file and recreate all the logic, but it would be so easy to use what we already have in the CLI to simply output a list of outputs that I can then parse.

I'm happy to implement as long as @StevenClontz thinks this is an okay idea.

**Comment by StevenClontz** [comment]
Sounds fine to me, sort of like `git branch` lists all the branches.
