### ISSUE TITLE
`pretext build --only xml-id`

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#128]
It'd be useful to be able to build a specific xml:id to reduce build times during authoring of a specific section. I don't think this is a quick thing to implement (I considered something like just killing all siblings of the specified xml:id in source before building, but that'd break at least xrefs), but wanted to open the issue for future consideration. 

Context: I *really* enjoy authoring using `pretext view --watch` but that breaks down once you get past a few sections.

**Comment by oscarlevin** [comment]
Maybe very easy: https://pretextbook.org/doc/guide/html/restrict-pretext-scope.html.  I think there was a way to do this using xsltproc (not just for image generation), but the google search for the documentation doesn't show anything.

**Comment by rbeezer** [comment]
That restriction switch was designed for instances of cruising through a 
document looking for small pieces to rip out and process (like a latex-image).

It'll be a lot of work to get just, say, one chapter out as, say, HTML.

**Comment by StevenClontz** [comment]
I think #136 is a better solution.
