### ISSUE TITLE
Signature changes for PDF, HTML, LaTeX conversions in core

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#160]
The `pdf()`, `latex()`, and `html()` routines now have a new fourth argument, which is a stylesheet that will be used instead of the default versions.

You can pass `None` in this parameter until you want to support it.  To use, it should receive a full filename (complete path).

It is the author's responsibility to ensure it behaves!  Which could suggest a reason for `pretext/pretext` to have this support, and the CLI not to?

See https://github.com/rbeezer/mathbook/commit/5f6cdebcf0377835aec7e503010e4ea3ee0cd40a

**Comment by oscarlevin** [comment]
I was just thinking about implementing something like this just for the CLI this morning.  It is the only thing stopping me from using the CLI in my own projects.  With this change to the core, I think we can tackle issue #23 and do so easily.  I'll post an idea there for at least a temporary way to make this work and try to implement it today.  If I can finish it by Friday, maybe we release 0.5 and really feel like everything is done.

**Comment by StevenClontz** [comment]
N.B. we should take advantage of our support for converting `<xsl:import pretext-href="pretext-common.xsl"/>` written in an author's source to `<xsl:import href="/path/to/pretext-cli/xsl/pretext-common.xsl"/>`, so you can extend CLI-managed XSL without worrying about where it actually lives on your disk.

**Comment by rbeezer** [comment]
Cool!  I'm trying to get AATA cutover to `pretext/pretext` to the point where the current makefile is trivially stupid.  ;-)  Almost "inside baseball": might work on "versions" next.

Holler if new code misbehaves.  Announcement on -dev in a bit, with documentaion with some gotchas.

**Comment by rbeezer** [comment]
> our support

Oh, good.  Only documented gotchas with my hacky setup for that.

**Comment by oscarlevin** [comment]
@StevenClontz , is the `pretext-href` conversion stuff already in our scripts?  Do you anticipate doing that every time a user builds (creating a copy of all the custom xsl in a temporary folder)?
