### ISSUE TITLE
pageres error with interactive figure

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#166]
Via @JeanSebastienTurcotte 

> I have tried building diagrams for the first time since updating from 0.3 to 0.5. I have a single interactive in my document which used to build fine. Now, I get an error citing "pageres" when the CLI is attempting to build the previews for interactive and the build fails. If I then use build html without the d flag, everything seems ok. I managed to fix this by adding a preview="mypreview.whatever" in the interactive tag. But I can't verify if the preview gets loaded in PDF due to point 2.

**Comment by StevenClontz** [comment]
https://github.com/JeanSebastienTurcotte/MADIR/blob/master/source/Section_ensembles.xml#L224

**Comment by rbeezer** [comment]
This may be obvious, but the `pageres-cli` application needs to render an HTML version of the project being served at some known location.  We do this with the  `pretext/pretext` script via a `baseurl` setting in the publication file.  So I'm not sure of the exact problem here, but if a `-d` flag affects results, then....

**Comment by StevenClontz** [comment]
This issue is probably a better fit for @oscarlevin but naively it sounds like maybe we need to include some reasonable default in our generated publication file that Just Works (and is ignored if this feature isn't used)?

**Comment by StevenClontz** [comment]
Sort of how we set https://github.com/PreTeXtBook/pretext-cli/blob/main/templates/publication.ptx#L4 pre-emptively in case an author wants to add WebWork later?

**Comment by oscarlevin** [comment]
That makes sense.  I'll try to look into this on Friday.  In the mean time, maybe @JeanSebastienTurcotte can try setting `baseurl` in the publication file.  Although I'm not sure why this would have worked earlier and not now; we are passing everything to the `pretext/pretext` script....

**Comment by StevenClontz** [comment]
This is not really a CLI but an external dependency issue. Hopefully they'll replace pageres with pyppeteer and make this easier though.
