### ISSUE TITLE
possible issue with PDF generation

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#167]
> Somehow, build pdf only produces a small part of my project. I get a successfull run and am prompted to preview the PDF, but it only contains 3 pages. Not sure what is wrong on this one.

https://github.com/JeanSebastienTurcotte/MADIR

**Comment by oscarlevin** [comment]
I didn't even get that far when I tried to build this.  My tex complained that it couldn't find `matrix.skeleton` (in `\usetikzlibrary{matrix.skeleton}`).  I suspect there is an issue with tex compiling.  

Try `pretext build latex` and then compile the main.tex file you get separately.  

This does raise a frustration I have: if the tex build fails, there is really no way to see why unless you separately build latex.  It might make sense to copy over the .tex file as well as the pdf.

**Comment by StevenClontz** [comment]
Not copying LaTeX is due to how @rbeezer /mathbook works, not our library, correct?

There's more to this than just shipping a LaTeX file - you'd need all the assets as well. So maybe what you're doing is what we should tell folks if PDF build fails: "try to `pretext build latex` and build the PDF directly to learn more".

**Comment by oscarlevin** [comment]
Correct and correct.  I don't know how to sniff out that the pdflatex or xelatex step fails.  Those (using `pretext/pretext`) are being done in batch mode or something, so we get a "successful" build even though we don't.

**Comment by StevenClontz** [comment]
Closing as we think this is covered in recent releases in the past year, will reopen if it's brought up again.
