### ISSUE TITLE
Don't copy .xsl or .ent files to output

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#168]
When doing a custom xsl build, we copy all the user's `xsl` directory to the temporary directory (replacing pretext-href with the appropriate href).  However, when the build finishes, the last step is to copy the output that was placed in the temporary directory into the output folder for the project.  Currently, all the .xsl and .ent files are being copied as well.  This doesn't break anything, but is sloppy and annoying.

**Comment by StevenClontz** [comment]
One solution: different temporary directories for XSL copying and output building.
