### ISSUE TITLE
Issue with sageplots

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#175]
I'm not sure where this is breaking down, but if you `pretext new` and insert the following figure into the introduction of your project:

```
<figure>
  <image>
    <sageplot>plot(x^2)</sageplot>
  </image>
</figure>
```

then `pretext build -d` will successfully create a file at `generated/sageplot/introduction-2.svg` (I inserted the figure into the introduction to the first section), but the generated HTML will be trying to embed an image at `generated/sageplot/image-1.png`.

**Comment by StevenClontz** [comment]
A workaround: adding an `xml:id` to the image seems to fix this.

```
<figure>
  <image xml:id="foo">
    <sageplot>plot(x^2)</sageplot>
  </image>
</figure>
```

Then the HTML correctly looks for a file generated at `generated/sageplot/foo.svg`.

**Comment by StevenClontz** [comment]
@rbeezer this feels like a core PreTeXt script bug, but maybe it's just how we're interfacing with it.

**Comment by rbeezer** [comment]
Maybe every element should have an `@xml:id` supplied by the pre-processor?

(See post I have been working on for two days, coming up.)

The `introduction-2` is what is wrong, if it is not obvious.  You should not be putting a (numbered) `figure` into an `introduction` but I don't think that is the problem.  I'll investigate, but it might be a few hours.

**Comment by StevenClontz** [comment]
I'm closing this as it's not a CLI bug.
