### ISSUE TITLE
Errors when git not installed?

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#176]
I had the pleasure of setting up a new windows machine today and pip installed pretextbook.  Upon running `pretext --version` I got an error about git (which I had not yet installed on my system):

>  Traceback (most recent call last):
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\site-packages\git\__init__.py", line 87, in <module>
>     refresh()
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\site-packages\git\__init__.py", line 76, in refresh
>     if not Git.refresh(path=path):
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\site-packages\git\cmd.py", line 340, in refresh
>     raise ImportError(err)
> ImportError: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh()
> 
> All git commands will error until this is rectified.
> 
> This initial warning can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|none|n|0: for no warning or exception
>     - warn|w|warning|1: for a printed warning
>     - error|e|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\Scripts\pretext.exe\__main__.py", line 4, in <module>
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\site-packages\pretext\cli.py", line 11, in <module>
>     from .project import Target,Project
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\site-packages\pretext\project.py", line 5, in <module>
>     import git
>   File "C:\Users\oscar.levin\AppData\Local\Programs\Python\Python310\lib\site-packages\git\__init__.py", line 89, in <module>
>     raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
> ImportError: Failed to initialize: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh()
> 
> All git commands will error until this is rectified.
> 
> This initial warning can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|none|n|0: for no warning or exception
>     - warn|w|warning|1: for a printed warning
>     - error|e|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> 

Obviously this is unfortunate for new users who might not want to use git or the git features.

**Comment by oscarlevin** [comment]
As suspected, once git has been installed, the error goes away.

**Comment by StevenClontz** [comment]
I disagree with GitPython's design decision to throw the error on import rather than first trying to use the library, but it is what it is.

Fix should be to move `import git` inside the specific functions that use it, and then use something like:

```
try:
    import git
except ImportError:
    log.critical("Git must be installed to use this feature.")
    return None
```
