### ISSUE TITLE
Improved subset builds

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#178]
I've made adjustments to the `html()` function in PreTeXt core.  To support 

Subset builds (final version of signature):  https://github.com/rbeezer/mathbook/commit/ab719e2e29f17fd33c0399c01315ef3d70317691

Zip-file option (call with 'html' for status quo): https://github.com/rbeezer/mathbook/commit/5e0c8ee32fe06042bfbbe753168f5664bc19d76c

I've tried to isolate this to some extent to avoid confusion, but holler if there are questions (or drop in to Drop-In!).  The only thing that might change is teh use of the `@xml:id` to specify a subtree for building, but I've not seen any good suggestions for an alternate approach.

**Comment by StevenClontz** [comment]
As of 3e1d1714113aaa97c736ccd76638aacc85e7bb19 we use the new-and-improved subset build pattern. I need to do some more general testing of different kinds of builds (#7 sigh) before I can cut a release. I'll try to put out a release candidate later this week.

N.B. I don't have any support for zip-file builds. Yet. #181

**Comment by StevenClontz** [comment]
Before release we need to add support for using xmlid_root in diagram builds e.g. https://github.com/rbeezer/mathbook/blob/dev/pretext/pretext.py#L247

**Comment by StevenClontz** [comment]
That was easy lol https://github.com/PreTeXtBook/pretext-cli/commit/6d0fb2c1bbbf7ae45ff8d8fde1af1bd75f96127c

New RC at https://pypi.org/project/pretextbook/0.5.4rc3/ -- using this today with a few projects to test the waters
