### ISSUE TITLE
Environment status (is working directory a PreTeXt project? is latexmk available?)

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#18]
Like a dummy I ran `pretext build html` in the wrong folder and got an `OS Error`. In a perfect world we'd have a function to sniff whether the user is working in a directory with a PreTeXt project, and raise an error on `pretext build` if not.

This might also be the right way to approach external dependencies too - we have specific functions to check for programs as needed for various functions, and if they are missing bubble up an error with nice instructions on how to get things installed.

**Comment by oscarlevin** [comment]
We should test whether the input file is a pretext root file (that includes `<pretext>`).  

Eventually, any pretext project folder will contain a .pretext.cfg file, and it will contain the name of the root file.  So we can also test for that.

**Comment by StevenClontz** [comment]
https://pretextbook.org/doc/guide/html/publisher-file-reference.html

**Comment by StevenClontz** [comment]
Closed as subset of #96 (root of project is `project.ptx`)
