### ISSUE TITLE
Consider support for zipped html builds

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#181]
New core features allow building a ZIP of html files. I'm not sure it fits into the GitHub Pages-focused workflow of the CLI, but probably should be exposed as a feature at some point. https://github.com/rbeezer/mathbook/commit/5e0c8ee32fe06042bfbbe753168f5664bc19d76c

**Comment by StevenClontz** [comment]
See also #178

**Comment by oscarlevin** [comment]
I'm pretty sure we have this all set up, although undocumented.  If a target has format `html-zip` then we build a zip.  This is the same way I'm setting up braille, which can have `electronic` or `emboss` page formats.  

I guess we should eventually decide whether we should instead have an attribute of format to control this, but I don't really like `@option` or `@format` (so `<format @format="zip">html</format>`?).  I guess `<format zip="yes">html</format>` isn't awful, but that doesn't work for the braille case really.

**Comment by oscarlevin** [comment]
In 2.0, a target can have have `@compression` attribute if the `format` is `html` or `webwork`.
