### ISSUE TITLE
consider switch from pipenv

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#182]
I'm using https://github.com/pyenv/pyenv-virtualenv for CheckIt, I think it's a little more elegant to use alongside pyenv. (e.g. running python from the project directly automatically uses the pyenv shim/virtualenvironment, without having to explicitly load up a shell).

But I don't think it has Windows support. @oscarlevin are you using Windows or a unix-like environment for developing the CLI?

**Comment by oscarlevin** [comment]
I'm using both, but recently much more linux (WSL when I'm on my windows machine).  I think it would be fine to change the developers guide to use this better system.

**Comment by StevenClontz** [comment]
okay I'll look into this when start preparing the next major release.

**Comment by StevenClontz** [comment]
Poetry has also been recommended by Bryan Jones. I believe that's what's used by Runestone so it'd be nice to converge workflows... https://python-poetry.org/

**Comment by rbeezer** [comment]
> Poetry has also been recommended by Bryan Jones.

We **already have** a `<poem>` element in PreTeXt.  Oh wait, this is the CLI repo...

**Comment by StevenClontz** [comment]
> There once was a maintainer named Rob
> Who told bad jokes while on the job
> While they were lame
> You could say the same
> Of Steven's limericks that cause you to sob

**Comment by rbeezer** [comment]
Immortalized at: https://pretextbook.org/examples/sample-article/html/poetry.html#limerick-clontz

That's the fastest publication you are ever going to get!

**Comment by StevenClontz** [comment]
Closing as of 84c126c008237cdcb6d60f228f86a3ddc1a74c44 (but making a new issue for setting up poetry for package management).
