### ISSUE TITLE
Don't use `<numbering><* level="0"/></numbering>` in default publication.ptx

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#186]
This will break when an author tries out using `<part>`s.

**Comment by rbeezer** [comment]
Look inside `xsl/publisher-variables.xsl` and you can find the defaults provided there.

It is good to make these explicitly available for a new author using the CLI, but perhaps mirroring defaults used in their absence would be the best way to get started?
