### ISSUE TITLE
at least warn authors who are working in an absolute filepath with spaces

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#187]
At the least, publication files cannot be imported if anywhere in the absolute filepath has spaces

**Comment by rbeezer** [comment]
This is an XSLT problem it seems.  The percent-encoding of a space (`%20`) can happen when XSL receives the filename as a string (`stringparam`) and before its use in a `document()` function to actually read the file.  Fix tested with the publisher file, and there are at least three other files.

Working on it and will post here once complete.

**Comment by rbeezer** [comment]
Fix is in at https://github.com/rbeezer/mathbook/commit/8dfbdff1a43e9096134d2b2eb7ebdabfac40f130

You might read the code comments in that commit for a bit of perspective, should this become evermore subtler than it is already.  ;-)

**Comment by StevenClontz** [comment]
Can confirm spaces in the publication filename don't choke things as of this core commit update. https://github.com/PreTeXtBook/pretext-cli/commit/094db808babe36d700182a236fc0cc0c2355437a
