### ISSUE TITLE
`pretext publish` should be `pretext deploy` (?)

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#195]
Using "publish" is confusing as it has nothing really to do with a `publication` file. `pretext deploy` I think is a clearer explanation of what this command is supposed to do.

**Comment by StevenClontz** [comment]
In #221 Oscar laments that we don't have a better word than "deploy". Now's the time to consider if this is possible; I don't want to change it again!

We agree at least that "deploy" is better than "publish".  "Deploy" seems to be a word used in static web development: https://www.digitalocean.com/community/tutorials/how-to-deploy-a-static-website-to-the-cloud-with-digitalocean-app-platform

I'm giving us up until whenever we make the next CLI release to decide on a better verb; otherwise we'll stick to "deploy".

**Comment by Alex-Jordan** [comment]
Is this very narrowly for putting your HTML up on pages.github.com? Or does it potentially have a more broad application?

**Comment by Alex-Jordan** [comment]
Maybe it should be like `pretext deploy pages.github` or even `pretext publish pages.github` where you are required to say where, and it only works if you give a valid location. And then the context of having that specification helps disambiguate.

**Comment by StevenClontz** [comment]
What this does:

- If project isn't tracked with git:
    - Print out links to documentation to help user set up SSH and create a new GitHub repo
    - Automate the following commands
        - `git init` 
        - `git add -A` 
        - `git commit -m "initial commit"` 
        - (change master branch to main)
        - `git remote add origin [prompt user for repo SSH info]`
        - `git push -u origin main`
- If branch isn't `main`
    - CLI never does this, so the user is told to fix it back to main themselves
- If HEAD is dirty
    - `git add -A` 
    - `git commit -m "update changes to source"` 
- Copy results of latest build (which isn't tracked by Git if using default `.gitignore`) into `/docs` (which is tracked by Git). Then
    - `git add docs`
    - `git commit -m "update build"`
    - `git push`

As a result, the user should have a working GitHub Pages deployment, which can be updated by `pretext deploy` at any time, assuming they followed instructions to set up GitHub Pages on GitHub's end.

**Comment by Alex-Jordan** [comment]
Geez someone should document all that somewhere ;)

**Comment by StevenClontz** [comment]
Ha, well, the point is that it *should* Just Work from the user's perspective.

To answer your question, it's hardwired for GitHub Pages, but would technically work for any Git host that serves up a webpage based on the docs subdirectory of a repo.

**Comment by StevenClontz** [comment]
Here's an example of a fresh deploy from a CoCalc instance to https://stevenclontz.github.io/bug-free-octo-waddle/

```
user@project-a3ec276b-3ccf-43b8-bbb2-52eec3285126 ~ 
[pipenv]$ pretext new
Generating new PreTeXt project in `/home/user/new-pretext-project` using `book` template.
Success! Open `/home/user/new-pretext-project/source/main.ptx` to edit your document
Then try to `pretext build` and `pretext view` from within `/home/user/new-pretext-project`.
```

```
user@project-a3ec276b-3ccf-43b8-bbb2-52eec3285126 ~ 
[pipenv]$ cd new-pretext-project/
```

```
user@project-a3ec276b-3ccf-43b8-bbb2-52eec3285126 ~/new-pretext-project 
[pipenv]$ pretext build
PreTeXt project found in `/home/user/new-pretext-project`.
Since no build target was supplied, the first target of the project.ptx manifest will be built.
Preparing to build into /home/user/new-pretext-project/output/html.

Now building HTML into /home/user/new-pretext-project/output/html

PTX: discovering source file's directory name: /home/user/new-pretext-project/source
PTX: verifying and expanding input directory: /home/user/new-pretext-project/source/../generated-assets
PTX: input directory expanded to absolute path: /home/user/new-pretext-project/generated-assets
PTX: verifying and expanding input directory: /home/user/new-pretext-project/source/../assets
PTX: input directory expanded to absolute path: /home/user/new-pretext-project/assets
PTX: converting /home/user/new-pretext-project/source/main.ptx to HTML in /tmp/tmpkxhw4k6y
PTX: XSL conversion of /home/user/new-pretext-project/source/main.ptx by /home/user/pretext-cli/pretext/static/xsl/pretext-html.xsl

Success! Run `pretext view html` to see the results.
```

```
user@project-a3ec276b-3ccf-43b8-bbb2-52eec3285126 ~/new-pretext-project 
[pipenv]$ pretext deploy
PreTeXt project found in `/home/user/new-pretext-project`.
Initializing project with Git.
Success!

If you haven't already, configure SSH with GitHub by following instructions at:
    https://docs.github.com/en/authentication/connecting-to-github-with-ssh

And if you haven't already, create a remote GitHub repository for this project at:
    https://github.com/new
(Do NOT check any "initialize" options.)
Visit Settings > Pages on your new GitHub repository's page to enable GitHub Pages,
selecting the `main` branch with the `/docs` folder.

Then within your new repository homepage's "Quick setup" section select "SSH".
And copy/paste your `git@github.com:YourUserName/repo-name.git` info below.
Remote SSH info: git@github.com:StevenClontz/bug-free-octo-waddle.git

Attempting to connect to GitHub (your SSH password may be required)...
Enter passphrase for key '/home/user/.ssh/id_ed25519': 
Successfully connected to GitHub via `git@github.com:StevenClontz/bug-free-octo-waddle.git`!

Preparing to deploy the latest build located in `/home/user/new-pretext-project/output/html`.
Latest build copied to `/home/user/new-pretext-project/docs`.

Deploying to GitHub. (Your SSH password may be required.)
Enter passphrase for key '/home/user/.ssh/id_ed25519': 

Latest build successfully pushed to GitHub!
Visit Settings > Pages on your GitHub repository's page to check deploy status.
```

**Comment by StevenClontz** [comment]
Anyway, I think I'm leaning `deploy`. I'd like to see `pretext deploy --runestone`, `pretext deploy --ftp`, etc. be options someday as well. But I think `pretext deploy` should default to `pretext deploy --gh-pages`, because that seems to be a safe no-cost no-review-required endpoint for folks to share their PreTeXt-authored documents to.

**Comment by oscarlevin** [comment]
I tried to `pretext deploy` in a untracked folder in windows and got the following:

    PS C:\Users\oscar.levin\Documents\dev\scratch\new-pretext-project> pretext deploy
    PreTeXt project found in `C:\Users\oscar.levin\Documents\dev\scratch\new-pretext-project`.
    Initializing project with Git.
    Traceback (most recent call last):
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pretext\project.py", line 314, in deploy
        repo = git.Repo(self.__project_path)
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\git\repo\base.py", line 224, in __init__
        self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\git\repo\base.py", line 307, in common_dir
        raise InvalidGitRepositoryError()
    git.exc.InvalidGitRepositoryError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "C:\Users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\Scripts\pretext.exe\__main__.py", line 7, in <module>
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\click\core.py", line 1128, in __call__
        return self.main(*args, **kwargs)
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\click\core.py", line 1053, in main
        rv = self.invoke(ctx)
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\click\core.py", line 1659, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\click\core.py", line 1395, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\click\core.py", line 754, in invoke
        return __callback(*args, **kwargs)
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pretext\cli.py", line 323, in deploy
        project.deploy(target_name,commit_message)
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pretext\project.py", line 330, in deploy
        repo.heads.master.rename("main")
      File "c:\users\oscar.levin\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\git\util.py", line 1001, in __getattr__
        return list.__getattribute__(self, attr)
    AttributeError: 'IterableList' object has no attribute 'master'

**Comment by StevenClontz** [comment]
I know exactly this problem: git for Windows has a hack that makes main the default branch. I didn't know that existed so the code right now assumes the default branch is master and tries to change it to main.

**Comment by StevenClontz** [comment]
closed as part of the refactor at https://github.com/PreTeXtBook/pretext-cli/compare/e48f5dc638130e1743eb231a8ada07e112044379...d81fa5412ab739dbe31169158d8dcdbc967b8c72

**Comment by bnmnetp** [comment]
```
git add -A
git commit -m "update changes to source"
```

Ugh!!  I wish `git add` did not even have a `-a` I get so many bad problems with book updates because of authors who do that and then we end up with output and/or 100's of other generated files that do not belong in the repo.  I think you are asking for trouble by doing this on a users behalf.

**Comment by StevenClontz** [comment]
It's a little more subtle than maybe you think? All the generated files are built to `generated-assets` which is ignored by the `pretext new` generated `.gitignore` by default.

You can see this in practice at https://github.com/StevenClontz/linear-algebra-tbil-2021/commits/main where I have about five authors collaboarting on a book in CoCalc. The `Update to PreTeXt project source` commits are clean and made first, and the `Publish latest build of target html` commits contain all the gross generated diff stuff. (All the github pages commits should really be on a separate branch but I haven't rigged that up yet.)

**Comment by bnmnetp** [comment]
A good autogenerated .gitignore file can save lots of headaches.

However... Another scenario that we should talk about is all of the Runestone books that are coming over to pretext.  I have thus far simply copied a `project.ptx` file into the folder and edited it, so that authors can use the CLI.

In these cases your assumptions about what is in the `.gitignore` file may not be true.

I think I have spent too many years telling students never to use `-a` that I have an allergic reaction when I see it.

**Comment by rbeezer** [comment]
> I think I have spent too many years telling students never to use -a that I have an allergic reaction when I see it.

I picked up this bad habit years ago, and still have to work to shake myself free of it.  Too many times I've done it "on accident" and had to unwind a lot of careful commit-building.

**Comment by StevenClontz** [comment]
PS: As someone who is fairly productive with running a `git status` check before any `git add -A`ing (and editing `gitignore` or manually adding files for separate commits as appropriate), I'm interesting in reading the rationale for other workflows that avoid `-A`.

**Comment by bnmnetp** [comment]
I think the issue is that once someone learns -A it takes a lot of pain to undo that habit.  @StevenClontz you seem like you are careful and judicious in your use of -A.  Unfortunately an automated -A is not exercising any judgement.  And many beginning users are not very discriminating:

`<soapbox>`

* Many git users don't take the commit process seriously -- So they do not write worthwhile commit messages, and commits tend to be something done in a big hurry. with -A making them even more "efficient"
* Many git users do not look carefully enough at git status and so with -A you end up with xxx~ emacs cruft .DS_Store files (thanks macOS) and files called foo or log.txt or whatever.  In the worst case an entire hierarchy of stuff that should not be committed like `__pycache__/` folders.  Or worse yet, files with secrets in them that should not be public.
* Many git users do not have good .gitignore files. - you may want to look at some of the github templates for ignore files, they include lots of things not in your template that you may want to consider.
* Yes, much of this is somewhat undoable with `git rm` but it remains in the history.
* Most often when you are ready to commit you have a hodge podge of changes in files that are not related and should not be committed together.  If used properly git is a giant safety net, but if you are not careful about your commits you are making it very hard for yourself.  It is worth while to take the time to make multiple commits of the small things that go together.  You should not have to do a git diff between two commit hashes to figure out what a commit is really about.
* cherry-pick and revert are beautiful commands but they do not work well if your commit history is crap.

`</soapbox>`

Even if I look at the git status and see that I have just two files in a subdirectory modified and no untracked files I will just get add the subdirectory over using -a. 

I wish that I had known git a lot better when I started the project!  My history would be MUCH cleaner and I would do more rebasing and more squash commits, and have no commit messages that simply read "WIP."

**Comment by StevenClontz** [comment]
Thanks for the soapbox @bnmnetp! (seriously) :-)

I think the main difference here is that `pretext deploy` is purposely not intended to produce a great Git history, but at least is a little better than mixing in all the build stuff with the source updates. But it *could* be improved to have better safety rails for folks who *are* trying to be mindful of their Git history. So I'd suggest one of two changes (in addition to the enhancement I propose at #242).

### option 1

`pretext deploy` behaves as currently does (add/committing all files into a commit, then copying build files into `docs` for a build commit & push), but `pretext deploy -s|--strict` only works when there are no untracked/unstaged files (and then only copies build files into `docs` for a build commit & push).

### option 2

`pretext deploy -a|--auto-git` (please suggest better names for the flag) behaves as `pretext deploy` currently does, and change `pretext deploy` to work as I described `strict` mode above (with a suggestion to use non-strict mode for folks who aren't going to bother with git management). 

### note

Either way we go, I want to encourage PreTeXt authors to let the CLI manage the Git stuff necessary for a Pages build, as I eventually want to fix it so instead of tracking `docs` within the `main` branch, we instead move files to a git-ignored `deploy` subdirectory which has a separate Git repo tracking a separate `gh-pages` branch with the same `origin` as the main project.

I'm going to move this discussion to [-dev](https://groups.google.com/g/pretext-dev).
