### ISSUE TITLE
New core stylesheet

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#197]
I've split out Runestone stuff into `pretext-runestone.xsl`, which will be imported by `pretext-html.xsl`.  So you'll need to include the new stylesheet in the next update so there is no failure loading.

**Comment by StevenClontz** [comment]
We pick up all existing XSL with `python scripts/update_core.py`, so this should be automatic. I'll keep an eye out for it for the next time we update core resources though, thanks!

**Comment by rbeezer** [comment]
OK, thanks.  Wasn't sure how much was automatic.  No more notifications along these lines!  ;-)
