### ISSUE TITLE
Program elements are not being rendered in pdf.

### ISSUE THREAD

**Issue by abradburn** [PreTeXtBook/pretext-cli#198]
In the documentation published Feb, 9, 2022, Section 3.10 Programs and Consoles, it is now recommended to use  ```<listing>``` and ```<program>``` instead of the earlier```<fragment``` and  ```<code>```?

With pretext-cli 0.6.0, this isn't being rendered. The program tags/content are being omitted.

At the same time, ```<code>``` is being rendered properly, but only within ```<fragment>``` tags..

Example XML that doesn't render.
```
<listing>
  <title>sum.s</title>
  <caption>A simple introductory program.</caption>
  <program>
    .global main
    .func main

    main:
      mov r1, #3
      mov r2, #4
      add r0, r1, r2
      bx lr
  </program>
</listing>
```
Product:
![image](https://user-images.githubusercontent.com/21087675/153391041-0a86e11b-8be9-4859-adb1-c476d4ad5397.png)

Additionally ```<listing>``` and ```<code>``` omits the code content.
Finally, ```<program>``` elements are not being rendered by themselves.

However, the same structure with ```<fragment>``` and ```<code>``` instead of ```<listing>``` and ```<program>```

Using ```<code>```
![image](https://user-images.githubusercontent.com/21087675/153390461-d5c53422-9bea-4280-a249-0ce4c0d782db.png)

Hopefully, this is helpful to the work you're doing. I thank you, this product is really great. I have enjoyed learning how to use it, and look forward to creating content with it.

Be well.

**Comment by StevenClontz** [comment]
@rbeezer can you comment on whether this is valid markup? I don't know of any reason this would be CLI-specific.

**Comment by rbeezer** [comment]
For a `program` element, you need to use `input` to wrap the code (so an optional `output` is possible).  I see we don't have great documentation for that.

The [pretext-support](https://groups.google.com/forum/#!forum/pretext-support) group is the best place for syntax questions - you'll get a fast answer.  This repo is more for the CLI front-end.

Thanks very much for the report, I'll see about getting the documenation up-to-date.
