### ISSUE TITLE
parse / validate option

### ISSUE THREAD

**Issue by arechnitzer** [PreTeXtBook/pretext-cli#199]
Is it possible to add a "validate source" option without doing a full build?  `pretext parse` or `pretext validate`

(btw - the cli is really useful)

**Comment by StevenClontz** [comment]
Closing as a duplicate of https://github.com/PreTeXtBook/pretext-cli/issues/29 

@oscarlevin can probably remind us of why this is non-trivial (I think it's an issue with LXML?)

**Comment by arechnitzer** [comment]
oops. sorry. should have searched harder.
