### ISSUE TITLE
Minimum python version 3.6

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#2]
If I recall, rbeezer/mathbook Python scripts require 3.4+. Is that the same range we want to support? If so, I'll set up https://github.com/pyenv/pyenv for 3.4 to ensure things run (e.g. the tests we need to write) on 3.4.

**Comment by StevenClontz** [comment]
Since this post, I seem to recall reading in passing on pretext-dev that rbeezer/mathbook/pretext/pretext.py has at least one feature that requires Python 3.6+. Am I making this up @rbeezer?

**Comment by rbeezer** [comment]
`subprocess.run()` requires 3.6, iirc.

Nobody has complained yet.  But some other variant from the `subprocess` module 
should be fine, so I intend to walk that one back.

**Comment by StevenClontz** [comment]
Looks like #41 would also require 3.6+ since Runestone does.

If in practice our users seem to have 3.6+ available, and if we're advocating a virtualenv workflow in some cases anyway, maybe just settling on support for 3.6+ makes sense.

Also, perhaps pretext-cli should be setting up virtualenv/Pipenv/Pyenv scaffolding upon `pretext new`. This would also address issues like #45 where pip-installed CLIs aren't available in PATH by default (since I *think* they would be available in a virtualenv regardless of platform). There's also https://github.com/pipxproject/pipx But these solutions might be circular: if I can't get `pretext` on a new user's PATH without extra configuration, and `pipenv`/`pipx` aren't in the standard library either, I'd have the same issue getting them on the user's PATH too. (Although `pipx` is `brew install`able on MacOS...)

**Comment by rbeezer** [comment]
Committed to 3.6, though practical minimum is 3.5 now.

See https://github.com/rbeezer/mathbook/issues/1479

**Comment by StevenClontz** [comment]
In 0466896cdaba6262f66f31c62959436e0553b884 I've documented pyenv/pipenv package management that fixes development with Python 3.6.12.

**Comment by oscarlevin** [comment]
I don't really understand what you did in the last commit, but trying the readme documentation failed.  No file .python-version on the first step.

**Comment by StevenClontz** [comment]
That's my fault: it was gitignored. I'll fix it later this afternoon when I'm back at the desk

**Comment by oscarlevin** [comment]
I'll go ahead and close this and open a new issue to address the readme development documentation.  Pyenv doesn't work on windows; there must be a simpler way to do this validation step.
