### ISSUE TITLE
suggest deprecating os file stuff in favour of pathlib.

### ISSUE THREAD

**Issue by arechnitzer** [PreTeXtBook/pretext-cli#201]
What it says in the title.

(but is only a suggestion)

**Comment by rbeezer** [comment]
I tried to use pathlib in the core routines, in order to get Windows compatibility, and it was a disaster.

**Comment by arechnitzer** [comment]
Strange... I thought the main point of pathlib was to avoid "I want my code to hack files on linux/osx/windows"-problems

**Comment by rbeezer** [comment]
Exactly.  Could be an ID-10T problem, but I gave it a serious go.  No love.

I think there may be just one place where we end up sanitizing path separators.  Where a publication file comes in with an OS-specific filename, and then needs to opened/read by XSL. Maybe.

**Comment by arechnitzer** [comment]
Ah... "fun".
