### ISSUE TITLE
pretext init creates a publisher file 

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext-cli#206]
Starting around this line:
https://github.com/PreTeXtBook/pretext-cli/blob/4622c3dfe64054d345dad2a1dfe20bd2c274d3d2/pretext/cli.py#L149

when `pretext init` is run, there is a check if this project has a `publication/publication.ptx` file. If so, `pretext init` will make use of it. If not, `pretext init` creates such a file and that is used in the manifest file.

But an existing project may have a publication file that is `publication.xml` (different extension) or it may be in a `publisher/` folder, or just somewhere else than `publication/publication.ptx`.

I suggest changing `pretext init` to not even try to make a publisher file. And then make it clear to the user that now they must enter the manifest file and do some editing. Actually not just manually tag the location of a publisher file, but also make it clear they should now edit the location of the project's main source file.

If that project does not have pre-existing publication file, there will be some message about it not being found, and that is the clue for this person to finally make one.

**Comment by StevenClontz** [comment]
Implemented at https://github.com/PreTeXtBook/pretext-cli/commit/3e0a616994ee3b29d946bed564e0fe09074892a1, will close this once it's released.

**Comment by Alex-Jordan** [comment]
I just found a trove of GitHub alerts that Gmail was filing away in "Updates" instead of putting into my inbox.

Anyway, can this be closed now?
