### ISSUE TITLE
Documentation hard to discover

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext-cli#209]
`pretext --help` lists some commands, but omitted are most options. After reading the source, I discovered `pretext build --help` lists more commands!

It would be good if the default help message either listed all help or suggested what you might do to see more help. (Also, it would be nice if `pretext -h` worked :-) )

**Comment by StevenClontz** [comment]
Current behavior:

```
user@project-a3ec276b-3ccf-43b8-bbb2-52eec3285126 ~/pretext-cli (main)
[pipenv]$ pretext --help
Usage: pretext [OPTIONS] COMMAND [ARGS]...

  Command line tools for quickly creating, authoring, and building PreTeXt
  projects.

  PreTeXt Guide for authors and publishers:

  - https://pretextbook.org/documentation.html

  PreTeXt CLI README for developers:

  - https://github.com/PreTeXtBook/pretext-cli/

  Use the `--help` option on any CLI command to learn more.

Options:
  -v, --verbosity LVL  Sets the severity of log messaging: DEBUG for all, INFO
                       (default) for most, then WARNING, ERROR, and CRITICAL
                       for decreasing verbosity.
  --version            Show the version and exit.
  -t, --targets        Display list of build/view "targets" available in the
                       project manifest.
  --help               Show this message and exit.

Commands:
  build    Build specified target
  init     Generates the project manifest for a PreTeXt project in the current
           directory.
  new      Generates the necessary files for a new PreTeXt project.
  publish  Publishes Git-managed project on GitHub Pages.
  support  Use when communicating with PreTeXt support.
  view     Preview specified target in your browser.
```

In particular ``Use the `--help` option on any CLI command to learn more.`` is not as clear as I thought. Perhaps we should prompt with an example: ``for example, `pretext build --help` ``

**Comment by StevenClontz** [comment]
We could implement https://click.palletsprojects.com/en/8.0.x/documentation/#help-parameter-customization to support `-h` flag for help text.

**Comment by siefkenj** [comment]
> In particular `` Use the `--help` option on any CLI command to learn more. `` is not as clear as I thought. Perhaps we should prompt with an example: `` for example, `pretext build --help` ``

It should be easy to autogenerate the string

```
For additional help, use
  pretext build --help
  pretext init --help
  pretext new --help
  ...
```

I would also be in support of adding a `--all-help` command that would print the standard help plus `pretext build --help` and friends at the same time.

**Comment by StevenClontz** [comment]
I'm not inclined to work against the Click library we use for CLI design. But if we can implement these suggestions within Clicks existing patterns for managing help text, let's look into it.

**Comment by StevenClontz** [comment]
I quickly tried to adapt https://stackoverflow.com/a/58018765 and got a full-help dump working, but it read `Usage: main view` rather than `Usage: pretext view` (or `Usage: /path/to/python -m pretext view`, etc.). I'd welcome a PR if anyone else wants to take a stab at doing this in a low-bloat manner, but I think the improvements at a80bb3e might be sufficient.
