### ISSUE TITLE
Don't track verbatim pretext-core resources

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#21]
Since `/pretext/static/pretext` and `/pretext/static/xsl` are exact mirrors of a particular commit of rbeezer/mathbook, we could instead have a file `/pretext/static/CORE_COMMIT` where we put the commit we want to work with, and then have a developer tool that pulls the files to those folders which are gitignored. (Note that this won't require end-users to have git, since these ignored files will still be bundled into the package published to PyPI.)

**Comment by oscarlevin** [comment]
Following up, related to #70, we don't have a great way to import the static resources.  The importlib.resources package allows access to files that we distribute with pretext-cli, but not directories.  In 0.1.3 we fixed this problem with a hacky fix, but it would be nice to have a more robust solution for dealing with core pretext xsl and python files.

**Comment by StevenClontz** [comment]
we don't anymore
