### ISSUE TITLE
factor out build.diagrams into several separate functions

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#210]
We can leave diagrams to build all at once, but we should support users importing the library as a script to only build a subset of elements.

**Comment by StevenClontz** [comment]
See discussion at https://groups.google.com/g/pretext-support/c/0GspWGzKwlM/m/NjdEy6_cBAAJ

**Comment by Alex-Jordan** [comment]
Do you have thoughts on the idea to "prompt" users for each diagram type? Not by default, but only if some argument is passed to `-d`. 

This would avoid factoring out build.diagrams.

**Comment by StevenClontz** [comment]
I'm open to allowing an argument for `-d`. I think Click won't allow an option to take an optional argument, so I might need a different API for this.

But https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/build.py#L37 is pretty complicated already; dividing it into subconcerns will expose more functionality and keep the code cleaner. As @davidfarmer alluded to in the Group discussion, most authors don't have huge books that need this kind of fine tuning, they just want diagrams to Just Work. A book like APEX probably needs to wire up a build script to the library directly rather than invoke the CLI in any case.

**Comment by StevenClontz** [comment]
Done this week.
