### ISSUE TITLE
Meta-issue: stylesheets to support

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#211]
I'm reviewing the documentation, and would like to remove as much `xsltproc` as I can.  Moving all the stringparams to the **publication** file is one line of attack.

The other would be to have some functionality exposed via the CLI.  Rather than spam the issues here with multiple new issues, maybe this can be a meta-issue to track progress?

These are stylesheets which (mostly) are discussed in the Guide and then `xsltproc` is used to show how to use them.  Better the CLI knew how to use them?  Some are important (doctesting Sage), some are debatable (author-tools).

```
xsl/pretext-jupyter.xsl
xsl/pretext-litprog.xsl
xsl/pretext-revealjs.xsl
xsl/pretext-sage-doctest.xsl
xsl/pretext-solution-manual-latex.xsl
xsl/pretext-ww-problem-sets.xsl
utilities/author-report.xsl
```

**Comment by oscarlevin** [comment]
Is the suggestion to basically implement #30, with this list of build targets?  Or is the idea to allow the calling of any xsl file packaged with pretext?  Right now, the custom xsl functionality allows for a users xsl file to be built against, but not those packaged with pretext, I think.
