### ISSUE TITLE
image archive attributed not respected

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext-cli#212]
An `image` element can have an `archive` attribute. For example, `archive="png eps"`.  This can also be the text content of `docinfo/images/archive` as a global value for all images.

When an `image` has this (either locally as an attribute or globally from docinfo) then what should happen is those image file formats should be built and placed adjacent to the folder where the primary image file is. For example if we are going to see an SVG image that lives in `generated/latex-image/`, then adjacent to that foo.svg we should have foo.eps and foo.png. And HTML output provides links to the archived image formats underneath the image.

The CLI diagram build is not taking this into account. For example if I do `pretext build -d html` on a project with an `<image archive=`asy`><asymptote>...` we get an image .html file inside `generated/asymptote/` but we do not also get the archival .asy file.

**Comment by StevenClontz** [comment]
Do we know where in https://github.com/PreTeXtBook/pretext/blob/master/pretext/pretext or https://github.com/PreTeXtBook/pretext/blob/master/pretext/pretext.py this is impemented for reference?

**Comment by rbeezer** [comment]
We assume authors build what images they know they need, so not in scripts.

See HTML XSL conversion, and  search on "archive".

**Comment by StevenClontz** [comment]
Do we have any specific example of where this attribute is used in production, or documented anywhere? This is not actually a PreTeXt feature (as far as I'm concerned) if it lacks documentation or at least an implementation known to folks outside of this thread.

**Comment by rbeezer** [comment]
Demos in the sample article, look for `@archive`.

Fully documented where you would expect it:

Subsection 4.13.5: Image Archives 
https://pretextbook.org/doc/guide/html/topic-images.html#topic-images-archive

An inability of the community to fully embrace comprehensive documentation does not negate a feature being a feature.  ;-)

**Comment by StevenClontz** [comment]
Thanks for kindly responding to my snippy response. (-:

So, it is documented. But as per that documentation, it's historically been the user's responsibility to create the files, not PreTeXt's tooling (directly). So this is not really the CLI's regression in functionality from core pretext features, but a new feature request.

I'm looking at the guide and e.g. [Paragraph](https://pretextbook.org/examples/sample-article/annotated/section-side-by-side.html#p-939). There's no way the CLI can automatically do what the documention seems to indicate that PreTeXt "supports": any possible graphics format with any arbitrary file extension, e.g. `archive="png JPEG tex ods"` with a `<latex-image/>` isn't happening.

So I'd like a tighter spec for this request.

**Comment by oscarlevin** [comment]
For the short term, a user can generate all image formats using `pretext build html -d -df all`.  

Maybe eventually we check for `@archive` in the source and if we see it then we either automatically generate all image formats, or pick exactly the ones we want.

**Comment by StevenClontz** [comment]
Telling authors to run `pretext build -d -df all` and to figure things out themselves (perhaps via #210 + custom Python scripts) if they want a tighter build or other formats sounds more aligned with the current promises authors have been given historically.

Philosophically, anything that we haven't provided tooling to Just Work is a stimulus for migraines if authors ask how to take advantage of it. If we want Alex's suggestion that the CLI know how to produce all the different requested formats, I'd lobby that `@archive` be deprecated for a finite list of e.g. `@format-jpg="1"`, `@format-png="2"` image attributes (numbers indicate order of preference to show reader?) that aligns with what core PreTeXt Python knows how to produce from the usual suspects: `latex-image`, etc.

Apologies as always for my stubborn [I fight for the Users!](https://www.youtube.com/watch?v=DkTb7Pe2MtY&t=136s) attitude when PreTeXt has historically been aimed at more advanced developers.

**Comment by Alex-Jordan** [comment]
Some (but not all) GitHub alerts have been quietly filed away by my Gmail without me seeing them for the past few months. I'm just seeing a lot of threads now where I had assumed there was no discussion happening.

At the time, `all` was not supported for asymptote images. But in the meantime I added that here:
https://github.com/PreTeXtBook/pretext/pull/1694

Not sure if it's made its way to the CLI yet, but it'll be there at some point now. I'm happy with using `-df all`. But in the same way it was not supported for asymptote images, it may not be supported for `sageplot` (I haven't looked). And if more image thingies come to be supported, we should make sure they support `all`.

(OK, I looked, and `sageplot` does support `all`.)

**Comment by StevenClontz** [comment]
I just pushed and update to the core commit, and [we already pass along 'all' to core Python script's outformat](https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/build.py#L45), so this should be working on the next update to the CLI.
