### ISSUE TITLE
`pretext build --all`

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#215]
I'm working on https://github.com/PreTeXtBook/pretext/pull/1680 and I've created a project manifest intended to produce everything desired for the website. Naturally I defined my targets in the correct order to be built, so one could `pretext build html && pretext build html-oscar && [...]`.

So this could be streamlined by supporting `pretext build --all` (or `--all-targets`?) which iterates over the targets and builds each one.

**Comment by oscarlevin** [comment]
Would it also build `subset`?  Also, would we need `latex` if `pdf` was being built?  So perhaps the manifest could have a special `<target name="all">` that had an element `<targetnames>` that listed the names of the targets to build.  Or in general, allow a target to call other targets.  Or have `<target-group name="all">` that refers to `<target>` names.

**Comment by StevenClontz** [comment]
Maybe each target could belong to one group, like `<target name="html" group="full">`. Then `pretext build group=full` would iterate through all the targets with the `group` attribute equal to `full`?

This implementation limits each target to one group, but I think that's the main use case. If you want one target in multiple groups, you can have multiple copies of your target, one for each group (not DRY but I don't think the use case is compelling enough to complicate this further).
