### ISSUE TITLE
A better error message for pdf2svg issue [windows]

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#218]
Having set up a new windows machine a few times now, I keep running into the same error trying to build images: I don't have pdf2svg installed.  This is easily solved using the documentation if you know where to look, but it would be helpful to sniff out this particular error and handle it more gracefully.

**Comment by StevenClontz** [comment]
I assigned @oscarlevin but maybe this is really something that @rbeezer could address on the core side? I think https://github.com/PreTeXtBook/pretext/blob/master/pretext/pretext.py#L2932 is what's intended to handle this; what would you like to see there Oscar (or is something else happening)?

**Comment by oscarlevin** [comment]
Yes, that part of core is catching the issue with a somewhat useful message.  I find the traceback that is displayed scary and unhelpful.  What would be really nice is to either give a link to the documentation for installing pdf2svg, or better yet, offer to install it and add it to the path for you.

We could do this prior to building svgs, or perhaps we want a `pretext setup` (or a better name) that verifies that the required helper programs are installed.

**Comment by oscarlevin** [comment]
Partial work here at 15844ee..9661e41, which provides `utils.check_executable` and reports missing executables in `pretext support`.

Once the images refactor (#251) is complete, I'd like to add checks for those executables needed for each image type before they are built, and provide helpful suggestions for fixing the issues.

**Comment by oscarlevin** [comment]
The infrastructure for OS-specific missing executable messages is available as of 9db2eff48ba259dd09e79c7ec9ba8d7ec51e0072.  We should clean up the pretext documentation for windows and other OS instructions and then update the messages.

**Comment by oscarlevin** [comment]
I think this is good enough now.  Might revisit after documentation changes.
