### ISSUE TITLE
pretext organize

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#22]

**Comment by StevenClontz** [comment]
I've changed the title to reflect a broader scope. Here's what `pretext preprocess` might do:

- If an element has a title/caption but no xml:id, the title/caption is slugified to create one.
- Build latex-image and similar elements (replaces `--diagrams` on `pretext build`, but we might add a `pretext build --preprocess` flag as well.)
- Rebuilds the file system based upon XML content. (e.g. if I write a new chapter in main.ptx, it gets factored out into chapter.ptx and an appropriate xi:include is inserted instead)
- With a `--release` flag, adds random xml:ids to appropriate elements without them already.

There's probably plenty of other nice things we want to do to manipulate the source directly. @rbeezer remind me to get you to explain the "assembly" stuff I've seen in passing on pretext-dev.

**Comment by StevenClontz** [comment]
For ID-ing `caption|title`d elements without an ID, we could use this model:

```
[partId]-[chapterId]-[sectionId]-[slugify(title|caption)]
```

**Comment by StevenClontz** [comment]
This is another feature I'd only support if the default `source` subdirectory is used (as it requires deleting files).

**Comment by rbeezer** [comment]
>  [partId]-[chapterId]-[sectionId]-[slugify(title|caption)]

I'm unclear at what stage this will be used/generated, or how permanent it is, but I'd like new authors to realize that `xml:id` can end up being visible (HTML filenames), and can be simple and human-readable.  I really want to avoid lots of "ugly" identifiers in source.  XML has a bad reputation already.  Why is a modified title or caption not enough?

Rob

**Comment by StevenClontz** [comment]
This is a pattern similar to what I've seen some authors use e.g. https://activecalculus.org/prelude/sec-circular-traversing.html . Speaking of HTML filenames, I'd really prefer subdirectory support from PreTeXt core anyway e.g. https://activecalculus.org/prelude/[chapterId]/[sectionId]/ so maybe this is my opinionated workaround.

Regardless, this is just to get something inserted into source; if(when) an author realizes they don't like what's generated, I think it's easier to edit down an existing long generated `xml:id` than remember the `xml:id` attribute in the first place.

**Comment by StevenClontz** [comment]
At least for now, we'll abandon editing source files.
