### ISSUE TITLE
Trace data files for CodeLens interactive program execution

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#225]
There is now a core routine, `tracer()` with relatively standard arguments.  It creates JS files, which are pretty much one variable with a huge pile of trace data.  C/C++/Java  come from a dedicated Runestone server via `requests`.  Python programs are ananlyzed locally with Python (duh!), via two new modules copied from Runestone (so maybe those will need to be copied over for the CLI).  Results go into a `generated-assets/trace` directory.  In our HTML, a `script/@src` gets these files, one per program.

Analagous to YouTube thumbnails, or similar.  Pinging @bnmnetp

**Comment by bnmnetp** [comment]
So ... Does this mean that you can run pretext once to generate the traces and from then on it will use those until and unless you regenerate them?  I like that.  Most of the time the vast majority of the code is the same as the last time you ran it.

Although as a newbie I found it confusing that even though I used `-c all` I still had to go and run `-c youtube` to generate the youtube thumbnails.  To be clear this is with Rob's pretext script so I don't know if the behavior is different with pretext-cli??

I'm happy to consult or create a PR to include the appropriate files for the cli tool.

**Comment by rbeezer** [comment]
> Does this mean that you can run pretext once to generate the traces and from then on it will use those until and unless you regenerate them?

Exactly.  Using a hash or something to guarantee a match would be a feature to explore.

`-c all` means you are building an output format.  Maybe it should be something that screams "whole document'?  The CLI does take a less fine-grained approach, and I think supports rebuiling everything as a more routine task.  The `pretext/pretext` script has been re-imagined as a Swiss army knife for developers.  I must have rebuilt the same six traces about 50 times in the last 48 hours, and I want to be surgical about that sort of workflow.  ;-)

**Comment by StevenClontz** [comment]
To confirm, is the element I should scan the document for (to check if this needs to be done) `//program[@interactive = 'codelens']`?

**Comment by StevenClontz** [comment]
Also can you point me to a MWE (E=Element) to test this with?

**Comment by StevenClontz** [comment]
Thanks for holding my hand here - looks like we have a new python dependency. What do I need to install to have `pg_logger`?

**Comment by StevenClontz** [comment]
Okay, figured out we're redistributing it: https://github.com/PreTeXtBook/pretext/blob/master/pretext/pg_logger.py (ps the link https://github.com/pgbovine/OnlinePythonTutor/ is broken, I guess it's now hosted at https://github.com/hcientist/OnlinePythonTutor ?).

Then I found Brad's https://github.com/RunestoneInteractive/RunestoneComponents and https://pypi.org/project/runestone/ which seems to properly package/distribute this.

I'm going to see how hard it is to fix core `pretext.py` to use the runestone package rather than distributing a copy of `pg_logger.py`.

**Comment by rbeezer** [comment]
> to use the runestone package rather than distributing a copy of pg_logger.py

See  https://github.com/PreTeXtBook/pretext/commit/0b6700a3fd6290d5f1849cb7c8fd3e6a0d74f9ee

**Comment by StevenClontz** [comment]
Looks like the only edits made for pretext were to change an import statement to handle the unconventional package structure of core pretext python scripts. So this *should* be a one-liner once we `pip install runestone`, but...

Oooh this is *fun*:

```
pretextbook[dev] 0.6.6.dev0 depends on requests<3 and >=2.28
runestone 6.2.2 depends on requests==2.27.1
```

@bnmnetp any reason runestone hardwires that version of requests? To be honest I'm not certain why CLI currently requires 2.28 (I'm sure there was some bug fixed in that version - I'll have to wade through the commit history to find out what we said when we added it).

**Comment by StevenClontz** [comment]
Lol okay I did that on *Monday*. https://github.com/PreTeXtBook/pretext-cli/commit/522086272922adc34e387ce245647f263a662820 I'm not sure my rationale at the time and the commit message isn't instructive. @oscarlevin do you remember any isues with old versions of requests? Or was I just messing around with our requirements and got hasty?

I'm changing CLI requirements to just `requests==2.*` and crossing fingers.

**Comment by StevenClontz** [comment]
I think that if Rob accepts https://github.com/PreTeXtBook/pretext/pull/1742 to use the Runestone components package (after a `pip install runestone` to his VM), then this is working as of c2f7713 (well, once I update the core commit to one that includes my PR).

**Comment by oscarlevin** [comment]
@StevenClontz , I don't remember exactly why you picked *that* version of requests, although there was something that it fixed, probably just on my dev environment.  But I thought that it was the < 3 part that was important, and maybe you just picked the most recent 2.*.  Or maybe I'm thinking of another package.

**Comment by StevenClontz** [comment]
I think that there was an issue in `2.0` or beyond, but definitely before `2.8`. We'll wait until we hit this again and add a minimum version compatible with runestone components if that happens.

**Comment by StevenClontz** [comment]
Closed by https://github.com/PreTeXtBook/pretext/pull/1746 5371588607bac42e90ea728553a4f8cdb32ded9b
