### ISSUE TITLE
Monolothic `pretext build --regenerate` or `--preprocess`?

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#227]
We currently have `--diagrams` and `--webwork` options for `pretext build`. There's now new [trace data](https://groups.google.com/d/msgid/pretext-announce/671543ef-c736-1e21-a5e3-12424982cb5c%40ups.edu) we need to preprocess. There will likely be more in the future.

Do we want to expose individual propressing/(re)generation steps? Or should we just expose to the typical author a single `--regenerate` or `--preprocess` flag to use when they want to update all their images/webwork/codelens...

I think the answer would be "no", except for the proposal at https://github.com/PreTeXtBook/pretext/issues/1703 to cache hashes of source elements involved in long builds. If we have this, then a single monolith rebuild isn't terrible: only the updated elements would be rebuilt.

**Comment by rbeezer** [comment]
That's a great question, and I don't have a good answer.  Despite anticipating the possibility.  ;-)

What if we let @bnmnetp attack the CodeLens source and trace data, and see https://github.com/PreTeXtBook/pretext/issues/1703 goes?  And then maybe a `pretext-dev` discussion might be illuminating?

Note that not everything can be cached.  We will never know if a YouTube preview changes/disappears and/or if a MyOpenMath problem has changed.

**Comment by StevenClontz** [comment]
History repeated itself and this is basically the same as #245. I'm closing this one to stick with fresher conversation.
