### ISSUE TITLE
deploy to tgz?

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext-cli#229]
Could `pretext deploy` have an option to make a compressed file that one could simply unpack on their web server?

**Comment by StevenClontz** [comment]
For this to be `deploy`, we'd have to handle the business of FTPing (or whatever) the archive to the server. I have concerns that this is too implementation-specific for each server to have a standard way of doing this. Do you have a particular hosting provider in mind?

And before that, we'll need a `pretext build` format for tgz. I believe we have one for zip. It's a discussion with @rbeezer whether this is really a core pretext library feature.

**Comment by Alex-Jordan** [comment]
Maybe "deploy" is not what I wanted then, and "build" is. I'm looking to be lazy and have one simple command make the tarball that I can manually transfer to my web server. When I say it that way, it sounds very low priority :)

To answer your question, I would just be using `scp` to copy the tarball from local position to a place on the server. I would actually log in to the server to uncompress it.

> I believe we have one for zip.

Good enough for me. I'll look for that and try it next time.

**Comment by Alex-Jordan** [comment]
Given what I just posted, should I close this?

**Comment by rbeezer** [comment]
I replied to this on May 4 (by email?), but it didn't seem to make it here.  So I've re-opened this and am posting via the web interface.

Core routines make a "zip" file.  Alex seems happy with a `zip`.  Was there a strong technical argument for `tgz`?  it could be done, but might just be basically redundant.

**Comment by StevenClontz** [comment]
On this end I'm focused on deploying via Git to GitHub Pages (at least until we likely look at Runestone deployment in a couple of weeks), which doesn't even use `zip`. Of course, if core adds a `tgz` option we could expose it here as well, but I think that's a discussion for pretext-dev or https://github.com/PreTeXtBook/pretext/issues/

**Comment by rbeezer** [comment]
I thought to make a zip in the core routines, since there is similar code already for epub.

Is there technical preference for the tgz  first?

I looked for a PTX issue and didn't see one.  Could you make such an issue and link back here?  Maybe adjust this to having the CLI expose an eventual core routine/option.
