### ISSUE TITLE
Call arbitrary xsl file

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#23]
`pretext build custom`

**Comment by oscarlevin** [comment]
Not sure how this would work now that we have committed to having the official xsl in static.  In any event, bumping to far distant future.

**Comment by oscarlevin** [comment]
So here is what we discussed as a reasonable option.  Custom xsl is held in the project folder (tracked by the manifest).  When it is time to build, the custom xsl and the static xsl are both copied to a temporary folder, so that the custom xsl's import can know what the path to the "static" xsl is.

This would not work for customizing xsl that is called by pretext.py (image creation, etc) unless that was exposed as a variable for those functions.  Some functions, like those to build html/latex/pdf should be fine though, if they still need the xsl to be set in a variable instead of hard coded.  The more complicated functions might call more than one style sheet, which would make this especially difficult.

**Comment by oscarlevin** [comment]
With the new feature in core to call external xsl in html/latex/pdf builds (#160), I think we can proceed.  I'm going to take a stab at this later today, so please wave me off if you think I'm about to do something unreasonable.  Here is the plan.

1. The project.ptx manifest will allow a `<xsl>` tag that can point to some custom xsl that lives in the project's `xsl` folder. 
 (Or maybe `custom-xsl` folder?)  
2. When the user builds that target, the script copies all of the pretext xsl folder and all of the projects xsl (or custom-xsl) folder to two subfolders in a temporary directory.  The user's custom xsl then includes `../xsl/pretext-html.xsl` which is the same pattern many of use use now (when copying the custom xsl to the usr folder in mathbook as part of our build scripts).  
3. That's it.

Alternatively, we could copy all of pretext's xsl into the project directory once and let the user manage everything there.

Or the pretext-href idea?  I need to learn how that works I guess.

**Comment by StevenClontz** [comment]
Actually that will break if custom XSL imports another custom XSL from a relative path.

**Comment by oscarlevin** [comment]
We can copy all of the custom xsl folder together, and replace all pretext-href with the correct href?

**Comment by StevenClontz** [comment]
That works but we'd have to strictly enforce using a directory with only/all XSL in it, while also pointing to the root XSL used for the custom transform.

**Comment by StevenClontz** [comment]
I think, for the CLI, it might be reasonable to say you can use a stand-alone XSL file per target that only imports using pretext-href.

**Comment by oscarlevin** [comment]
Right now I often have `custom-latex.xsl` import both `custom-common.xsl` and `pretext-latex.xsl`.   I guess I don't need to do this, except that it makes sense to have custom-common customizations that both -latex and -html use.

Assuming we copy the project's xsl folder to the temporary directory, switching pretext-href to href along the way, then any relative path imports should work, right?

**Comment by StevenClontz** [comment]
So this...

```
<target>
    <xsl>xsl/custom-html.xsl</xsl>
</target>
```

would infer that XSL lives in `os.path.dirname("xsl/custom-html.xsl")` that is `"xsl"`, copy that to a temp directory, then rewrite each XSL file in that directory using https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/utils.py#L229. Probably want some checks that `os.path.dirname("xsl/custom-html.xsl")` doesn't contain stuff that would make that copy step really long?

**Comment by StevenClontz** [comment]
*whispering: in CLI 1.0 we should hard-code source living in source, xsl living in xsl, output living in output, so we don't have all these gotchas involved with authors doing terrible unexpected things...*

**Comment by oscarlevin** [comment]
Or we copy every `*.xsl`, maybe `*.ent`, file in the home directory of `custom-html.xsl`.  This requires that the main custom-html.xsl file be in the root of the xsl directory.

_whispering back: yeah, I wanted to say `<xsl>custom-html.xsl</xsl>` and assume that lives in `xsl`_

**Comment by oscarlevin** [comment]
By the way, something else to think about: the method for styling latex now is to use `mathbook/xsl/latex/pretext-latex-AIM.xsl` or similar, which imports `../pretext-latex.xsl`.  So I guess for using the CLI, we would need to have a custom xsl that imports `pretext-href="latex/pretext-latex-AIM.xsl`.  

In other words, we don't support 
```
<target>
    <xsl>latex/pretext-latex-AIM.xsl</xsl>
</target>
```
or similar.

**Comment by StevenClontz** [comment]
Hmm, yeah, if you want custom XSL that's exactly PreTeXt-supplied XSL, having a dummy custom XSL file that imports pretext-href would do the trick. I'd rather just have that been the solution for now rather than something like `<target><pretext-xsl>latex/pretext-latex-AIM.xsl</pretext-xsl></target>`

**Comment by daverosoff** [comment]
I want to test this feature. Our books have weird numbering that I supply with an XSL wrapper that imports `pretext-html.xsl`. I put that file `custom.xsl` into a new directory `xsl` in the top level of my project, and added `<xsl>xsl/custom.xsl</xsl>` to the html target in `project.ptx`. The result follows (there were further exceptions that I trimmed). Am I doing it wrong? Thanks.

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pretext/project.py", line 267, in build
    builder.html(target.source(),target.publication(),temp_dir,target.stringparams(),custom_xsl)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pretext/build.py", line 16, in html
    core.html(ptxfile, utils.linux_path(pub_file), stringparams, custom_xsl, output)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pretext/static/pretext/pretext.py", line 1589, in html
    xsltproc(extraction_xslt, xml, None, dest_dir, stringparams)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pretext/static/pretext/pretext.py", line 1732, in xsltproc
    xslt = ET.XSLT(xsl_tree, access_control=control)
  File "src/lxml/xslt.pxi", line 408, in lxml.etree.XSLT.__init__
  File "src/lxml/etree.pyx", line 316, in lxml.etree._ExceptionContext._raise_if_stored
lxml.etree.XSLTParseError: Cannot resolve URI /tmp/xsl/mathbook-html.xsl
```

**Comment by daverosoff** [comment]
I deleted a previous comment because there was something I overlooked. I'm not quite sure what the solution is for the "thin XSL" concept, since my wrapper imports `pretext-html.xsl` but the CLI doesn't find it in the right place. My `project.ptx` looks like this:

```xml
<project>
  <targets>
    <target name="html">
      ...
    <xsl>xsl/custom-html.xsl</xsl>
    </target>
</project>
```

**Comment by daverosoff** [comment]
> 
> 
> I deleted a previous comment because there was something I overlooked. I'm not quite sure what the solution is for the "thin XSL" concept, since my wrapper imports `pretext-html.xsl` but the CLI doesn't find it in the right place. My `project.ptx` looks like this:
> 
> ```
> <project>
>   <targets>
>     <target name="html">
>       ...
>     <xsl>xsl/custom-html.xsl</xsl>
>     </target>
> </project>
> ```

Aha, I figured it out—I changed the import to `xi:include/@pretext-href="mathbook-html.xsl"`. Probably if I had read more of the issues here I would have known. Thanks folks.

**Comment by StevenClontz** [comment]
https://github.com/PreTeXtBook/pretext-cli#importing-pretext-provided-xsl-into-custom-xsl added info here
