### ISSUE TITLE
Ensure CLI is compatible with core sample-article

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#231]

**Comment by StevenClontz** [comment]
Stop me @oscarlevin if you're already working on this but it's something to do before dropin starts in an hour

**Comment by rbeezer** [comment]
Not sure where this is going.  A `project.ptx` file will be welcome, but please do not move or rename any files.  I believe all the rearrangemets needed for "managed directories" are in place.

**Comment by oscarlevin** [comment]
Go for it @StevenClontz .  Yes, I think the only thing we would add is the `project.ptx`, and then on our end a script that downloads the most recent sample-article folder and runs `pretext build --generate` on it.

**Comment by StevenClontz** [comment]
Done at https://github.com/PreTeXtBook/pretext/pull/1743

I was optimistic and went ahead and wired the requirements to be 0.7.0.

**Comment by StevenClontz** [comment]
Closing in anticipation of upstream merge
