### ISSUE TITLE
Can remove the fake WeBWorK server stringparam (soon)

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext-cli#236]
Now that https://github.com/PreTeXtBook/pretext/pull/1714 is merged, then once that makes its way to the CLI, then the CLI no longer needs to respect the "fake" stringparam in a target with `stringparam key="server"`.

**Comment by Alex-Jordan** [comment]
Some discussion at:
https://groups.google.com/d/msgid/pretext-dev/CAH%2BNcPav8qEZeRJtPsZeZzU6phz2kA3z%3DwzswNA1GZCytKbwBQ%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by StevenClontz** [comment]
@Alex-Jordan what's a minimal webwork example I can include in a `pretext new book` (both source and publication info)? Both to test the above two commits and to provide authors an MWE for seeing how webwork can be integrated?

**Comment by Alex-Jordan** [comment]
Here are some references to help test against other servers:

Paragraph 
https://pretextbook.org/doc/guide/html/webwork-processing.html#p-1488

Section 42.7: WeBWorK Options 
https://pretextbook.org/doc/guide/html/publication-file-webwork.html#publication-file-webwork

**Comment by StevenClontz** [comment]
Closed by b0fe15920d39064492fabcf6a4324b725ab384cd 1304710c86024804b8e73c4b2f078436d0b5bf48 28ae0e4f8232fe8247be73cf6994fcf076c4e030
