### ISSUE TITLE
Info: small change to interface for pretext/pretext script

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#238]
Not sure how closely you monitor changes.  So this is just a heads-up that [d60aa540ccecb730f43028cda136c3abf06ef573](https://github.com/PreTeXtBook/pretext/commit/d60aa540ccecb730f43028cda136c3abf06ef573) is strictly contained in the (crummy) interface on the `pretext/pretext` side, so you can ignore it.  And close this.

**Comment by StevenClontz** [comment]
Thanks for the heads-up. Generally unless the `pretext/pretext.py` API has changed somehow, our operations on this end shouldn't be affected.
