### ISSUE TITLE
Interactive `pretext new` with optional command-line options

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#24]
A `pretext new` should start an interactive shell to provision the new project. However, if e.g. `--title="My Great Book"` is provided, that is used instead.

**Comment by oscarlevin** [comment]
How about this for `pretext new`:

1. `pretext new` will initially produce a `outline.xml` file that that user can fill in with title/chapter/section info.  Running `pretext new` again will use that `outline.xml` file to build the project.
2. `pretext new --interactive` will interview the user through a series to prompts to fill out the `outline.xml` file, and then rerun `pretext new` automatically to transform the `outline.xml` file to build the project.
3. `pretext new --clean` would remove the `outline.xml` file so to not accidentally overwrite other work.  Or maybe `pretext new` gives a warning if the target files already exist.

I was also thinking about way this generates the files now.  How about we assume that the user runs `pretext new` from inside the project folder, which they make themselves.  So more of `git init` than `git clone`.  This would avoid the necessity to provide a title.

**Comment by StevenClontz** [comment]
1/3. So I have to admit that I haven't seen the light as to the value of https://github.com/oscarlevin/pretext-app/blob/master/data/outline.xml since it's almost already a PreTeXt file itself. If I'm writing all that by hand, I'd be just as productive writing the `main.ptx` itself. Perhaps the middle ground is allowing a way to use `pretext new` to get the truly minimal boilerplate out of the way in a single `main.ptx`, and then let the user edit it to add in author/title/chapters/sections manually. Then we write a feature (in Python or XSL) that reads in any PreTeXt document (with an arbitrary file structure), and refactors it into an organized file structure with `xi:include`s. Let me know if there's a usecase for the outline I didn't appreciate in your pretext-app that isn't covered with this plan.

2\. I think I want the interactive workflow to be our default. In general, I'd rather add keystrokes for the power users than the newbies. (Eventually alternative defaults can be set in a configuration file.) But maybe `pretext new --minimal` skips the interactive bit, and can be used as described above.

Coda: Again thinking about casual users, I can see a pain-point where they go into `My Documents`, then run `pretext new`, and suddenly all their generated files are mixed in with hundreds of other files without any great way to show them where they are (and possibly overwriting other files). Also this functionality is already available with `pretext new title .`. If we don't want to require a title, `new-pretext-document` seems reasonable for the folder. (I think I'm in favor of `cd`ing into the new folder upon creation if that was a concern.)
