### ISSUE TITLE
Consider changing `--diagrams|-d` to `--generate-assets|-g`

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#245]
Since many of the steps we're doing in `--diagrams` aren't diagrams, maybe this should be renamed.

**Comment by bnmnetp** [comment]
I love it!  If this had said `--generate-assets` I t would have saved me a lot of time.

I might also add that if "generated" is empty it might be a really good time to tell the builder that they may need to look deeper and run the build command with additional parameters.

OR

make the cli even more intelligent and if there are generated things that are not there or out of date then a pretext build  should recreate them!  That is hard in the out of date case, but not hard in the non-existent case!

I would lean towards not having any generated assets included in github.   That is why Runesonte.academy exists!!  But in the case where someone wants to host their own then they are likely able to generate them.

I am also in favor of --generate-assets  as in my weekly scripts to update books I would always include that as an option. I do not know and do not want to know who has changed what from week to week!

**Comment by oscarlevin** [comment]
I really like `--generate-assets` that build everything.  For image heavy books, being able to generate webwork separately is also nice, so `--generate webwork` or whatever the syntax would be is good.  Maybe though just `--generate images` that does all of the other stuff would be better.  My concern is that for "images" that don't have xml-ids, PreTeXt assigns them a id based on their location in the source.  So if you add a latex-image, that might change the expected filename for an asymptote image??  @rbeezer ?

**Comment by StevenClontz** [comment]
I was thinking `--generate [ElementName]` would be easiest to communicate to authors. Although this means we have a lot of different types of `<interactive/>`s to lump together. But then we have `<webwork/>`, `<sageplot/>`, etc. Then when someone asks "why doesn't my `<sageplot/>` show up" we can say "run `pretext build --generate sageplot`" and folks won't feel like the process is too esoteric?

**Comment by rbeezer** [comment]
Right now (iirc!) image filenames for `latex-image` come from the enclosing `image`.  Logically (my logic!) they should come from the `latex-image`. 

Lots of under-the-hood work on identifiers, but currently derailed by Runestone documentation.  Eventually we will have `@label` for human-readable identifiers/strings, which will form filenames.  The above paragraph will be a deprecation, which I think I can manage gracefully with pre-processor.

And then we will have default/auto-generated labels.  And finally, to my point - they will be less sensitive to source changes in faraway places.  Do not act on the above, which is not happening ASAP.
