### ISSUE TITLE
Never show traceback unless `-v debug` is requested 

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#249]
In an effort to make the CLI more friendly to non-coding folks, we could make it our design goal to have all errors be more user friendly by only providing easily read error messages without any python supplied traceback info (unless the user asks for debug level verbosity).

**Comment by oscarlevin** [comment]
This should be mostly accomplished by e3e95cb0f02a5aba4da913644e99dbdbe9618019, which wraps all calls to core in the build and generate steps in try/excepts. 

I'll leave this open until the end of next week though, because:
1. There might be other errors we find that require a similar treatment
2. We might want to catch more specific exceptions with better messages

**Comment by StevenClontz** [comment]
Work has progressed and ongoing.
