### ISSUE TITLE
Document ubuntu/wsl setup steps

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#257]
Working on WSL I had trouble working with pdfCropMargins, because "neither Ghostscript nor pdftoppm" were installed.  This was a quick `sudo apt install` fix, but it strikes me that we should give a single `sudo apt install ...` command that provides everything a user needs that isn't already taken care of by pip.

**Comment by StevenClontz** [comment]
Add to this OSX I think.

It may be worth considering whether we want users to install everything upfront, or if we try/except certain features and prompt the user to install things as they introduce elements to their source or use features that require extra steps.

**Comment by StevenClontz** [comment]
Closed by https://github.com/PreTeXtBook/pretext-cli/pull/311 (despite the ongoing battle to keep this updated)
