### ISSUE TITLE
Reconsider versioning workflow

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#259]
It's unclear to me that releasing RCs has much value. Instead, I think having a regular (weekly?) schedule of packaging beta releases with the latest core commit + any enhancements we're making on the CLI would be valuable to users active on -dev/-support. Then we can take the last beta release that seemed stable on a coarser schedule (every two months?) and cut that as a public release.

Or maybe if we have packaging automated enough (a github action) we can just push `x.y.zbYYYYMMDD` each day we have changes.

**Comment by bnmnetp** [comment]
Automation is a good thing!
