### ISSUE TITLE
add `<view-port>` to project.ptx

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#262]
A user might want a different port for different subset builds, and not have to remember to do the `-p` command when you view.  If the port number was put in the project manifest, then they could have multiple pages open at once.

**Comment by StevenClontz** [comment]
I thnk I like `<view port="8888"/>` here.

Worth noting that if we hardwired `output` as our output, we could disaccosiate `view` from targets entirely and just serve up `output`...
