### ISSUE TITLE
Discussion: Should requirement.txt warn if old (minor) version?

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#276]
I find the warning message frightening when building, like I've done something wrong.  But it's not my fault, it's the developers.  Yes, we should keep this info as debug, and report it in `pretext support`.  But @rbeezer does a good job at not breaking previous builds when he improves core, so I'm not really sure what we are warning users about.  Perhaps when there is a critical error, we can inspect requirements.txt and suggest a user look at `--help` if we think a feature might have changed.

**Comment by StevenClontz** [comment]
I disagree - you should not `pip install --upgrade pretextbook` unless you're also willing to update your `requirements.txt`, which I'd do after confirming my project builds with the new CLI version. Otherwise you're not being truthful in the requirements of your project.

**Comment by StevenClontz** [comment]
Closing for now based on Zoom discussion, but we'll be on the lookout for user reports on this issue.
