### ISSUE TITLE
pip install `pretext-cli`

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#279]
https://github.com/PreTeXtBook/pretext-cli/blob/5b21dd0b14360c68dd7efcd410bc4a69412f89a0/docs/quickref-cli.tex#L60

That line is aspirational - we have `pretext-cli` requiring `pretextbook` as a hack, but we haven't renamed yet.

Maybe https://github.com/simonw/pypi-rename is a pattern we can follow.

Maybe we can ask nicely to adopt just the `pretext` namespace on PyPI (current project is 0.0.4 and hasn't been touched in many years).

**Comment by StevenClontz** [comment]
I'm pushing this to a new 1.0.0 milestone, whether we switch to pretext-cli or maybe we're lucky and our request to adopt pretext is accepted.

**Comment by oscarlevin** [comment]
A recent very long support thread ended up being an issue with the `pretext` pypi package also being installed.  We really should try reaching out to the developer to see if his project is still active enough to be hosted there, and ask very nicely if he would be willing to let us use `pretext` for PreTeXt

**Comment by StevenClontz** [comment]
I'll send an email and copy you on it Oscar.

**Comment by oscarlevin** [comment]
Thank you!

**Comment by oscarlevin** [comment]
I think this is redundant now that we `pip install pretext`

**Comment by StevenClontz** [comment]
In retrospect, I should have added `pip uninstall pretext-cli` to the instructions for the final 0.x release of `pretextbook`, for the few folks that may have installed things that way. But I think we didn't really publicize it too much, so it's not worth any effort beyond keeping it in mind for `-support`.
