### ISSUE TITLE
pretext build pdf support other engines on specific build targets?

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#28]
If the user has a latex compiler available, we should provide `pretext build --format=pdf` which builds LaTeX and converts it to PDF.

**Comment by oscarlevin** [comment]
In addition, an option (that can be stored in the config file) of which engine (pdflatex, xelatex) to use, or even which latex build command (like latexmk with options).

**Comment by StevenClontz** [comment]
Building with `pdflatex` in 556134e - pushing this back to 0.3 to handle other engines.

**Comment by oscarlevin** [comment]
Now building pdf as a separate target, using whatever engine is specified in the project.ptx manifest.

Does it make sense to move the tex engine into targets?

**Comment by StevenClontz** [comment]
One idea: have `<target><executables/></target>` override the `<project><executables/></project>`.

**Comment by StevenClontz** [comment]
We have `pdf-method` that choses a LaTeX engine (oof why didn't we call it `tex-engine`?), so I think this is closeable.

https://github.com/PreTeXtBook/pretext-cli/blob/main/templates/project.ptx#L21
