### ISSUE TITLE
scripts/update_core.py fails

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext-cli#281]
```
Traceback (most recent call last):
  File "/Users/bmiller/src/pretext-cli/scripts/update_core.py", line 2, in <module>
    from pretext import CORE_COMMIT
ImportError: cannot import name 'CORE_COMMIT' from 'pretext' (/Users/bmiller/.virtualenvs/pretext/lib/python3.9/site-packages/pretext/__init__.py)
```

I'm not sure what the best way to keep up with the core is?  I would make an editable install of this package and run update_core.  But maybe for now I'm destined to be a day behind?  Are alphas generated every time Rob commits to master?

**Comment by oscarlevin** [comment]
I'm not sure why you get this error; I just tried it on my machine and it worked fine.  I've updated CORE_COMMIT in __init__.py just now, so maybe try again after a fresh pull?

Actually, what you probably want is to use the symlink_core.py script, which allows a separate folder for the core that you can maintain separately.  I think we still have that mentioned in the readme.

Right now we don't have any system for when we create a new alpha, other than if we fix something in the CLI, and maybe we remember to update the core commit or maybe not.  I think the idea of automatically building a new alpha version every night in case there is a update to pretext (which likely will be every night) is worth further discussion.

**Comment by bnmnetp** [comment]
Indeed, I missed the script when I looked..... It may also be that I had the wrong virtual environment enabled.  I have one for pip installed cli and another for dev.

thanks.
