### ISSUE TITLE
Draft -vs- Published

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext-cli#282]
As I am working on an interface to allow authors to keep their books up to date on Runestone Academy I have a feature request to discuss.

On Academy we can publish books as either "draft" or "published" -- this is nice for authors who want to let us do the build and then do some more review before publishing.

when I say `runestone deploy` in my script it moves the draft -- where an initial build ends up -- to published.

It would be nice to support both of those in the project file for a runestone target, and maybe for other targets as well?

thoughts?

**Comment by StevenClontz** [comment]
All: See discussion at https://groups.google.com/g/pretext-dev/c/jbrJ7GO2d6E/m/DYjDcUR4BQAJ?utm_medium=email&utm_source=footer

**Comment by StevenClontz** [comment]
Closing as I think we don't need additional functionality on the CLI side for this workflow? Brad check out https://pretextbook.org/doc/guide/html/runestone.html and let us know if that or the CLI should be fixed.
