### ISSUE TITLE
directory of time-stamped logs

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#285]
Rather than overwriting `cli.log`, we should have a gitignored `logs` directory that has `TIMESTAMP.log` for each run. It's easy to destroy this directory if someone wants to tidy up, but this way a log isn't lost if another cli command is run.

**Comment by oscarlevin** [comment]
Implemented for 2.0.0, but should we have a cleaning functionality that removes old .log files, or all of them?  I'm thinking that the average user will accumulate LOTS of these over the course of a project.  Do we really need to keep anything older than a day?
