### ISSUE TITLE
Epub/Kindle/Braille issues

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#286]
As in #30 , we would like to support building epub, kindle, and braille with the CLI.  Here are the current stumbling blocks:

1. We would need to ship the `script\mjsre` folder from core pretext which has a js script `mj-sre-page.js` that gets called.  This in turn requires a few packages that should be installed into the `mjsre` folder (a global `npm` install of these packages doesn't seem to work.  This means we either need to test installing the entire scripts folder into the user's home directory (say in `.pretext/script/mjsre`) and have them npm-install the packages (and this might not even work, depending on what assumptions `pretext.py` makes about the paths to that folder), or include the entire node_modules folders that get installed when the requirements are installed.
2. Likely we also need core's `CSS` folder, since the script copies local css to do the formatting.  This is less of a big deal.
3. I have not been able to test this out, because on Windows I get a file permission error.  I think I get this no matter what (using `pretext/pretext` for example), so it seems like even if we get these supported, we can't support windows as is.

So the question is, do we proceed?

**Comment by rbeezer** [comment]
Braille requires `liblouis` which I install from source.  Usually OK, but sometimes some gotchas.  If you didn't do braille, you don't need SRE (modulo the "speech enhancement" we uncovered in Ann Arbor, which maybe should move under some flag/switch).  That leaves MathJax for EPUB, no way around that.  At least MJ has a broad base of users who try to use it locally (or server-side).

@mitchkeller is the one to speak to Kindle.

**Comment by mitchkeller** [comment]
1. I don't think it would be awful if the CLI shipped a node_modules folder that had the versions that the current `package.json` file specifies. The publisher would still need to have `node` installed, but that's no different than requiring that they have a TeX distribution installed to build PDF.
2. Yes, this folder is going to be required.
3. ¯\_(ツ)_/¯ 

I think once epub-svg builds, epub-kindle should mostly be fine. Well, that's assuming the routines that build generated assets can produce png files for those images. Non-generated assets will also need to have a png version available (for things that are SVG in HTML), but I feel like it's already something we assume that authors do for themselves.

**Comment by oscarlevin** [comment]
The windows permission error should be fixed by https://github.com/PreTeXtBook/pretext/pull/1779

**Comment by oscarlevin** [comment]
The issues here are resolved, even though braille is still in the works and there are a few tweaks needed for epub/kindle.  All tracked in #30
