### ISSUE TITLE
`pretext generate --all-formats` is misleading

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#287]
The `--all-formats` seems to depend on the format of the default target (or whatever target you specify), not all possible output formats.

**Comment by oscarlevin** [comment]
Maybe we replace this with `pretext generate --everything` which creates all output formats for all target formats in the manifest.

**Comment by StevenClontz** [comment]
I don't think we need to change the name necessarily, but we should change the behavior.

**Comment by StevenClontz** [comment]
Actually should we always iterate over all target formats for deciding the asset types to build, unless a target is specified (as in a `pretext build -g` call)?

**Comment by oscarlevin** [comment]
I agree.  I'm happy to get this done.  So:

- On a `pretext build -g` we build default assets for the first target, as you would expect when you do `pretext build`.  Or `pretext build print -g` is the default assets for print.
- On a `pretext generate` we generate all default assets for all `target.format()` that show up in the manifest.
- On a `pretext generate --all-formats` we generate all assets for all formats in the manifest.

**Comment by StevenClontz** [comment]
sounds good to me. I think it's implicit but `pretext generate -t TARGET_NAME --all-formats` would generate all asset formats associated with the format of the `TARGET_NAME` target.

**Comment by StevenClontz** [comment]
I was thinking we'd iterate over every target to collect all the needed asset formats first, then iterate over that collection to build those formats.
