### ISSUE TITLE
consider changing organization of static module and functions

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#292]
Right now we have `static.path` and `static.template_path`. Maybe we don't need just a `static` module, but separate this stuff out to `core` and `template` modules?

**Comment by oscarlevin** [comment]
Really we have three: `template` `static` and `core`.

**Comment by oscarlevin** [comment]
How about switching `static.templates_path` to just `templates.path`?

**Comment by StevenClontz** [comment]
Did we keep support for `symlink_core` script somehow?

**Comment by oscarlevin** [comment]
Ah, no I did not.  Should be easy to do, just changing the location of the symlinks to the user/.ptx folder.  

Is the workflow to run the `symlink_core` script and then run `update_core` to go back?

**Comment by StevenClontz** [comment]
yeah. I'm working on a PR for the refactored static resource management, so I'll include that in my work.

**Comment by oscarlevin** [comment]
Perfect.  Note that we just need to change the symlinks for the folders (and it should also include "static" and "css" now), since pretext.py is still in the original core folder.

**Comment by StevenClontz** [comment]
Closed by 21eeb2648e34217dcb7959e64fc8d73499694000
