### ISSUE TITLE
Factor out `view` to have different functions for each target format

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#293]
For epub we don't want to spin up a server.  For pdf, we really don't need this either.

**Comment by StevenClontz** [comment]
I use `pretext view pdf` all the time. Very convenient to open in the browser if you're editing on CoCalc/vs code

**Comment by StevenClontz** [comment]
As for epub, how *can* an author view the built output?

I suppose we could have some trys/excepts for non-HTML format targets. We could attempt https://docs.python.org/3.6/library/os.html#os.startfile on Windows to open the containing directory in Explorer. We could use `code path/to/output` if we know we're in VS Code.

**Comment by oscarlevin** [comment]
For pdf, I agree viewing in the browser is great, but we don't need a server for that.  Maybe.

I don't know of easy ways to view epub.  There is Calabre which is cross platform.  Other readers exist as well, but for kindle I think you need the kindle previewer.  Anyway, what I was thinking is that we would just point to the file and suggest you open it with your viewer.

**Comment by rbeezer** [comment]
Calibre is a cross-platform "desktop" viewer.  That's what I test with.  Cheating just a bit, since it renders the MathML version using full-blown MathJax 9as I understand it).  ;-)

I'd bet a Mac will (a) have iBooks or similar, (b) open with that without too much effort.

**Comment by bnmnetp** [comment]
Lots of options on the mac:  [Top 10 Free epub readers for the mac](https://pdf.wondershare.com/macos-10-14/epub-for-macos-10-14.html#:~:text=10%20Free%20EPUB%20Readers%20for%20macOS%2010.14.%201,4%204.%20FBReader.%205%205.%20NOOK.%20More%20items)

I would love to give this a try on our httlacs.

**Comment by rbeezer** [comment]
There are lots out there, but my experience with Android is that very few can handle what we throw at them.  We aren't writing pulp fiction after all.

**Comment by oscarlevin** [comment]
This should now be working, after #303
