### ISSUE TITLE
Adding targets to `project.ptx`

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#294]
Having a standard Runestone setup available was requested by @bnmnetp in #30, and now with epub and epub-kindle available, folks are going to want more build targets in their project manifest.  How should we handle such new targets?  I see three options.

1. We keep the project manifest simple for `pretext new` and `pretext init`, and improve the documentation to list steps to add new targets manually (including how to have a new publication file for runestone).
2. We have the standard project manifest have every possible target that we currently support, and `new` and `init` with additional publication files for those targets that need them.
3. We add new targets programmatically as a user needs them, with something like `pretext add runestone` or `pretext addtarget runestone`, thus keeping the default new setup simple and less intimidating.  We could also prompt the user when they try `pretext build runestone`: "runestone isn't a target in `project.ptx`.  Would you like to add this target? Y/n".

Thoughts?

**Comment by rbeezer** [comment]
EPUB requires MathJax, which requires node, which requires npm.  Do we want new users immediately trying to get EPUB with no extra effort and no reading documentation?  (Since they are getting nice HTML and nice Runestone possibly with no effort - eg no LaTeX.)

**Comment by StevenClontz** [comment]
Anything that edits `project.ptx` is a new leap. We'd have to read the file, parse it, edit it in memory, then write back to disk (hopefully without clobbering anything like comments). It's all plausible but not something I want to rush. So I'm marking this as far-distant now, but we can go ahead and add runestone to `pretext new`/`init`.

**Comment by oscarlevin** [comment]
Given that it is now much easier to add a target in v2.0, I think we can abandon the idea of adding them programmatically.
