### ISSUE TITLE
tests and view

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#295]
While looking into customizing `pretext view` for #293 , I stumbled on a messy error message if you try to run `pretext view` outside of a cli-managed project.  So I added the same logic we use for `build` there, as well as for `generate` and `deploy`.  But now the tests fail, and I'm not sure why.

One thing that would help is @StevenClontz can bring me up to speed on how the tests work and how to run them prior to pushing.  If we could take a few minutes to do this at our next checkin, that would be great.

**Comment by StevenClontz** [comment]
I think this is fixed by 8a76263a5f768d5e30126cf6ac9ef0f7db794745
