### ISSUE TITLE
Documentation in PreTeXt

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#31]
We should [eat our own dogfood](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) and document things in a PreTeXt document, which is `pretext publish`ed ala #13. Our README (which is also used in PyPI) can simply link to this documentation.

**Comment by rbeezer** [comment]
I'd love to be able to do an automated pull of this repo, and process this documentation for inclusion at the main PreTeXt site as part of the overall documentation.

**Comment by StevenClontz** [comment]
Note: I started work on this in e5a5e4c656a14932de3515854554de2e5d940f3e

**Comment by StevenClontz** [comment]
@rbeezer I was skeptical when you suggested this at first, but if we can figure out a workflow that guarantees that our documentation is updated in the PreTeXt Guide simultaneously when new versions are published on PyPI then I think I'm in.

In the meantime, https://pretextbook.github.io/pretext-cli/ has the current work-in-progress CLI documentation (published using the new [minimal] `pretext publish` workflow I implemented yesterday). If we get the synchronous documentation build figured out, then I'll have that URL forward to the appropriate section of the PreTeXt Guide instead.
