### ISSUE TITLE
Assemblage in default/init book

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#313]
An "assemblage" is very popular as a way to get a "blue box" and a black border.  It is unusual within PreTeXt in that it is not numbered (and has more styling than most parts).  So I'm not a fan.

Seems a CLI new-book creation includes an "assemblage" in  `sec_first-examples.ptx`.  Do you think we could not promote this construction so prominently by not making it available so readily?

Rob

**Comment by StevenClontz** [comment]
Mocked up at https://github.com/PreTeXtBook/pretext-cli/pull/314. @oscarlevin you wrote this so merge if you agree

**Comment by oscarlevin** [comment]
I suppose I'm okay removing assemblage, but a summary of important theorems really should not be in a `<remark>`.  We definitely should not be promoting non-semantic markup.  Maybe for now we just remove that completely (or highlight remark-like with different text).

And while I'm here, I would like to once again make a plea for the ability to turn off numbering on a per-element basis (so theorems and definitions are not numbered, but lemmas and corollaries are, for example).  The ability to present unnumbered boxes is a useful and common feature of lower level math books.  If this ability existed, then expanding assemblage into "collection-like" (with `<collection>`, `<summary>` and `<assemblage>` at least) and having it numbered by default would be a fantastic feature.  Obviously the numbering is super complicated and controversial.

**Comment by oscarlevin** [comment]
Merged slightly modified version.

**Comment by rbeezer** [comment]
**Thank-you!**
