### ISSUE TITLE
On what errors should the CLI exit?

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#315]
Our current `generate` behavior is to exit completely whenever an error in generating any assets is encountered.  @Alex-Jordan points out that this is not helpful for WeBWorK, since the core script already puts a placeholder in a broken webwork problem, which would make it easier for the author to identify where the issue is.  

I think a similar argument can be made for other assets: it is helpful to see how far the process got, to diagnose whether there is an issue with the computer setup and no images can be produced, or if the error is with the code of a particular asset.

So how about this new behavior:
- On all of our try/excepts that currently result in ending the build/generate, we instead collect the error message and have `log.warning("There was an error with the {task}")` and then just `pass`.  
- At the end of the run, we display all the collected error messages.
- We make the errors more informative, i.e., "In generating the WeBWorK asset, an error was encountered.  Look at cli.log for more info, and check your output for unexpected results."

Thoughts?

**Comment by StevenClontz** [comment]
I think it should be a `log.error` initially as well, but yeah, I like reporting each error as it happens, continuing, then reporting a log of all errors together at the end of the build (and exiting with an error).
