### ISSUE TITLE
Quick Reference for the CLI

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#320]
An "authoring" quick reference is going up on the website, and being announced on `pretext-announce`.  When syntax is relatively stable, perhaps a companion "PreTeXt CLI Quick Reference" would be very useful as authors are just getting started (and/or at workshops, etc.).  Perhaps a non-developer can be cajoled into writing such a thing?

**Comment by StevenClontz** [comment]
A WIP for this is here: https://github.com/PreTeXtBook/pretext-cli/tree/main/docs

It needs work, preferably after we nail down the upcoming 1.0 release.

**Comment by rbeezer** [comment]
Excellent!  Yes, no rush while things are in flux.

I converted Tom's to use `xelatex` (color package option) and a few other things, see recent commits if you are curious.  When the CLI version is ready to go, I can integrate into the website build, etc.

**Comment by oscarlevin** [comment]
This is waiting as a PR on pretext for the 1.0 release, so closing.
