### ISSUE TITLE
Get interactive preview generation working

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#324]
Right now interactive preview images are generated from a deployed version of the HTML build. Coordinating with core dev, we should be able to spin up a local server to grab screenshots with pyppeteer instead.

**Comment by StevenClontz** [comment]
See https://groups.google.com/g/pretext-dev/c/qiQv9VD4J_E

**Comment by oscarlevin** [comment]
This is fixed now and will be available on the next release.
