### ISSUE TITLE
Support programmatic creation of a project

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#327]
Right now a new `Project()` may only be instantiated by reading a `project.ptx` off the disk. This is a pain for me today, because (for reasons) I have a project that needs two separate targets for each section with custom XSL. So now I'm creating this `project.ptx` by hand, but I'd have preferred to programmatically instantiate a `p = Project(xml_object)`.

**Comment by oscarlevin** [comment]
This is the major feature of the 2.0 release.  @StevenClontz, you should write something for the guide about how use this feature.
