### ISSUE TITLE
click-log and stderr

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#336]
As mentioned in #334 , I have proposed switching to click-log instead of click-logging, to address #331 .  However, this introduces another strange thing, namely that all logs are sent to stderr instead of stdout for info and debug (and I think stderr for warnings, errors, and criticals).  If we are okay with this, then we should go ahead, but if not, then I think it means abandoning both click-log and click-logging.  I like the idea of getting rid of a poorly maintained dependency, but it would require a little work.

This would require creating our own formatter (I like the colors and lowercase levelnames, but I think I could replicate what they have easily).  More complicated would be to implement the simple verbosity option that we have now (the `-v debug` behavior).  However, this is an opportunity to maybe do something better.  We could follow the core pretext method of `-v` for info messages, `-vv` for debug and nothing for only warnings and above.  Or keep nothing for info and above, `-q` for errors and above, and `-v` for debug.  We can probably also set this up so putting those flags anywhere works, not just after `pretext`.  

Since this is a feature breaking change, I thought I would through it out before we ship 1.0.  What do you think @StevenClontz?

**Comment by StevenClontz** [comment]
`-v` and `-vv` are non-semantic commands, I much prefer `-v DEBUG|INFO|...` and especially like the default set to info as we do currently.

I'm not excited about rolling our own logging.

Looking at https://github.com/click-contrib/click-log/blob/master/click_log/core.py#L33 I think we could roll our own ClickHandler and override the logger's handlers after a basic_config.

**Comment by StevenClontz** [comment]
Here's some context for the stderr btw: https://github.com/click-contrib/click-log/issues/15

**Comment by oscarlevin** [comment]
Yeah, I saw that issue, and that last comment is what makes me suspicious.  I will spend another day thinking about how to override the basic_config.  I know how to make our own handler, but that would give double messages I think.  click-log overrides the default emit() function of logging to use click.echo and passes the stderr thing.  In any event, I think this is fine for now (shouldn't delay 1.0), since we are not changing the interface.
