### ISSUE TITLE
`webbrowser.open` requires string argument on Linux

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#341]
As reported in pretext-support, there is an issue with running `pretext view` on non html targets in Linux.  Should be a quick fix, once I get a test environment set up to try this on my wsl install.

**Comment by StevenClontz** [comment]
Dropping this note somewhere relevant: today `webbrowser.open` was honored by CoCalc's VS Code instance, so `pretext view` opened the link in my browser automatically. 🤩
