### ISSUE TITLE
error message with invalid target

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext-cli#345]
Suppose you type `pretext build web` when the project file has `<target name="html">`.

The build fails and the resulting error message is cryptic.

It would be better if the CLI noticed that you asked for an unsupported target,
provided an easy to understand error message, and gave you a list of possible targets.

I am using 1.0.2

**Comment by oscarlevin** [comment]
Thanks for the heads up.  We had something like this working not so long ago, with exactly what you are asking for.  I'll investigate later today and push a fix.
