### ISSUE TITLE
Generate QR codes for interactive content

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#353]
There is a new generation routine in core.  It makes QR codes for interactive content, meant for use in static formats.

https://github.com/PreTeXtBook/pretext/commit/ebd94b8ed16f32563c085f189c495bc6bc54324d

At this moment, QR codes only appear in the LaTeX conversion, but plan is to use pre-processor to make a static version of interative content as legal PreTeXt, hence these images.  Building these with Python is *way* faster than the LaTeX package.

*  CLI will need to pip-install  `qrcode[pil]`, https://pypi.org/project/qrcode/
*  New routine is `qrcode()`, modeled after `youtube_thumbnail()`, including identical signature.
*  New supporting stylesheet, `xsl/extract-qrcode.xsl`.
*  New `qrcode` directory as home for results.
*  Could be integrated now into the CLI.  Images/Codes are not being used yet, and some are broken due to LaTeX-specific ampersands in some URLs.

I might do a refactor to adjust the LaTeX conversion first, as a test.  Even if it then gets ripped out later when generalized.

**Comment by rbeezer** [comment]
> Could be integrated now into the CLI. 

If this is done, I haven't heard about it.  ;-)  Could become necessary before the next CLI release.  And in any event, it'd be good to have some testing when they are not even being used.  Trying to release `interactive` from purgatory.

**Comment by oscarlevin** [comment]
That's true, no work on this in the CLI yet.  But should be straight forward.  Let's do this Friday.

**Comment by rbeezer** [comment]
> Let's do this Friday.

Perfect.  Along with logos and buttons.  ;-)  Thanks.

**Comment by oscarlevin** [comment]
All set and will be in the nightly build tomorrow.  No change for users, except they will have qrcode images in the `qrcode` folder of the `generated-assets` folder if they have any youtube videos or interactive elements when the generate.
