### ISSUE TITLE
`pretext view --watch` memory leak?

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#356]
I'm editing a single-section subset of https://github.com/TeamBasedInquiryLearning/calculus and cannot seem to use `--watch` without a crash due to limited memory on my CoCalc machine. I only have 1000 MB of RAM on this VM, but that's the basic amount you get with a paid CoCalc license, so maybe we should still be trying to be usable in this scenario.

**Comment by bnmnetp** [comment]
It could just be Python being python.   Even though it does garbage collection to free up memory it does not necessarily give it back to the operating system.  This is true especially with smaller amounts of memory.  For my web serving processes they are configured to restart themselves after every 1000 requests, this keeps the memory usage very manageable.

Not sure how you have watch set up but we could probably figure out some kind of stratgey.

**Comment by oscarlevin** [comment]
`--watch` has been removed as an option for 2.0, since codechat accomplishes the same thing.
