### ISSUE TITLE
inspect working directory for `pretext new` behavior

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#357]
In the near future I expect to see a workflow where a CoCalc user creates a new (empty) directory, then opens that directory in VS Code, then creates a new PreTeXt project. This will (unless the `-d` option is used) create a subdirectory of the new directory.

I think the default behavior of `pretext new` (without the `-d` option) should be:

- If there are any visible files in the directory, attempt to create the project in a `new-pretext-project` sudirectory of the working directory.
- Otherwise, attempt to create the project in the working directory.

**Comment by siefkenj** [comment]
Would it be bad to prompt the user "Do you want to use the current directory for pretext source (instead of creating a sub-directory)?" when there are no files detected in the current directory?

**Comment by StevenClontz** [comment]
I think the opinionated user should be using the `-d` flag. I'm not everyone (I'm certainly running `pretext new` way more than anyone else should be besides Oscar), but I cannot think of a situation where I want my new project in a subdirectory if my working directory is clean, or where I want a project mixed in with files that already exist in my working directory.

**Comment by siefkenj** [comment]
Okay. Here's a different idea: what if there were a `pretext undo`. The annoying part of putting the files in the wrong place is cleaning up. If a warning was printed that says it's creating in the current directory, it could suggest `pretext undo` if that wasn't what the user wanted. (maybe `pretext cleanup` would be better?)

**Comment by StevenClontz** [comment]
Aren't the defaults one-liners? If the project created a directory, `rm -rf new-pretext-project`. If it used the current directory, `rm -rf *` (since the directory was clean).

Actually is there any strong reason to allow a new project in a non-clean directory? Because `pretext new -d .` in `Documents` is never a good idea. So we can

1. make the default directory the working directory
2. no matter what directory was given, if it already exists and has non-hidden files besides, we build in a subdirectory `new-pretext-project` instead.

Argument to the above: I've definitely provisioned a Git repo with a default `README.md` then run `pretext new -d .` there. So maybe a `-f` flag to force not creating a subdirectory would be good as well.

**Comment by oscarlevin** [comment]
Since the prefered workflow now uses codespaces which comes with the project already initialized, I don't think we need to worry about this any more.
