### ISSUE TITLE
Coordinate native search moving to opt-out

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#358]
Announcing native search right now.  I'd like to convert from opt-in to opt-out in a month or two.  Probably not in the next stable release, but perhaps the one after?  Can you give me a few days warning?  Should just be a simple edit on my end.  Perhaps I'll even put it onto a branch now...

**Comment by oscarlevin** [comment]
We generally release a stable version at the end of each month.  But of course, we can do one at any time.  We had talked about doing a minor release when search was announced.  Unless @StevenClontz objects, I'll go ahead and do this as soon as I can

**Comment by rbeezer** [comment]
Thanks!  I'll get this in towards the end of November, so you don't have to think about it.

**Comment by StevenClontz** [comment]
since it's still opt-in, let's put out a patch release so folks can start using it now if they want, and let's make it a minor release when it's opt-out

Oscar, you have your head around the current release workflow better than I do at the moment; do you mind cutting the release?

**Comment by oscarlevin** [comment]
Will do.
