### ISSUE TITLE
restricting WW processing to a subset

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext-cli#359]
This is maybe not an "issue" but I'm unsure the right way to bring this up.

Following:
https://github.com/PreTeXtBook/pretext/pull/1850

`pretext/pretext/pretext` can now take the subtree `-r` argument when doing `-c webwork`. That is, when building WW representations. 

- Does anything special need to be done for the CLI following this? Or (once the CLI has its next update) will it simply work to do things like `pretext generate webwork -t target` where the target uses a subtree?
- What is the timeline for the next update that would have that commit from the above PR? If there's any pretty-pleasing I can do to make it in the CLI by late November, let me know. I'll be training colleagues on December 2 for ORCCA revisions, and if I can have this official at that time, it will help me a lot.

**Comment by StevenClontz** [comment]
https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/project.py#L277

Looks like we need to start passing through the xmlid here. In fact our nightly builds will now start to be broken for all webwork builds due to the non-backwards compatible change you made at `pretext.py#L889`, adding an argument to the middle of existing arguments:

https://github.com/PreTeXtBook/pretext/commit/5ab1a1aba6e4b6304ff6abf7af0e218c32484525#diff-314fe2c53fd9bf7fa916f2baea3aec2d3eb1a8fbb50e6cdd0162ce42fdb7d4f1R889

**Comment by Alex-Jordan** [comment]
Oops. That was for consistency with other functions. Probably all parameters in these functions should get names...

**Comment by StevenClontz** [comment]
My general gripe with `pretext.py` design philosophy is a lack of keyword arguments (so order-agnostic) with default values - there are so many `None`s being passed around anyway, and it makes things tedious to use and update!

**Comment by rbeezer** [comment]
In this project, there is no room for griping about one another's contributions, just room for improvement.

Please make an issue and consider formulating a pull request.

**Comment by StevenClontz** [comment]
Apologies for my bluntness! It's a non-trivial task and only faces developers (and theoretically, anyone importing it as a library rather than using the CLI or your command-line script), not end-users. So I'll make the issue, but cannot prioritize it. Maybe this spring.

**Comment by StevenClontz** [comment]
Here's the failure I predicted: https://github.com/PreTeXtBook/pretext-cli/actions/runs/3383462486/jobs/5619382162#step:7:78

**Comment by rbeezer** [comment]
> So I'll make the issue, but cannot prioritize it.

Thanks.  Likely not so hard to do, but will require **lots** of testing.

**Comment by StevenClontz** [comment]
Also I'm a big fat hypocrite - as I work on fixing this, I'm noticing similar issues with CLI code. (Interestingly, at some point I had the mindfulness to call core functions using keyword arguments anyway - this *does* protect against moving the positional arguments around, but does not offer a solution for when a new positional argument is introduced.) https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/generate.py#L219

So we all, including myself, could think more carefully about making sure we're committing code that won't break other folks' work downstream. 😅

**Comment by oscarlevin** [comment]
It seems like our nightly build system is working though, since we didn't publish a nightly that was broken.

@StevenClontz , will you get this repaired today or would you like me to fix it?  I have time this afternoon so we can get back on the nightly schedule tonight.

**Comment by StevenClontz** [comment]
I've got a PR cooking. #360

**Comment by StevenClontz** [comment]
> It seems like our nightly build system is working though, since we didn't publish a nightly that was broken.

🎊 🥳

**Comment by rbeezer** [comment]
> about making sure we're committing code that won't break other folks' work downstream

For the record, I knew what I was doing.  :-(   Which is why I suggested Alex ping y'all.  I was working under a deadline over the weekend.  Never a good situation.  ;-)

Glad to hear the nightly system is bomb-proof.  ;-)

**Comment by StevenClontz** [comment]
#360 is merged, closing this. `pretext generate webwork -x foo` will generate webwork under the xml:id `foo`.
