### ISSUE TITLE
Publication file conflict

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#362]
A publication file can be specified all by itself through a dedicated mechanism, or more generally via the string parameter `publisher`.

Who wins when both are employed?  To encourage publication files, I say the dedicated mechanism.  Which is what I have firmed up just now in the `pretext/pretext` script.

https://github.com/PreTeXtBook/pretext/commit/f48855730ff76d980a17afa915dded145bd9d4fa

So this is just a heads-up, should we want to be consistent.  Maybe we already are.  I've not examined the CLI code to see.

**Comment by oscarlevin** [comment]
We simply pass the stringparams to the build scripts in core, and always pass a publication file (this must be set in a target), so we always use the dedicated mechanism.  

I've added a warning to any build that even specifies a `publisher` stringparam, since this never gets used.
