### ISSUE TITLE
project.ptx Schema?

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext-cli#368]
Is there a schema file for `project.ptx`? Or is there some way to programmatically generate all valid options?

**Comment by StevenClontz** [comment]
Nope, though I think at this point the conventions are stable enough that we *should* encode what's allowed.

**Comment by oscarlevin** [comment]
Now that we validate the manifest using pydantic, does it still help to have a schema for it?  I suppose we could set up pretext-tools to complain when something isn't right based on the schema, which would tell users that there is an issue sooner.  

Does pydantic have a way to generate a schema from its document model?

**Comment by bjones1** [comment]
Having a schema would be nice from an VSCode IDE perspective, where the user could be guided into the correct syntax while editing. However, I don't know any way of auto-generating the schema from pydantic / pydantic-xml; the constraints they support is probably a much richer language than XML's schema.
