### ISSUE TITLE
Add warnings based on source elements

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#38]
When a PreTeXt document contains elements that need additional processing (images #8 , webwork #9 , etc) that should not be processed every time, we should output a warning that these things have not been reprocessed, with instructions of how to do that. 

We can walk the xml tree to look for these elements using lxml.

**Comment by StevenClontz** [comment]
Somewhat related: we should elaborate on ``--diagrams`` help so users know what PreTeXt elements it is needed for.

**Comment by StevenClontz** [comment]
Naively, all I think we need are a few e.g. 

```
if doc.xpath('//latex-image')
    click.echo('foo')
```

**Comment by StevenClontz** [comment]
> Somewhat related: we should elaborate on `--diagrams` help so users know what PreTeXt elements it is needed for.

I think this was addressed in 292f47f2398dcd1e4e1b13348bed719fda14de36

**Comment by oscarlevin** [comment]
Yes, the help has been improved.   It would still be nice to have specific warnings.  I'll try the doc.xpath thing next.

**Comment by StevenClontz** [comment]
I've implemented this for `latex-image`. But we need to think more carefully here: right now we're passing along a string with the source filename/path to a few functions, which are each separately parsing the source. It seems it would be more efficient for `pretext build` to grab the source, immediately serialize it to an lxml object, and then pass that around the library.

**Comment by oscarlevin** [comment]
I agree we should think about when the right time to parse is.  Note that calls to the pretext/pretext script ask for the xml file, which gets parsed separately anyway.   Not sure about how much of an efficiency concern this is in the end though.  If it really did slow things down, then maybe refactoring the pretext/pretext script would also be warranted.

More to the point of this issue, it would be helpful to have a single utility that checks and reports for a large variety of elements.  The pretext/pretext script has some of this in the all_images  function.

**Comment by StevenClontz** [comment]
Closed by d29c2d4f8c7c6b934850cd6f7c10f869867b2479
