### ISSUE TITLE
Consider temporarily disabling automatic opening of `pretext view`

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#389]
On Codespaces, I'm frequently getting failed previews popping up, seemingly due to the proxying of localhost to the github.dev subdomain. I don't think this is an issue when actually clicking on the link.

I also find myself using a lot of `--no-launch` in practice anyway when re-building since I already have my browser open (and to the page I care about).

**Comment by oscarlevin** [comment]
My workflow has become to open a view (perhaps now I will use the live-preview instead of `pretext view`, and then run `pretext build`, instead of `pretext view -b`.  The idea is that you ask to view once, and build to refresh.

**Comment by oscarlevin** [comment]
This has been done
