### ISSUE TITLE
Move repository to PreTeXtBook org

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#39]
It's easier to do now than later, so we should consider moving this repo to the PreTeXtBook organization, assuming @oscarlevin and I can remain as lead maintainers.

The name of this repo is ambiguous with the `pretext` module being maintained in `mathbook`, so perhaps `pretextbook-pypi` would be better once we make this move.

In the meantime, https://pypi.org/project/pretextbook/ is the public-facing homepage for the project so we won't be disrupting things if we make a move. (I've purposely not used the StevenClontz/pretext.py URL much anticipating a move/rename.)

@davidfarmer @rbeezer thoughts?

**Comment by davidfarmer** [comment]
Okay with me.

Either you automatically get the permissions you want when it is moved,
or I will grant them after the move.  Just let me know what to do.

**Comment by StevenClontz** [comment]
I think I'll need to be added to the organization with repo creation permissions.

@oscarlevin thoughts about the name? I'd like to make that change simultaneously (as possible).

**Comment by oscarlevin** [comment]
@StevenClontz,  I think that `pretext-cli` seems like a good name for the repository.  `pretextbook-pypi` doesn't strike me as saying what this is, and it is not clear whether the pretext/pretext (core) modules might end up in pypi eventually.  Alternatively, looking at the repositories in pretextbook already, maybe just `CLI` should be the repository name (at `github.com/pretextbook/cli`).

**Comment by davidfarmer** [comment]
I'll make the repository and then put the two of you as owners,
and see if that works.

**Comment by rbeezer** [comment]
Yes, a move would be great.

Names:  I'd be very happy for **this** CLI to have the best name.  So if you want to call it `pretext` that is fine by me.  I'd be happy to call the other one (the former `mbx`) something else.  Ideas welcome.  `pretext-dev` to conote its purpose/use?

Share any gotchas on the move.  Next big renaming job will be the `mathbook` repo itself.

**Comment by StevenClontz** [comment]
@rbeezer We could keep this as `pretext.py`. I think I like something like `pretext.core.py` for what's currently tracked in rbeezer/mathbook -- those scripts are used by authors as well, albeit indirectly if the CLI becomes the recommended interface. If it is published to PyPI eventually, I think `pretextbook.core` is the right naming according to https://www.python.org/dev/peps/pep-0423/#top-level-namespace-relates-to-code-ownership I also like `github.com/PreTeXtBook/core` as a repo name for the current `rbeezer/mathbook`.

@oscarlevin I do like the nice short url `github.com/PreTeXtBook/CLI`. I am torn between including `pretext` in the name or not; it's redundant with `pretextbook`, but it's less ambiguous after a `git clone` if you include it. (Then again, we're trying to prevent needing to `git clone` unless you're a developer anyway.)

@davidfarmer To transfer the existing issues in this repo I believe I'll need (at least temporarily) permission to create repos myself in PreTeXtBook: https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by davidfarmer** [comment]
I added SC and OL to the organization with the ability to
create a repository.

I renamed the existing CLI repository to DeleteMe, because I did not
immediately find how to delete it.

**Comment by StevenClontz** [comment]
Okay, I'll need to wait until @oscarlevin has accepted, so we won't lose his assignments: https://help.github.com/en/github/administering-a-repository/transferring-a-repository#whats-transferred-with-a-repository

In fact, it seems we can only make this move as long as everyone's okay with Oscar and I remain members of the PreTeXtBook organization (not just the repo?) after the move:

> When you transfer a repository from a user account to an organization, issues assigned to members in the organization remain intact, and all other issue assignees are cleared. Only owners in the organization are allowed to create new issue assignments

**Comment by oscarlevin** [comment]
I have accepted.

**Comment by davidfarmer** [comment]
>       When you transfer a repository from a user account to an organization, issues assigned to members in the
>       organization remain intact, and all other issue assignees are cleared. Only owners in the organization are
>       allowed to create new issue assignments

That doesn't sound right, because assigning issues happens at the 
repository level.  Maybe I am thinking of something else.

But, no big deal either way, as long as we don't lose information.

**Comment by oscarlevin** [comment]
@davidfarmer: I deleted DeleteMe for you :)

**Comment by StevenClontz** [comment]
Okay we're now at PreTeXtBook/pretext.py -- last thing is to make the appropriate name change.

Looking around, there's one `pretext-projects` repo, and others don't include `pretext`. I think either `pretext-cli` or `CLI` are the way to go. I'm going to go with `pretext-cli` so `git clone` produces a semantic subdirectory by default. Feel free to chime in if anyone feels differently; otherwise I'll close this tomorrow.

**Comment by StevenClontz** [comment]
Looks like I don't have sufficient permissions to access the Settings of this project after the move: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization So @davidfarmer or another admin will need to update the name of this repo.

Note that right now StevenClontz/pretext.py mirrors this repo. I don't think there's "forwarding" after a repo name change. So there's some incentive to not change the repo name if we're happy enough with pretext.py. I'm okay with keeping `pretext.py`, or changing to `pretext-cli` or `cli`.

**Comment by StevenClontz** [comment]
Ah -- I can make the change myself once @oscarlevin and I are made Admins for this specific repo. We don't need to be owners for the organization, if I understand correctly. (This is why Oscar was able to delete DELETEME, since we were admins of that project I believe.)

**Comment by davidfarmer** [comment]
I think I made the two of you admins on the repository.
(Why that is not automatic when you create it, I don't know.)

**Comment by StevenClontz** [comment]
Renamed to PreTeXtBook/pretext-cli as per "The Zoom Where It Happened".

**Comment by rbeezer** [comment]
> "The Zoom Where It Happened"

I'm glad we got that recorded!
