### ISSUE TITLE
speed up testing

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#392]
We currently test on six configurations: ubuntu and windows with python 3.8, 3.9, and 3.10.  I guess, soon, 3.11?  Anyway, the windows tests take a long time and sometimes fail (but not because anything is broken; it seems to be an issue with requesting something from a server).  

Maybe we test different python on ubuntu, and just one on windows?

**Comment by StevenClontz** [comment]
That sounds fine to me, though a more robust workflow that checks all Windows versions before a stable release might be appropriate.

**Comment by oscarlevin** [comment]
I've added python 3.11 to the testing workflow, and removed the number of tests for the nightly and test-on-push steps.  All of the stable builds now require 8 tests (2 OS times 4 python versions).
