### ISSUE TITLE
Copy images correctly

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#4]
In addition to images in source, pretext allows pre-built, static images.  A natural place to hold these is in `source/images`.  As of 2503fef, this directory (if it exists) is copied to the correct place in `output`.  But an author is able to specify any path to static images, and right now, there is no support for that in pretext-cli.

One way to make this work might be to read the source using lxml and go find any images that are mentioned and copy them to the correct place relative to `output`.  No idea how complicated this would be.

Another thing to keep in mind: there are other ways images can make their way into a book, including images generated by WeBWorK.  I am not quite sure where these should go, but Alex says they get generated in the same place as the WeBWorK extraction file.  Eventually these need to be copied to `output` or some subdirectory of it.

**Comment by StevenClontz** [comment]
I'm okay with the CLI being opinionated about where images must exist (e.g. an `images` subdirectory of the defined source path), unless there's a strong reason that a user might *need* to pull images from elsewhere. Certainly it's not a high priority for me as I think the CLI should focus on getting new authors up and writing quickly; existing authors can either adjust to the CLI's structure, continue using xsltproc, or contribute to the CLI's code to add options that fit their workflow.

**Comment by oscarlevin** [comment]
We will wait for PreTeXt to manage image locations in the publisher file before finishing this so we don't have to repeat work.

**Comment by StevenClontz** [comment]
closed as a subset of #96
