### ISSUE TITLE
fix dependency insights

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#408]
As noted in #405 somehow only the legacy pretextbook dummy setup.py was picking up dependencies from other repos. We want to address this.

**Comment by StevenClontz** [comment]
#409 failed to fix this :(

**Comment by oscarlevin** [comment]
I know why!  The other pretext is getting priority somehow.  When I look at my dependencies for a pretext project, it points to the 0.5 release of "pretext" (https://github.com/moreati/b-prefix-all-the-doctests)

**Comment by oscarlevin** [comment]
Which is puzzling, since it definitely was working earlier; I saw a repository on the dependents list that was only created a few weeks ago (well after we changed the setup.py file).

**Comment by StevenClontz** [comment]
Played around with this a bit tonight to no success.

Opened https://stackoverflow.com/questions/75851255/ to see if the mob can help.

**Comment by StevenClontz** [comment]
Ultimately this was a GitHub bug and had to be fixed by opening a support ticket. 🙃 Fixed now.
