### ISSUE TITLE
/tmp directories not cleaned up after successful build

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext-cli#414]
It would be nice if the temp folders were removed after a successful build.

I cleaned up 38GB of temp folders on my staging machine after it ran out of disk space during the Saturday updates.  The culprit took me a while to find but there were hundreds of tmp folders from pretext builds.

**Comment by StevenClontz** [comment]
I believe this is the only culprit (unless it's happening on the [P](https://github.com/PreTeXtBook/pretext) side).

https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/project.py#L240

We have a context manager that usually handles cleanup - we can just use it on every build rather than just with custom XSL.

**Comment by StevenClontz** [comment]
Oh, well now I remember why we did that.

https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/project.py#L344

Can you tell me more about the tempdirectories you cleaned up? Because now I'm unsure we caused them on our side.

**Comment by rbeezer** [comment]
The core routines clean-up after themselves, **unless** verbose (`-vv`) logging is requested.  Is the CLI writing these messages into a file?  Always?

There is a module-level variable which accumulates the temp directories.  They could be released.  I'm guessing there is likely a routine for that?

**Comment by bnmnetp** [comment]
I cleaned them all out on saturday, but when I checked this morning there is one directory like /tmp/tmp0x7680gs for each of the PreTeXt books on runestone academy.

These appear to contain the output of the build (not the source) for each book.

```
ls /tmp/tmpyg6yimow/
 _static                    colophon-2.html           sec_count-conc.html          sec_planar.html
 external                   dedication-1.html         sec_counting-addmult.html    sec_polyfit.html
 generated                  dmoi.html                 sec_counting-binom.html      sec_propositional.html
 knowl                      frontmatter.html          sec_counting-combperm.html   sec_recurrence.html
 acknowledgement-1.html     index-1.html              sec_gt-conc.html             sec_seq-arithgeom.html
```

**Comment by StevenClontz** [comment]
Took a mostly random stab at https://github.com/PreTeXtBook/pretext-cli/pull/415 - we'll see if tests pass (-:

**Comment by oscarlevin** [comment]
Somehow forgot to finish merging this.  It is now part of the latest release, 1.5
