### ISSUE TITLE
Output logs when using CLI as module

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext-cli#418]
I'm working on the author server and trying to make the error reporting more reliable and robust (You're welcome Oscar)

One of the easiest and likely best ways for me to do that is to avoid using the subprocess module to run pretext.  It is already running in a subprocess and adding the additional layer means I have to do a lot of extra work to figure out where and when things might go wrong.

If I could `import pretext` and call `pretext.build(with some args)` that would be great.   I have some vague idea that this is a goal or maybe there is a way to do this and your are doing it for the VSCode support?

If this is already possible point me to an example or some code!  If not how hard do you think it would be to make this possible?  It might be as easy as some refactoring where the current `build` function becomes a new undecorated function that is called by the click-decorated function....

**Comment by StevenClontz** [comment]
This is already possible but isn't well documented. I'm on mobile now but will try to find an example when I can.

**Comment by bnmnetp** [comment]
OK, good to know that sometimes my vague recollections are actually reality. 😄

**Comment by StevenClontz** [comment]
See example at https://github.com/StevenClontz/pretext-module-example-20230215/blob/main/build.py Note that there's no good way to instantiate a `Project()` without providing a path to a `project.ptx`. There's also lower-level build functions in `pretext.build` that more lightly wrap the core PreTeXt module (not to mention the core PreTeXt module itself at `pretext.core`).

The major known issue is that we're not printing out the logged statements when importing PreTeXt, though it does build. Assigning to Oscar as he's more familiar with the logging module.

**Comment by bnmnetp** [comment]
Thanks

**Comment by oscarlevin** [comment]
The log issue should be fixed with #472.
