### ISSUE TITLE
custom format doesn't support webwork problemset generation

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#419]
> Works, but if I have format set to "custom", I get an error complaining that the publication file doesn't know what the webwork representations file is.
>
> So I left the format as "html" even though this is incorrect and it worked.
> Also, I had to put a symlink to pretext/xsl/pretext-ww-problem-sets.xsl in my project folder, because the <xsl> tag takes that folder as root.

**Comment by sean-fitzpatrick** [comment]
I set the following:

```
<target name="wwsets">
  <format>custom</format>
  <source>ptx/3410notes.ptx</source>
  <publication>publication/publication.ptx</publication>
  <output-dir>output/webwork</output-dir>
  <xsl>pretext-ww-problem-sets.xsl</xsl>
</target>
```
Running `pretext build wwsets` gives me a long list of errors of the form:
> PTX:ERROR: There is a WeBWorK exercise with internal id "webwork-59" but your publication file does not include the file of problem representations created by a WeBWorK server

If I change the format to `html`, I'm able to generate the problem sets.

The publication file for html doesn't indicate where the webwork-representations file lives.

**Comment by oscarlevin** [comment]
Closing, since 2.0 supports the `webwork` build target for webwork sets.
