### ISSUE TITLE
More aggressive `pretext init --refresh`

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#437]
With the improved Git tooling provided by VS Code, I wonder if we cannot be more aggressive with `pretext init --refresh`. My suggested workflow: every time you upgrade your CLI version, you should run a refresh so your Codespaces setup is more appropriate for potential contributors. I think folks will comply with this more readily if you don't have to manually decide whether you need to update stuff in `.devcontainer`.

Downside: a lot of folks will customize `project.ptx` which will get clobbered during a forced refresh. But if we educate authors on using the changed files tool in VS Code, and to revert the changes to `project.ptx` before committing this refresh (which is pretty easy to do in the VS Code UI) I think we'll have a good balance.

Thoughts @oscarlevin?

**Comment by oscarlevin** [comment]
Is there a reason we want to update `project.ptx` at all?  Perhaps just a `pretext update` command that installs the most recent version of the CLI, updates `requirements.txt`, updates `.devcontainer` and... that's it?  

Or maybe the `.devcontainer` can be managed exclusively through pretext-tools, which already has an "update" command
