### ISSUE TITLE
Devcontainer: persistant static file server for projects

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#438]
In https://github.com/pi-base/web/blob/main/.devcontainer/devcontainer.json#L7 we use `postAttachCommand` to spin up a preview server for one of the apps (`"viewer": "pnpm run --filter viewer dev --host").

I suggest we do something for our users: whenever you spin up our recommended codespace, you immediately get a static file server for the whole repository. Then when you want to `pretext view` we just need to point the Live Preview or new tab to the right URL: we don't have to manage spinning up or down a server because we're just always running one.

**Comment by oscarlevin** [comment]
Not exactly this, but an equivalent is in the 2.0 release.
