### ISSUE TITLE
pretext view --rebuild-html

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#46]
If the user supplies the `--rebuild-html` flag when viewing, then the HTML (without diagrams) should be automatically rebuilt whenever a source file is edited.

**Comment by oscarlevin** [comment]
Would it be possible to (perhaps optionally) have `pretext view` start the server silently?  Then we would have the terminal available to rebuild (which would update what is served).  Later `pretext view --end` would stop the server.

(I'm having lots of trouble using the view to make changes.  Every time I want to test something, I need to `pretext view` and then stop the server before I can build again.  But for some reason on Windows the [ctrl]+[c] only works some times, so this is frustratingly slow.)

**Comment by StevenClontz** [comment]
Having a background process handle the local webserver isn't a pattern I've seen in other web apps or static site generators, which makes me wonder if there's a reason no one else does it. I bet many users will forget to `--end`, and we'll get complaints of `port already in use` because there's a process hanging out somewhere (maybe another PTX project).

But I agree that right now I'm doing a lot of `pretext build; pretext view`, then Ctrl-C, then [up]+[Enter] to rebuild/view. Sometimes I use tmux to have two consoles if I'm digging in for a longer authoring session. Is there a sane way to spin up two consoles in Windows, one to view and one to build?

**Comment by oscarlevin** [comment]
A second console is very easy using the Windows Terminal, I just have been lazy in starting to pipenv shells.  I agree the background running is a little squishy.  Some sort of --watch (for small projects) makes more sense.

**Comment by StevenClontz** [comment]
I still think this is a good idea, but it's quicker to at least implement a `--build` flag so `pretext view --build` aliases `pretext build && pretext view`.

**Comment by oscarlevin** [comment]
@StevenClontz implemented this on 6/30/21 with the -w watch flag.
