### ISSUE TITLE
Remove mypy checking? Or avoid this pattern...

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#469]
So I started writing this pattern:

```python
import typing as t
from pathlib import Path

class Foo:

    def __init__(self, p:t.Optional[Path|str] = None) -> None:
        self.path = p

    @property
    def foo(self) -> Path:
        return self._path

    @foo.setter
    def foo(self, p:t.Optional[Path|str]) -> None:
        if p is None:
            self._path = Path("default", "path")
        else:
            self._path = Path(p)


f = Foo()
f.path # Path("default", "path")
g = Foo(Path("another"))
g.path # Path("another")
h = Foo("and/another")
h.path # Path("and", "another")
```

This is type safe, valid Python, that allows for flexibility in assignment (you can use a Path or a string, or pass None to get a default) but precision in output (a Path).

Sadly, there's a six-year-old issue that recognizes that a bug in mypy incorrectly marks the non-Path assignment as a type error: https://github.com/python/mypy/issues/3004

So either I need to stop using this pattern (which I kinda like - we do a lot of `element.get("attr"):t.Optional[str]` that's nice to assign to a property we want to be a path without doing the conversion manually) or we need to not require MyPy enforcement.

**Comment by bjones1** [comment]
I'm confused -- when I run mypy on this, it doesn't complain. I'm using mypy v1.4.1. What version are you using?

(I added `from pathlib import Path` to the code, since that was missing.)

**Comment by StevenClontz** [comment]
I'm using whatever the vs code plugin uses. Let me check the actual MVP I posted to see if it triggers the issue.

**Comment by StevenClontz** [comment]
Closing as I believe this is moot with the switch to `pydantic_xml`
