### ISSUE TITLE
Add support for custom domains

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext-cli#476]
I have published the Runestone Academy Instructors Guide at https://guide.runestone.academy. I have set up a CNAME record and validated guide.runestone.academy.   

However when I run `pretext deploy`  The site becomes unavailable and the github pages settings page for the RunestoneInstructor/InstructorGuide repo loses its custom site and https settings.

possible gotchas:

* RunestoneInteractive is a github organization.  So not just a personal repo
* although I have never published this guide on github before, Github initially wanted to publish it at runestoneinteractive.org/ and then blog.runestone.academy.  But that does not seem to be the case anymore after some settings changes.

Once I manually re-add guide.runestone.academy as a custom domain it all works again, but that is definitely a PITA.  Any thoughts or workarounds?

**Comment by StevenClontz** [comment]
Can you share the repo?

**Comment by bnmnetp** [comment]
https://github.com/RunestoneInteractive/InstructorGuide

**Comment by StevenClontz** [comment]
I see that the CNAME file required for a custom domain (created as a commit when you set the custom domain in gh-pages) was deleted here: https://github.com/RunestoneInteractive/InstructorGuide/commit/d467fcc7d755a5b66eed07157ca2549a970cb3c1#diff-76b26edb75578663ca0fd6515ec7880ca04046bdbab298938981c9f0bd3907ddL1 So we need to figure out how/why.

**Comment by bnmnetp** [comment]
I suspect a force push ??

**Comment by StevenClontz** [comment]
A solution for now: create the CNAME file you need in the appropriate output directory, then force add it to your repository (despite other files in output not being tracked). Then make sure it's not deleted in future commits.

But we should create the CNAME for you as a future CLI feature.

**Comment by bnmnetp** [comment]
Yeah, it seems that something is deleting the CNAME file every time I run `pretext deploy`

**Comment by bnmnetp** [comment]
or, if not deleting changing the CNAME file to be empty.

**Comment by StevenClontz** [comment]
> or, if not deleting changing the CNAME file to be empty.

Yep, but that may be more difficult as we'd have to handle the logic of pulling, merging, etc.

**Comment by bnmnetp** [comment]
force pushes are bad.

But even this last attempt where I had the CNAME file locally, it seemed to get erased.

**Comment by StevenClontz** [comment]
I don't recall the implementation exactly, but if it was a force push I don't think you would be able to see the commits that were force pushed over. I've been on mobile this evening so I'll check on a proper computer when I have the chance.

**Comment by StevenClontz** [comment]
Here's a pattern that's working for me at https://test20230712.clontz.org/frontmatter.html

https://github.com/StevenClontz/cli-custom-domain-test/commit/20aa7e5064bb2f01943bf5cf79c831f0af80969c

Give that a try and let me know how it goes.

**Comment by bnmnetp** [comment]
That setup seems to be working.

**Comment by StevenClontz** [comment]
Great! I'm working on CLI this morning so I'll keep this in mind and see if it makes sense to fold this feature into that work.

**Comment by oscarlevin** [comment]
Two things that make this more complicated: for most folks, they will never manually make a CNAME folder; apparently that is something github pages sometimes does for repositories when you set up a custom domain (although I don't think it has for me; I have custom domains without it).  Perhaps in those cases, we don't have to worry about this at all.

Once the project refactor is done, we can merge in the landing page feature which will automatically put the contents of `site` at the root of the github pages branch.  At that point, anyone who wants a CNAME (or any other file) can just track it as part of that folder.

**Comment by oscarlevin** [comment]
Closing this since with 2.0.0, you can put CNAME in your `site` directory to make it persist.
