### ISSUE TITLE
Add support for previewing deployment

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#480]
I'm trying out the `deploy-dir` stuff now.  I think it's set up correctly, but there's no way to check without actually trying it.

Ideally, I could preview the deployed site. I suggest in 2.0, we have `pretext stage` (working title) that stages everything in `staging`, and lets the author preview things in a web browser. Then `pretext deploy` takes the content of `staging` and puts it into the `gh-pages` branch.

**Comment by StevenClontz** [comment]
(On the bright space, the deployment was successful!)

**Comment by oscarlevin** [comment]
This is available in 2.0 now.
