### ISSUE TITLE
remove order requirements in pydantic-xml elements

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#482]
https://github.com/PreTeXtBook/pretext-cli/blob/4d783542d9a4e68a83e93c52fe9fb3f68cd41081/pretext/project/xml.py#L58

I had an issue where my executables had extra elements `pdfcrop` and `pageres` (which were deprecated a while back). So deleting them is fine.

But it revealed perhaps another, bigger issue: it couldn't find `node` and `liblouis` because they appeared *after* those deprecated executables. I don't think the order of these elements in `<executables/>` should matter, so can we fix this?

**Comment by StevenClontz** [comment]
Similar issue in `<targets/>`: it's saying elements aren't found, but it's just because they appear in a different order than expected.

**Comment by StevenClontz** [comment]
I imagine this is less an issue for non-legacy project files as we're switching to attributes.

**Comment by bjones1** [comment]
Sounds like we need the [unordered](https://pydantic-xml.readthedocs.io/en/latest/pages/data-binding/elements.html#unordered) search mode.

**Comment by bjones1** [comment]
While working on this, I had a question: for the legacy project `<executables>`, must they all be defined or should we assume defaults if, for example, the `<asy>` tag is missing?

**Comment by bjones1** [comment]
Should be fixed by #484.
