### ISSUE TITLE
Unnecessary `devcontainer.json`

### ISSUE THREAD

**Issue by bjones1** [PreTeXtBook/pretext-cli#490]
We currently have three `devcontainer.json` files:
- [.devcontainer/devcontainer.json](https://github.com/PreTeXtBook/pretext-cli/blob/main/.devcontainer/devcontainer.json) create a developer's Codespace for working on a CLI.
- [templates/.devcontainer.json](https://github.com/PreTeXtBook/pretext-cli/blob/main/templates/.devcontainer.json) is used for creating a new author's PreTeXt Codespace for writing/editing a PreText book.
- [.devcontainer.json](https://github.com/PreTeXtBook/pretext-cli/blob/main/.devcontainer.json) is a copy of the file above, but isn't AFAIK used.

Can we delete this file?

**Comment by oscarlevin** [comment]
The last one must have been copied by mistake.  Or perhaps one of the scripts adds it...
