### ISSUE TITLE
Create `site` directory when deploying (or skip it gracefully)

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#491]

**Comment by StevenClontz** [comment]
Related: Terri's local git setup did not successfuly deploy even after we added this directory and a dummy index.html. It did work in Codespaces though.

**Comment by StevenClontz** [comment]
Deploys also apparently worked before the 1.7.2 upgrade.

**Comment by oscarlevin** [comment]
I'm not sure what this issue is.  I thought I had it wired up to only deploy the "site" directory when there were `<deploy-dir>` elements in one or more targets.

**Comment by oscarlevin** [comment]
Got it.  In fact, we should create at least a very minimal landing page to point to each target.  I'll work on that ASAP.

**Comment by oscarlevin** [comment]
This is fixed as an issue, but we of course have more to do on generating a `site` automatically.  But that's a different project.
