### ISSUE TITLE
Remove `--project-ptx-override` in v2

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#507]
With pretext 2.0.0, the `Project` and `Target` classes are refactored so that it should be easy to use them as when importing pretext as a module.  I believe this basically eliminates the need for `--project_ptx_override`.  @siefkenj, since this was your contribution, do you have any feelings about this?

**Comment by siefkenj** [comment]
I think it is still relevant. `--project_ptx_override` is for use with the commandline so you can avoid coding/creating files.

**Comment by StevenClontz** [comment]
New workflow would be a Python script or REPL.

See e.g. https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/main/slides/build.py

Would that cover your use case?

**Comment by oscarlevin** [comment]
The plan is to remove this for now, and we can always bring an equivalent feature back if there is need for it.  Implementation would be much easier with the refactor.
