### ISSUE TITLE
Correctly find log

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#51]
https://github.com/PreTeXtBook/pretext-cli/blob/1a333095cfffaaf80f00b922f3d4516c3a7a97cc/pretext/build.py#L91

The above hack seems to be broken if my CLI is living in a folder named `pretext-cli`. While I imagine this wouldn't be broken in production (since it's named pretextbook in PyPI) I feel there must be a more elegant way to handle this. (For now, I've renamed `pretext-cli` to `ptx-cli` on my machine.)

**Comment by oscarlevin** [comment]
Fixed on 563d59b.  Now logfile will be located at `build.log` instead of `html-build.log` or `latex-build.log`, which is better anyway since we are building different targets in their own directories.
