### ISSUE TITLE
Files provided in `site` should overwrite PTX files

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#510]
See discussion: https://groups.google.com/g/pretext-support/c/BS6bWcqvuaA

**Comment by rbeezer** [comment]
Please make sure to document that this behavior will neuter the publisher's election in the publisher file.

**Comment by StevenClontz** [comment]
Yes, in general, this could be used to do very annoying things, so it should be used judiciously.

**Comment by oscarlevin** [comment]
This is currently done in 2.0.0.  The entire contents of the `site` directory is copied over to the `stage` last, so anything there will overwrite files copied from generated targets.  This should be fine though.
