### ISSUE TITLE
Make deploying to Runestone easy

### ISSUE THREAD

**Issue by bjones1** [PreTeXtBook/pretext-cli#513]
I'd like to head up this effort with PRs to the `refactor2` branch.

**Comment by bjones1** [comment]
Notes from today's drop-in discussion:

- Create a new format: Runestone. This is really just HTML with a few tweaks.
- Try passing a stringparam of `host-platform = runestone`. This might be an easy alternative to creating a new publisher file with the `<platform host="runestone">` tag unnecessary. Otherwise, take the existing publisher file and perform this edit automatically.
- Modify the templates to add a Runestone target.
- Modify the templates to add the following to the `<docinfo>` tag in `main.ptx`:
    - Add a `<document-id>change-this-for-runestone</document-id>` tag, along with comments explaining what content is allowed for this tag. Comment text: "Note Runestone’s preferred practice for the <document-id> is to have a simple lowercase string with no dashes or other special characters. This value is visible to readers who want to register for your course on Runestone outside of any formal setting."
    - Add the following tag:
     
        `<!-- See https://guide-link for valid values of @shelf; one example (below) is "AP Computer Science". -->`
        `<blurb shelf="AP Computer Science">A simple string (no markup is allowed) to describe your book. Think of something like what you would read on a book jacket. This is used only when publishing using Runestone.</blurb>`
- Check the `<document-id>` to make sure it's valid.
- Disallow `@output-dir` for a Runestone target. Instead, automatically use `published/document-id` instead.

**Comment by bnmnetp** [comment]
I like the direction this is headed...

When you say the "existing publisher file" how do we know what that is?  There could be several publisher files.  -- do we assume that we use the one in the web target?

Another thing to consider is that there are people working on a new shell and style for runestone academy books.  That would restore some of the things that people look for in the nav bar and are sorely missing in the current shells.  Once that is known I guess we could programmatically change the style information to use that for academy to ensure we have a consistent look.

**Comment by bnmnetp** [comment]
Today this is done in the publication file inside the html tag.   Here is what I have in my data structures book:

```
<html>
...
<css style="oscarlevin" colors="blue_red" toc="crc" banner="crc" navbar="crc" shell="crc"/>

...
</html>

```

**Comment by bjones1** [comment]
Perfect -- this is easy to accommodate; just put it in the publication file as always. You can either share a publication file with the web-only target, or have a separate publication file for the Runestone target. What's different: the CLI now automatically sets `<platform host="runestone">` for the Runestone target, instead of authors needing to add this to their publication file.

**Comment by bjones1** [comment]
A working prototype is in #516.

**Comment by rbeezer** [comment]
> Create a new format: Runestone. This is really just HTML with a few tweaks.

I'm starting to lean negative on this one.  The HTML stylesheet produces two flavors of HTML: regular and Runestone.  It once made an AIM flavor (for the UTMOST research study) and will eventually produce a React flavor.  The LaTeX conversion produces two flavors of PDF: electronic and PDF.

We control all these options via a configuration file, aka the publication file.  And in every case there are likely multiple entries that should, or could, be set.  In particular, I will soon release some documentation about how the generated files can vary for different output formats.  Which is also handled by the publication file.  Sounds like Brad wants a common look for projects hosted on Runestone - another publication file entry.

So, to suggest that a single publication file is fine for "web" and Runestone sounds inaccurate to me, at a savings of not adding a single line to a publication file.  Having the CLI manage entries of the publication file is not the sort of separation I have envisioned as an interface to core PreTeXt.

**Comment by bnmnetp** [comment]
Despite documentation to the contrary I've worked with at least 4 authors over the last few weeks, that made a runestone ptx file that simply had the platform tag and nothing else.  Assuming it would "inherit" the other data.  So, this seems to be a problem.

Yes, for books on runestone I would like to have something akin to the CRC style and shell. So that we can have a an easy visible way for people to get to the home page.

My understanding of this work is that it does not preclude a separate publication file for Runestone.

I am sympathetic to not wanting to repeat yourself.  Currently the most common use case is just that the runestone publisher file is a copy of the web file with one thing added.

**Comment by StevenClontz** [comment]
Brad is the publisher in this scenario, so he should have the tools to manipulate publisher settings programmatically, rather than requiring the authors or him to configure things manually.

**Comment by bjones1** [comment]
Conceptually, I agree with @rbeezer: the decision to produce a PreTeXt document as HTML, PDF, or Runestone is a publication decision. However, the structure of the publication file seems a bit odd in this regard to me: a single publication file may contain options specific to HTML, PDF/LaTeX, slideshow, or EPUB -- but the same file can't contain Runestone options, since these conflict with HTML options. This forces the use of two publication files for authors that want to publish to Runestone, which feels awkward to me.

(On a side note, IMHO the [Directory Management](https://pretextbook.org/doc/guide/html/publication-file-source.html#publication-file-directory-management) options in the publication file really belong in the CLI...)

**Comment by bjones1** [comment]
My notes from today's discussion:
- Rob prefers not to create a separate `<runestone>` section, parallel to `<html>`, in the publication file; this follows the path of the `<latex>` section, which offers either a print or an electronic version of the output.
- Brad wants to avoid manual edits to authors' books, specifically creating publication files for Runestone.
- Brad points out that few authors actually need to build a Runestone book; they simply need to provide him with all the relevant files.
- Oscar suggests that the `pretext deploy` process would have a special `runestone` option, which would:
  1. Ensure that the `<document-id>` and `<blurb>` elements are present in the source's `<docinfo>` tag.
  2. Add a target named `runestone` to the project file if it doesn't exist; this added target would be accompanied by an added publication file, which is a copy of the current publication file except for the modified `<html platform="runestone">` attribute.
  3. Check that the Runestone target's `output-dir` and `output-filename` attributes are not present. Verify that `<html platform="runestone">` in the publisher file.
  4. Get a special token from Brad (how?) to authorize pushing to his author server, then push the book source there. (Do we need to store this token somewhere, for future pushes?)
  5. Open an author server URL to allow the author to build/test/deploy using the Runestone author interface.
- My ideas:
  - I'd rather not modify existing files, in case our code corrupted/deleted/damaged an existing file.
  - I propose that newly-created templates would contain two publication files (one for Runestone and another that's the traditional publication file), a target named `runestone` in the project file, and the appropriate `<document-id>` and `<blurb>` in the source file.
  - Instead of modifying anything in the process above, we'd instead check everything and point out what needs to be done. That is, omit step ii in the process above.

**Comment by bjones1** [comment]
Closing -- all relevant code implementing this is merged.
