### ISSUE TITLE
Extra space in publication path

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#524]
In the middle of other things, but I got a warning when compiling DMOI today that my manifest is not ready for 2.0.  The reason was that the publication file didn't exist.  Somehow a space is being inserted between the project directory and the relative publication path in 1.7.5.

**Comment by oscarlevin** [comment]
Okay, the error was mine.  But perhaps we should strip spaces around these anyway?

**Comment by bjones1** [comment]
Maybe -- at a minimum, we should warn the user if there are spaces before/after the path/file name.

**Comment by oscarlevin** [comment]
I looked into this a bit, and it doesn't seem easy.  But also not particularly helpful, as our error messages are much improved now.  Closing.
