### ISSUE TITLE
avoid too much boolean logic...

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#549]
https://github.com/PreTeXtBook/pretext-cli/blob/20f4b74feee84bfacf3169286e9d835f3d86d98d/pretext/project/__init__.py#L442

Rather than `no_generate = False` why not `generate = True`?

**Comment by oscarlevin** [comment]
How about `if_false_then_not_no_generate == True`?  

But yeah.  The reason to keep no_generate is because that is what the option in the CLI is called.  But I agree switching for the internals makes sense.

**Comment by StevenClontz** [comment]
i'll make a pr
