### ISSUE TITLE
latex-Image output formats

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#55]
Currently we generate only svg image formats from latex-image.  It should be possible to generate other image formats using some sort of option.

**Comment by oscarlevin** [comment]
Partially implemented at 3239688, except that png fails on Windows (at least) so 'all' option also throws an error.  

Suggestions for a better flag than -df or --digrams-format welcome.

**Comment by oscarlevin** [comment]
Next up: generating images from source other than latex-image.  For this, it seems we should look for all image containing tags and call the correct pretext/pretext routines, rather than having an option.   Is there a use case for an author who would want to generate only asymptote but not latex-image from a document that contains both?  Maybe for large projects...

**Comment by oscarlevin** [comment]
Upon further investigation, the pretext/pretext script has an `all_images` function that does exactly what we want.  But it requires a `@generated-images` attribute in the publisher file (related to the image management stuff), which I don't really understand.  So I propose we hold this back to 0.3 so we can understand this better, including how to better manage the publisher file (I'm thinking maybe the cli fills in defaults when they are not present)

**Comment by rbeezer** [comment]
`@generated-images` is undocumented, subject to change, and perhaps already changed on a current branch of mine.

I suspect if this attribute is not present in the publisher file, the routine in question will function just fine.  That is status quo.  Try it out?

**Comment by StevenClontz** [comment]
Since png seems broken upstream, we'll disable that functionality for 0.2 release.

**Comment by oscarlevin** [comment]
Removed png and all targets for now (at 600613c).  Will leave open and set 0.3 milestone to get these added back in when pretext/pretext is fixed.

**Comment by oscarlevin** [comment]
Calling all_images(...) without publisher file (or without the `@generated-images`  does indeed throw an error.  I don't think this is a problem for anyone using the command line pretext/pretext, since there is no way to call that function right now.  I just got excited that you did most of the work for us.

**Comment by rbeezer** [comment]
> does indeed throw an error

Sorry.  Mostly shooting in the dark from here.  I'll be back into image management after about a week, so hopefully can get some of that straightened out.

**Comment by oscarlevin** [comment]
@rbeezer and @daverosoff , maybe we can fix the png on windows build error before the end of the workshop?

**Comment by oscarlevin** [comment]
Thanks to @daverosoff , I can confirm that the png issue was mine and not either the cli or pretext.py: windows has another `convert` command that was being called instead of imagemagic's.

The last two image output formats will be available upon the merge of #121
