### ISSUE TITLE
Scaffold default project to have a few files

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#578]
Right now we have this beautiful CodeChat authoring workflow, but it only functions well if the PTX file matches the produced HTML page. So we should use xi:include to ensure each section/chapter/frontmatter/etc has a separate file for use with CodeChat.

Alternatively: if CodeChat can infer the cursor location, maybe it's possible to grab the xml:id from the part of the active file being edited? @bjones1

**Comment by bjones1** [comment]
Maybe? I'm pretty sure I can get the cursor's location from VSCode. Given that, we could probably search backward for a regex matching and xml:id. Do you think that would be good enough? Otherwise, that means parsing with lxml (what about malformed xml that causes a parse failure?) then hoping lxml records a character offset for each parsed element.

**Comment by StevenClontz** [comment]
Searching for `xml:id="foo"` seems simple. But we're going to have to worry about this pattern:

```xml
<chapter xml:id="ch-dont-want-this">
  <section xml:id="sec-do-want-this">
    <figure xml:id="fig-dont-want-this">
      <!-- cursor is here -->
    </figure>
  </section>
</chapter>
```

**Comment by oscarlevin** [comment]
And that's assuming the html is chunked at the appropriate level anyway.  Does CodeChat work if the `xi:include` scheme is out of sync with the chunking level at all?

**Comment by bjones1** [comment]
CodeChat just records every `xml:id` it finds, plus what file it found that `xml:id` in. Given a file name of the HTML output (which, currently, is based on an `xml:id`), it find the source file which contains this `xml:id`. So, it shouldn't be affected by chunking.

**Comment by bjones1** [comment]
> Searching for `xml:id="foo"` seems simple. But we're going to have to worry about this pattern:
> 
> ```
> <chapter xml:id="ch-dont-want-this">
>   <section xml:id="sec-do-want-this">
>     <figure xml:id="fig-dont-want-this">
>       
>     </figure>
>   </section>
> </chapter>
> ```

I think this is do-able; given the list of `xml:id`s, then we keep searching in the regex until we find a matching file in the filesystem. A bit ugly, but probably not that slow.

**Comment by oscarlevin** [comment]
I've added files to the `pretext new book` template, which takes care of this issue.  @bjones1, not sure if you are interested in pursuing the alternative suggestion, but if so, let's create a new issue for that.

**Comment by bjones1** [comment]
Eventually, but I have several other tasks before I get to this one...
