### ISSUE TITLE
Update documentation/help

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#58]
We should review the changes we made to 0.1rc0 and make sure they are reflected (ideally) in `--help` calls, and in the documentation if necessary.

**Comment by oscarlevin** [comment]
I _think_ I have added enough help to document the new features that are available.  No work on the documentation yet.

**Comment by StevenClontz** [comment]
I'll work through the docs and build the new `--help` output.

**Comment by StevenClontz** [comment]
Closed in fd4223517b4b5e9d0d1c52ab03d7ca96f0a73ff1
