### ISSUE TITLE
Refresh .gitignored config files on every run of the CLI marked as managed by CLI

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#582]
Rather than require users to maintain `codechat_config.yaml`, we can just generate it for them every time the CLI is called.

We can add a safeguard that only overwrites the YAML if it contains a comment saying it's auto-generated. That way folks can configure it manually as well.

**Comment by StevenClontz** [comment]
Rather than requiring a manual `pretext init -r`, or tracking hashes of files we know we've generated, maybe this is a simpler solution. We can have a line like

```xml
<!-- Managed by PreTeXt-CLI -->
```

or

```python
# Managed by PreTeXt-CLI
```

or

```json
"managed_by_pretext_cli": true,
```

that we include in every file we want to keep updated for our users. Then, they can edit these manually if they want, but if so, they are responsible for keeping them updated. Otherwise, they Just Work and whenever we want to change, say, the .devcontainer, we just overwrite it the first time `pretext` is run after a `pip install --upgrade pretext`.

**Comment by bjones1** [comment]
I like it!

**Comment by oscarlevin** [comment]
This is completed in #594
