### ISSUE TITLE
Tests no longer passing

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#591]
I was about to push a 1.8.3 release to add some new features of core so Brad could build Runestone books with them.  However, since doing so, our tests no longer pass.  

The culprit seems to be that `sage` is not installed on Windows.  Of course it's not, but why were tests passing before?  What could possibly have changed in core that would cause this issue?

Note that all tests pass just fine when I run them in a Linux codespace (with sagemath installed).

Any ideas @StevenClontz or @bjones1 ?

**Comment by StevenClontz** [comment]
I seem to recall @bjones1 added testing for Sage if and only if Sage was installed. So maybe that check that Sage is installed is failing?

**Comment by StevenClontz** [comment]
I'd be supportive of a stealth push of a 1.8.3 package from a local machine as long as tests pass otherwise, if that's easier. Or maybe a 1.8.3dev20230915 just for Brad.

**Comment by oscarlevin** [comment]
Looks like it was an issue with the schema that I introduced with a bad PR to core.  Reverting to a previous commit solved the issue.
