### ISSUE TITLE
`"image": "oscarlevin/pretext:small"` does not build a PDF

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#600]
Attempting to do so results in this error:

```
! The font "Inconsolatazi4-Regular.otf" requested by PreTeXt output is not avai
lable. Either a file cannot be located in default locations via a filename, or 
a font is not known by its name as part of your system..
```

**Comment by oscarlevin** [comment]
I've added latex-fonts-extra to the small dockerfile.  Hopefully this resolves the issue.

**Comment by StevenClontz** [comment]
I think so. I may re-record my PreTeXt video this morning as a few short videos separating the how + why, and avoiding the previously-required kludge to use `pretext:full` to get a PDF.
