### ISSUE TITLE
Updates to pudantic causing type checking to fail

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#605]
I did a `poetry update` to get pymupdf added to the dependencies, and this also updated pydantic stuff.  That causes 18 type errors.  Something about FieldValidation and not having data as a type.

**Comment by bjones1** [comment]
I'll take a look!

**Comment by bjones1** [comment]
What versions are you using? I ran the tests and it's working for me on my local PC.

```
pydantic               2.4.2
pydantic_core          2.10.1
pydantic-xml           2.2.3
```

**Comment by bjones1** [comment]
The fix works.
