### ISSUE TITLE
CodeChat breakage?

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#608]
I cannot get CodeChat to work in both an existing and brand new Codespace today. Any recent changes that might explain why I'm hung up on this screen?

![image](https://github.com/PreTeXtBook/pretext-cli/assets/1559632/e8c5a67c-f1c5-4a3e-a15f-496237eb7b15)

![image](https://github.com/PreTeXtBook/pretext-cli/assets/1559632/7b8c104a-44fb-4efb-bb64-9f1eee3bd60a)

(Found this out when I tried to record a new Getting Started video...)

**Comment by bjones1** [comment]
No, I haven't changed anything on my end. Does making a small edit, or switch files, help?

**Comment by StevenClontz** [comment]
Nope

**Comment by bjones1** [comment]
I'll play when I have a minute...

**Comment by bjones1** [comment]
This is the client running in the webview trying to reach the server.

**Comment by bjones1** [comment]
Still working on it. It looks like the websocket connection doesn't work on Codespaces (but still works fine on a local machine). However, I'm not sure why that connection isn't routed properly (yet).

**Comment by bjones1** [comment]
OK, fixed now. Do a `pip install -U CodeChat_Server` in the Codespace to test.

**Comment by StevenClontz** [comment]
That did it.

I don't think we have CodeChat_Server as a dependency of PreTeXt-CLI so we need to make the fix elsewhere (pretext-tools?) to force users to upgrade so CodeChat works. In the meantime I'll make an -announce post.

**Comment by oscarlevin** [comment]
It seems like the codechat vs code plugin is the right place to require codechat_server.

**Comment by bjones1** [comment]
> It seems like the codechat vs code plugin is the right place to require codechat_server.

Do you mean the CodeChat VSCode plugin should automatically run `pip install -U CodeChat_Server` if the CodeChat server isn't installed?

**Comment by StevenClontz** [comment]
I'll rephrase: I'm ignorant to how codechat is installed for a codespace, like most of our users. I just want to make sure this feature works for them, by making sure the most recent version is installed the next time they create or start a codespace.

**Comment by StevenClontz** [comment]
In particular, I just spun up a new Codespace and it's using the old CodeChat_Server. So maybe the real place I want this to be updated is our Docker images? And then my usual advice (rebuild your container) would fix any codechat issues?

**Comment by oscarlevin** [comment]
Something is broken in the docker image and images are not being automatically built.  I'm getting an error when trying to pip install codechat-server (or maybe pretext): https://github.com/oscarlevin/pretext-docker/actions/runs/6444519353/job/17497597340

**Comment by bjones1** [comment]
I see the error when building greenlet, which is a dependency of playwright:

```
poetry show greenlet
 name         : greenlet
 version      : 2.0.2
 description  : Lightweight in-process concurrent programming

required by
 - playwright 2.0.2
```

I'm not sure how to work around this.

**Comment by bjones1** [comment]
Another problem: we need to do a `poetry update` then commit that new lock file to get the latest CodeChat Server. I'll send a PR for that.

**Comment by oscarlevin** [comment]
> > It seems like the codechat vs code plugin is the right place to require codechat_server.

> Do you mean the CodeChat VSCode plugin should automatically run pip install -U CodeChat_Server if the CodeChat server isn't installed?

Yes.  For pretext-tools I have a popup that asks if they want to install the cli.  If yes, then it sniffs the user's python version, ensures that pip is installed, and the runs the pip install command.

See https://github.com/oscarlevin/pretext-tools/blob/e481b9d08ae3b9b4a0060d1ed0753a0d2a1c5b67/src/extension.ts#L94.

**Comment by bjones1** [comment]
Neat, thanks! I'll work on adding this.

**Comment by oscarlevin** [comment]
Okay, I think I have it.  Docker images are rebuilding now.  

For future me: there was a problem rebuilding the wheel for `greenlet`.  Using the command `pip install pretext --only-binary {greenlet}` made sure to use an existing wheel.

I also changed the base image to the same one that codespaces uses by default, which might have helped.

@StevenClontz, you should be good to proceed with the explainer videos

**Comment by StevenClontz** [comment]
> @StevenClontz, you should be good to proceed with the explainer videos

Will do, modulo that I'll be using a 2.0.5 nightly to record, and we should release 2.0.5 (or 2.1) before releasing the videos.
