### ISSUE TITLE
`latex` format fails to copy external directory

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#619]
To replicate:

```bash
pretext new
cd new-pretext-project
mkdir assets
touch assets/foo.txt
pretext build print-latex # no external directory is copied!
```

**Comment by StevenClontz** [comment]
I looked back and found where we used to handle this: https://github.com/PreTeXtBook/pretext-cli/blob/3bb3b6bf057076064e98927480a815ea29ee4499/pretext/project.py#L410

I guess maybe this got forgotten in the 2.0 refactor? Though I'm unclear why `generated` is being copied but `external` is not.

**Comment by StevenClontz** [comment]
> I guess maybe this got forgotten in the 2.0 refactor? Though I'm unclear why `generated` is being copied but `external` is not.

For posterity: I don't think `generated` was being copied, actually.

**Comment by oscarlevin** [comment]
It looks like we should manage directories in the CLI.  Should this also be done for the custom target???

**Comment by StevenClontz** [comment]
Yeah, I think we should run `core.get_managed_directories` and `core.manage_directories` (once it exists) to put files where our users will expect them.
