### ISSUE TITLE
Params with colons

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#62]
https://twitter.com/aacooper/status/1300957668614512640?s=20

**Comment by oscarlevin** [comment]
Yup, we need to fix this.  Options:

1. Go back to =, so --param toc.level=2, etc.
1. Use a space.  This is what xsltproc does.
1. Something else?

**Comment by StevenClontz** [comment]
1. `=` could still be part of a valid URL so that's a no-go I think.
2. ` ` is safer as typically it's escaped as `%20` in URLs, and (maybe) there's no good reason to pass a param with a space
3. We could simply only split on the first colon. So `foo:bar:baz` would split to the python dict `{'foo': 'bar:baz'}`. I'm leaning this way, unless we need to consider the possibility of a param key with a colon in it.

**Comment by StevenClontz** [comment]
This is fairly breaking so this should be a 0.1.1 release.

**Comment by oscarlevin** [comment]
Splitting on the first colon seems reasonable.  A minor concern is that anyone who has stored stringparams in a config file should not be inconvenienced by this bugfix.  Until we get the config file to list stringparams as separate entries.  The current config file entry looks like:

`param = ('toc.level:2', 'html.knowl.example:no', 'numbering.projects.level:0')`

**Comment by StevenClontz** [comment]
New branch at https://github.com/PreTeXtBook/pretext-cli/tree/0.1.1

**Comment by StevenClontz** [comment]
I'll leave handling config file stuff to you, I just pushed a fix to the 0.1.1 branch. Once you're happy with it I'll publish rc0 to PyPI and get Cooper to try it out before publishing 0.1.1 public.

**Comment by StevenClontz** [comment]
@rbeezer are there any param keys that contain a colon? If colon-less keys can be counted on then splitting on exactly the first colon seems the most robust solution, as it allows arbitrary text as the value.

**Comment by oscarlevin** [comment]
Looks good to me.  My config file still works (as expected).

**Comment by StevenClontz** [comment]
Okay @rbeezer let me know about the colon thing, but I'm pretty sure keys are just letters and periods. So I'm going to push out rc0 and get at least Cooper to try it.

**Comment by rbeezer** [comment]
Every "stringparam" I've built (I think) is all lower-case and uses periods as separators.  No colons.  I'm talking about the name, maybe you mean the value?  Less certain, but no colons come to mind.

**Comment by StevenClontz** [comment]
Values definitely have colons (e.g. `https://...`) which was the issue here. Glad to hear that the keys seem to be colon-free as expected.

**Comment by rbeezer** [comment]
Ignore this - testing my email filters so a mention of @rbeezer will light up my email (I get **everything**) already, so nothing is special.

**Comment by StevenClontz** [comment]
Closed in 54cd7b23a4cd065d2b65e4a7ecb4f27cb8afc378
