### ISSUE TITLE
Error screenshotting interactives without xml:id

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#648]
Add `<interactive geogebra="KGn2d4Qd" />` to a fresh PreTeXt project using our Codespace et al (using the small or full Docker image), and you cannot build the `print` target.

But `<interactive xml:id="foo" geogebra="KGn2d4Qd" />` works just fine. I think there's an issue with numbering - someone is inferring the wrong filename/number for the HTML page that's supposed to be screenshot.

**Comment by oscarlevin** [comment]
I'm pretty sure this is a core issue that is being worked on.  Closing here.

**Comment by rbeezer** [comment]
Yes, this was fundamentally addressed, recently, at

https://github.com/PreTeXtBook/pretext/commit/bee1919d68417866ca29915cc6d316777bf9d211

along with a whole lot of surrounding supporting work.
