### ISSUE TITLE
general assets directory

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#65]
Keeping in mind conversation here https://groups.google.com/g/pretext-dev/c/A2mFEBobxG0/m/f6P0Qz6yAwAJ I think maybe we want a general `assets` directory in the source, with `images` as a subdirectory. In particular, I'm working on a book with many Python scripts that currently are stored in `my-great-book/source/files/foo.py`. Right now I'm just including them via XML and everything's fine. But if I wanted to *distribute* them (or any generic files) there's no automatic way to do so other than manually copying them into my output folder. I think it's reasonable to support a canonical `project/source/assets` directory that's distributed with HTML output (which would include things like images).

**Comment by oscarlevin** [comment]
This is implemented in 0.3
