### ISSUE TITLE
fix permissions issues for `pretext new` and `pretext build [html format]`.

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#652]
https://groups.google.com/g/pretext-support/c/4YGa5UnTBnU

**Comment by StevenClontz** [comment]
I did some troubleshooting in that thread...

> The output/web problem is either an issue with the core PreTeXt python module, or perhaps how we're importing it somehow?

```
>>> pretext.core.html('/workspaces/effective-funicular/new-pretext-project/source/main.ptx', '/workspaces/effective-funicular/new-pretext-project/publication/p
ublication.ptx', {}, None, "html", extra_xsl=None, out_file=None, dest_dir='/workspaces/effective-funicular/new-pretext-project/output/web')
@StevenClontz ➜ /workspaces/effective-funicular/new-pretext-project (main) $ ls -la output/
total 12
drwxr-xrw-+ 3 codespace codespace 4096 Dec 21 17:00 .
drwxr-xr-x+ 8 codespace codespace 4096 Dec 21 17:00 ..
drwx------+ 5 codespace codespace 4096 Dec 21 17:00 web
```


> It is not an issue with how CLI imports pretext.py:

```
>>> pretext.pretext.html('/workspaces/effective-funicular/new-pretext-project/source/main.ptx', '/workspaces/effective-funicular/new-pretext-project/publication/publication.ptx', {}, None, "html", extra_xsl=None, out_file=None, dest_dir='/workspaces/effective-funicular/new-pretext-project/output/web')
@StevenClontz ➜ /workspaces/effective-funicular/pretext (master) $ ls -la /workspaces/effective-funicular/new-pretext-project/output/
total 12
drwxr-xrw-+ 3 codespace codespace 4096 Dec 21 17:08 .
drwxr-xr-x+ 8 codespace codespace 4096 Dec 21 17:08 ..
drwx------+ 4 codespace codespace 4096 Dec 21 17:08 web
```


> (to be clear, I git cloned the latest PreTeXtBook/pretext and imported pretext.pretext directly from Rob's repository in the last post)

**Comment by StevenClontz** [comment]
I'm stepping away from this for a bit, but a theory: I seem to recall that, perhaps, both our provisioning of a new pretext project and Rob's building of an HTML target happen in a temporary directory. Perhaps the permissions of this temporary directory are 700, and we need to manually fix permissions when we copy things over?

**Comment by oscarlevin** [comment]
Waiting for my codespace to spin up, but perhaps this has something to do with `shutil.copytree` using `copy2()` by default which is supposed to preserve permissions (and that when we create files in the temp directory, they get set to be more restrictive).  There is a way to change the copy method.  https://docs.python.org/3/library/shutil.html#shutil.copytree

**Comment by StevenClontz** [comment]
It looks like this likewise is the case at https://github.com/PreTeXtBook/pretext/blob/master/pretext/pretext.py#L3326

**Comment by StevenClontz** [comment]
Another solution: rather than building directly in to a temporary directory, we/core can create a directory inside the temporary directory (which I think will have the right permissions), build things there, and copy that.

**Comment by oscarlevin** [comment]
I guess it makes sense that this is new, since it wasn't that long ago that we convinced @rbeezer to switch to shutil.copy() requiring the bump to 3.8

**Comment by oscarlevin** [comment]
Tried changing the `copy_function` to `copy` instead of `copy2` and this did not help.  But both preserve permissions, it seems.

**Comment by StevenClontz** [comment]
I tagged the wrong issue

**Comment by oscarlevin** [comment]
Confirming that #655 does fix this for the `pretext new`, but will not help with core pretext's use of the build in temp, shutil copy out pattern.

**Comment by StevenClontz** [comment]
https://github.com/PreTeXtBook/pretext/pull/2101 should close this I think then.

**Comment by oscarlevin** [comment]
Perhaps I'm being paranoid now, but it seems like core does a lot of things with temporary directories and then copies the result back to the right place.  Perhaps implementing the subdirectory trick here instead: https://github.com/PreTeXtBook/pretext/blob/2930c68504dd1c2710e0afbd1e0f785a785c632a/pretext/pretext.py#L3945

**Comment by StevenClontz** [comment]
good call Oscar - I'll update my PR

**Comment by StevenClontz** [comment]
Actually that's not quite a one-liner: Rob manually manages a list of temporary directories that he has a cleanup method for, which would not quite work if I returned a subdirectory of the temp directory. So there's a few ways to make it happen, but I'd rather @rbeezer make the call on his end.

**Comment by StevenClontz** [comment]
Actually nah, I think just coercing permissions for the directory is the right way to go: https://github.com/PreTeXtBook/pretext/pull/2101/commits/d51c9c00c0ce259a7052113e7d309d5a9bc40f0b

**Comment by oscarlevin** [comment]
That works.  Or you could return the subdirectory but append the temp directory to the list of directories that will need to be destroyed.

In the mean time though, should we fix the output directory in the CLI?  I can work on this.

**Comment by StevenClontz** [comment]
Yeah - we'll let Rob decide on how he wants this refactored, but I think this works. And in the meantime you've got a patch on our end in the pipeline.
