### ISSUE TITLE
Remove `project.ptx` from list of files "managed by pretext"

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#653]
We have had at least 3 people confused by our rewriting of their edited project.ptx file.  The easiest solution would be to simply remove it from the list of files that we manage (and users could still get a fresh copy using `pretext init -f project.ptx`).  

I don't think we lose much here by doing so.  Definitely having a managed .ignore and .devcontainer makes sense as we are likely to push changes to these.  But unless we do another redesign for v3.0, I don't see us ever changing the default project.ptx.

**Comment by StevenClontz** [comment]
I agree

**Comment by StevenClontz** [comment]
Fortunately this is very simple: remove the line in our template and no further action is needed, and users will get the update next time they run pretext.

**Comment by StevenClontz** [comment]
See also https://bugs.python.org/issue41884

**Comment by oscarlevin** [comment]
Closed by #656
