### ISSUE TITLE
Validate xml prior to building

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#66]
Is there an xml lint provided by lxml?  Currently, things like extra `<` cause problems without sending any useful error messages.  This would help with the more general problems of providing feedback and good error messages.  See #43 .

**Comment by rbeezer** [comment]
Some hints here?

https://emredjan.github.io/blog/2017/04/08/validating-xml/

**Comment by oscarlevin** [comment]
One part of validation is checking for well formed xml.  This is now implemented at de1b02b.  Note the strange necessity of calling source_xlm.xinclude() multiple times to catch errors in nested xinclude-ed files.

Next up: validating against the schema (which is also #29)

**Comment by oscarlevin** [comment]
In 6d6600d, there is now some simple schema validation checking done when building, although errors do not interrupt the build (most books seem to have schema violations).  This also required that we import the schema into static, so the update_core.py script has been modified to do this.

What we are doing now is to use the pretext.rng file to use lxml's RelaxNG validation.  However, the errors we get are very unhelpful.  For example, the schema violation in `tests/schema-error.ptx` is that there is a `<p>` nested in another `<p>`.  The error given by RelaxNG validation is "./tests/schema-error.ptx:10:0:ERROR:RELAXNGV:RELAXNG_ERR_ELEMNAME: Expecting element idx, got introduction" (and a bunch of other equally useless messages).  

Incidentally, I tried to use the xst validation, but lxml gave an error claiming "lxml.etree.XMLSchemaParseError: local complex type: The content model is not determinist., line 1511".  @rbeezer, any ideas why that might be?

**Comment by rbeezer** [comment]
I've wasted hours trring to make sense of the error messages from these routines.  I'd love it if you cracked the code in a way we could explain to authors.

Not exactly sure what `xst` validation is.  But I think I know the problem.  RELAX-NG lets you specify combinations of elements *and* attributes as disjoint options in the schema.  A W3C schema is not this flexible.  When I convert the PreTeXt RNG schema into a W3C schema, I get three violations of this nature where it mentions determinism and then says the conversion is "approximating".  So I think the schema browser must have a few inaccuracies.  So I'm just running off the `determinist` clue here.

**Comment by oscarlevin** [comment]
That makes sense.  I meant `xsd` instead of `xst`; I was using [etree.XMLSchema()](https://lxml.de/validation.html#xmlschema).

I'll see if I can make more sense of the error messages.  Perhaps another python library needs to be brought in.

**Comment by StevenClontz** [comment]
Currently accomplished with `.error_schema.log` and `error_syntax.log`.
