### ISSUE TITLE
fix stdout vs stderr

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#660]
CodeChat color-codes based on standard output vs errors:

![image](https://github.com/PreTeXtBook/pretext-cli/assets/1559632/7d19f06f-f6bf-4647-8977-9c34e3328f02)

At some poine we should find a way for CLI to only use stderr when we have warnings and errors.

**Comment by oscarlevin** [comment]
I think this is relatively easy to configure with the logging package.  I'm not sure what the best practice is though.  I vaguely recall thinking about this when I initially set things up and some advise that all logging should be sent to the same place.  But it is worth looking into for sure.
