### ISSUE TITLE
Allow users to build against a pr or commit of core pretext

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#673]
What should the interface look like?

**Comment by StevenClontz** [comment]
Notes on our previous discussion:

How about `pretext build --dev-static abc123`, where `--dev-static` is not exposed with `--help`?

**Comment by bnmnetp** [comment]
I would love to see that extended slightly to include the working directory of a local pretext core repo.  

For those of us who do occasional development that includes the core, but build a book for testing with the cli this would be really helpful.

**Comment by oscarlevin** [comment]
I'd like to include both a way build using either a hash or a local directory.  

But note that regardless, this would not respect any changes to the core python script.  To use that, you would need to set up a cli development environment.

**Comment by StevenClontz** [comment]
Potential blocker here - we cannot monkeypatch core Python into a pip-installed pretext-CLI.

What I would... okay Oscar just said it: we should make it as easy as possible for advanced users to install CLI from source with core PreTeXt resouces from source.

**Comment by bnmnetp** [comment]
So, maybe this is duplicating functionality I can already get with the pretext-cli and pretext core repos installed side by side?  

I don't follow the argument about monkey patching if you can have a ``.ptx/COMMIT_HASH`` then why not a ``.ptx/local`` ?  the ``--dev-static`` could be a path instead of a hash?

**Comment by oscarlevin** [comment]
Since there is no way to patch in the core python script, let's just keep the current workflow of using `poetry shell` and `python ./scripts/symlink_core`.  Detailed directions will be in [this help file](../docs/core_development.md)
