### ISSUE TITLE
Unclear what `init` means

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext-cli#688]
As a user coming from the world of `npm`, where `npm init` is how you set up a new project, I ran `pretext init` which set up a broken project. Then, I saw that `pretext new` might be relevant, so I ran it, only to discover that it refused to run because of the files created by `pretext init`.

The `-h` documentation does not seem to explain when one would use either of those commands. I suggest making it more obvious and adding a suggested default (`pretext new` I presume) to the output of the bare `pretext` command so that its more discoverable.

**Comment by StevenClontz** [comment]
I think this is somewhat historical - we used `init` to "initialize" existing projects from before CLI times to use the CLI (like when you `git init` an existing project to start tracking it with Git), vs `new` for generating new projects from nothing.

In retrospect, I would have considered removing `init` entirely in 2.x had I thought about it - these days these conversions are much rarer, and can maybe handle the friction of `pretext new` into a new directory and moving files around.

+1 for clarifying `-h` here, not sure it's good to tweak further until a new major release someday.

**Comment by StevenClontz** [comment]
Making a PR for `-h` quickly.

I'm open to different behavior for bare `pretext` calls as well.

**Comment by oscarlevin** [comment]
@StevenClontz's pr should make this better.  Closing for now, but feel free to reopen if you think this needs more attention.
