### ISSUE TITLE
Confusing log output

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext-cli#689]
On the command line, the CLI outputs

```
comprehensive messages, warnings, and errors:
```

even if there are no errors. At first glance, I see the word `error` and I think something has gone wrong. I don't think this text is helpful. A blank line would serve just as well to separate it from the previous diagnostic information.

**Comment by StevenClontz** [comment]
I think that line is printed before we know if there are errors (which I think we basically pipe through from core PreTeXt). So I'm in favor of this but am not sure how trivial the change is.

**Comment by oscarlevin** [comment]
Perhaps core could report "None" when there are none.  But this is definitely an issue that belongs with core, not the CLI.

**Comment by rbeezer** [comment]
@oscarlevin is right that this is not CLI territory, but rather for PreTeXt.

I have 
* softened the lead-in message to the log
* made it appear only when there are messages to be seen

See https://github.com/PreTeXtBook/pretext/commit/512775a1a8e2988a51064b4242b827e060f10353

I'm not sure just where/how to best report a `None`.  Perhaps a good Drop-In discussion with @oscarlevin?

**Comment by rbeezer** [comment]
Forgot to say:  thanks @siefkenj for the report, much better now.
