### ISSUE TITLE
`pretext` and `pretext -h` should show version

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext-cli#694]
Both running `pretext` and `pretext -h` should print version information. `pretext -h` should print version information including the bundled version of pretext. `pretext --version` should also show the bundled pretext version.

**Comment by oscarlevin** [comment]
I agree that including the version of the cli whenever pretext is run is a good idea.  What do you mean by the bundled version of pretext?  The hash?  That's available with `pretext support`

**Comment by siefkenj** [comment]
What about the date of the commit with the hash in parens?
```
pretext-cli: 2.3.7
pretext-core: 2024-02-11 (h43jklr32j43)
```

**Comment by oscarlevin** [comment]
It doesn't seem easy to get the version number using click's built in help pages.  But I've added the CLI version to each regular run of pretext.  If you need more info, `pretext support` has it.
