### ISSUE TITLE
Jarring delay opening browser on `pretext view`

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext-cli#695]
There is currently a 3 second delay in opening a browser when running `pretext view`. This is odd behavior, since it's long enough for a user to start doing something else and then be surprised when a browser window suddenly opens.

Is it for technical reasons? I would vote for one of the following:
 1. A browser opens immediately; or,
 2. A browser does not open and an option is printed to the command line like, `press "b" to launch in a web browser`

**Comment by StevenClontz** [comment]
Issue was that the browser window was opening faster than the server booted up, or before the port was sucessfully forwarded in Codespaces.

**Comment by oscarlevin** [comment]
Next release will remove the delay for anything other than codespaces.
