### ISSUE TITLE
document images folder behavior

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#71]
It's not clear from any documentation that we assume images must be in `source/images`. But we also should consider implementing #65 before addressing this.

**Comment by rbeezer** [comment]
I'm in the midst of addressing this.  Short version: publisher file will specify location of "generated" images (absolute or relative to source) and a location of "external/source" images, always relative to source.

Modifying script to **generate** said images.  **Then** will deal with managing them as part of `pretext/pretext` script.

Watch for testing opportunities on `pretext-dev`.  ;-)

Documentation will come with code.

**Comment by StevenClontz** [comment]
closed as subset of #96
