### ISSUE TITLE
External images for slides

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#717]
Not sure if this is a CLI or core issue, but external images in a slideshow get copied to the `external` folder of the output, while the source reports them as being in the same directory as the `slides.html` folder.  @rbeezer, should this be an issue on pretext?

**Comment by rbeezer** [comment]
Good catch!  Thanks.

Moving to https://github.com/PreTeXtBook/pretext/issues/2155
