### ISSUE TITLE
Fix codespace `pretext view` again

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#724]
Apparently another change made by github has broken `pretext view` in codespaces.  Seems to be a problem with an address already being in use.

**Comment by oscarlevin** [comment]
Actually, it seems to work again.  Not sure what happened during the presentation today. @StevenClontz, were you just guessing that was what happened today, or have you seen other issues lately?

**Comment by StevenClontz** [comment]
I think we need to get rid of the auto-open window, at least in Codespaces. It seems that clicking the link in the Codespace is triggering something necessary to make the codespace alias for localhost functional.

**Comment by oscarlevin** [comment]
Further testing makes me believe this is an issue with using both CodeChat and `pretext view` in the same codespace.  If I restart the codespace and do a `pretext view`, it works fine.  If I preview with CodeChat, that works, but then I run into errors when I try to `pretext view`.  Perhaps codechat is using the same forwarded port as the python webserver we are using for viewing?

**Comment by StevenClontz** [comment]
N.B. CodeChat has switched to a different webserver besides the default Python module; dunno if that is related.

**Comment by oscarlevin** [comment]
This should now be fixed now.  Will reopen if needed.

**Comment by bjones1** [comment]
> Further testing makes me believe this is an issue with using both CodeChat and `pretext view` in the same codespace. If I restart the codespace and do a `pretext view`, it works fine. If I preview with CodeChat, that works, but then I run into errors when I try to `pretext view`. Perhaps codechat is using the same forwarded port as the python webserver we are using for viewing?

I haven't changed the ports that CodeChat uses, just the server (CherryPy).
