### ISSUE TITLE
404 on xref to an individual exercise

### ISSUE THREAD

**Issue by braughtg** [PreTeXtBook/pretext-cli#738]
Attempting to create an `xref` to a specific exercise properly generates a link within the book text, however clicking the link causes a 404.

A minimal example can be found here: https://github.com/braughtg/ex-link-pretext-bug

## To reproduce:
- Open https://github.com/braughtg/ex-link-pretext-bug in a Codespace
- Open `source/sect-section-name.ptx` in a CodeChat Preview
- Click on the link to "Checkpoint 1.1.1" at the bottom of the document.

## Observed Behavior:
When clicking the "Checkpoint 1.1.1" link I see the following error message:
![image](https://github.com/PreTeXtBook/pretext/assets/16962482/11b883ec-f63f-46da-8dee-28ac5a316a6b)

## Expected Behavior:
The document should jump to the appropriate exercise.

## Notes:
- An `xref` to an `<exercises>` block works fine.
- Pointing at the "Checkpiont 1.1.1" link shows what seems to be a correct URL to an anchor in the current page. However, clicking the link tries to navigate to a `knowl/xref/ex-foss-community-principles.html` file that does not exist.

**Comment by braughtg** [comment]
> This issue is about something entirely different

This seemed related to me since it was exactly the same functionality of referencing a specific exercise and getting an invalid link in the CodeChat preview.  So I thought this additional similar sighting might be helpful in tracking it down. I apologize if I didn't make that clear or if I missed the mark.  I'll paste the larger example over there now.

**Comment by StevenClontz** [comment]
Actually I'll give that a try...

**Comment by StevenClontz** [comment]
Okay, first, I get the same behavior as you on an initial CodeChat knowl, even though (unlike my theory) they are on the same page:

![image](https://github.com/PreTeXtBook/pretext-cli/assets/1559632/daa1ab28-9c70-4a2e-9175-25f80c417896)

But after I did a full build of the book, the knowl was built and the 404 is gone.

![image](https://github.com/PreTeXtBook/pretext-cli/assets/1559632/6b34af57-fa84-4203-982e-c489a3acfe43)

I see there's something special about that knowl that is causing unique behavior. So let me try to create a simpler xref within the same page.

Ah, same error, until I do a full build of the book:

![image](https://github.com/PreTeXtBook/pretext-cli/assets/1559632/852dc435-7134-4189-ab85-1e706c3d876e)

**Comment by StevenClontz** [comment]
So this is probably actually PreTeXt-CLI, and the way we build subsets of a book for CodeChat's preview. We try to do this snappily, and I guess at some point we decided to not build knowls. This probably makes sense - even if we did, I don't think we'd get knowls from other sections of the book.

I seem to recall that, at one point, we had toggled knowls to not function at all in a preview build. That'd make things look different than the full build though. @oscarlevin, thoughts?

**Comment by StevenClontz** [comment]
Codechat calls `pretext build web --xmlid {xml_id}`:

https://github.com/PreTeXtBook/pretext-cli/blob/dddff55a4f0170ddcbfa2de5a5c93882b2fb28f3/pretext/cli.py#L461

But, ultimately, it actually is core PreTeXt that accepts that option and runs the HTML build:

https://github.com/PreTeXtBook/pretext-cli/blob/dddff55a4f0170ddcbfa2de5a5c93882b2fb28f3/pretext/project/__init__.py#L560

Which I confirmed with Rob's script does not build knowls:

```
$ pretext/pretext -f html -p /workspaces/ex-link-pretext-bug/publication/publication.ptx -r sec-section-name -c all -d /workspaces/ex-link-pretext-bug/output/devscript/ /workspaces/ex-link-pretext-bug/source/main.ptx 
```

I'll open a thread on -dev to confirm if this is expected behavior. My guess is yes.

**Comment by oscarlevin** [comment]
This definitely seems to be a codechat specific issue, where each page is built using the xml-id shortcut.  Since we are concerned mostly with speed here, I don't think we should worry about making these xref knowls work.  Other than noticing how cool knowls are, what is the advantage to having them available in the preview?  Presumably checking whether the content renders correctly should be done by going to their source.

Perhaps we can insert some warning somewhere, or use a custom 404 page that says, "if you build the book completely, you would see a cool knowl here."

**Comment by StevenClontz** [comment]
For clarity, it's not a codechat bug, but an issue about our integration with Codechat in our VS Code authoring suite.

The custom 404 page is intriguing (return any request for `/project/path/knowl/*` with this custom page)?

**Comment by braughtg** [comment]
Awesome!!

**Comment by StevenClontz** [comment]
@braughtg if you get a chance, `pip install --upgrade --pre pretext` and let us know how this works for you.

**Comment by braughtg** [comment]
> @braughtg if you get a chance, `pip install --upgrade --pre pretext` and let us know how this works for you.

@StevenClontz The issue seems to be resolved... here is what I am observing.

Within my code space I:
- ran `pip install --upgrade --pre pretext` in the codespace terminal (log below)
- deleted the `output/web` directory since I had previously done a full build.
- opened my `main.ptx` and navigated to a page with a reference that contains an `xref` that previously gave the 404 error.
- clicked the `xref` link.
- the page jumps to the referenced exercise and highlights it.
  - This is true whether the `xref` is in the same section or a different section.
  - So, seems as if the `xref` is now correctly using a hyperlink instead of a knowl.

Great stuff!! Thanks!
