### ISSUE TITLE
Build sage-generated images

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#78]
via Jean-Sebastien:

> Hey, Pretext-CLI can't seem to generate sage produced image for me. I tested a latex-image and it works but not a sageplot one. Is that normal or am I doing something wrong?

**Comment by JeanSebastienTurcotte** [comment]
If it matters, tested on Cocalc

**Comment by oscarlevin** [comment]
I'm pretty sure this just hasn't been implemented yet.  Should be easy to fix in the next release.

We need to make a list of all the "in source" images that need separate processing by the pretext/pretext script, and then decide whether to attempt to build all of these, let the user say which ones to build, or detect which to build automatically.

**Comment by StevenClontz** [comment]
This is a subset of #55.

**Comment by StevenClontz** [comment]
Nope, I misunderstood #55 - this is a separate issue.

**Comment by StevenClontz** [comment]
Closed by 34e18fe43f6728f9b4561548eacdc08140a667b9
