### ISSUE TITLE
Guess target if target name is incorrect

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#788]
If a user types `pretext build html` and there is no `html` target (only `web`) and only one `html`, why not just build html and warn the user?

**Comment by StevenClontz** [comment]
Sounds reasonable. Can check against the finite list of valid formats, then look for a unique target with that format. 

Or could short circuit target list: given `pretext build FORMAT`, build the default Pretext source using the default publication for `FORMAT`.
