### ISSUE TITLE
De-activate much of auto-generated publication file

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext-cli#831]
Examples in the publication file may be best included as comments, rather than over-riding stock defaults, unbeknownst to new users.

Certainly the location of external and generated directories needs to be given, and are best provided automatically.  But I can't think of anything else that **must** be present.

Prompted by discussion on `pretext-support`.

https://groups.google.com/g/pretext-support/c/wmeji4iUMGQ/m/BCXpeyH9AgAJ

**Comment by oscarlevin** [comment]
This is now done.  Added a lot of the new options in comments.  But a new book should build with all defaults until the author...uh, I mean, publisher... goes poking around.

**Comment by StevenClontz** [comment]
What PR/commit closed this?
