### ISSUE TITLE
Give helpful feedback when webwork-representations.ptx is missing

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#84]
If a user forgets to build with the -w flag when they have webwork problems, and specifies the webwork-representations file in the publication file, there is an ugly lxml error.   We should check that this file exists and offer to build it if it doesn't.

At the same time, it would be good to give feedback that the webwork-representations file is not being rebuilt when running `pretext build`

**Comment by rbeezer** [comment]
Just FYI, just in case.  `XSL/lxml`  cannot check if files exist, so you will need to do that with Python.  You can easily do a minimal thing with  `lxml` to check if the relevant attribute is present within the publisher file.

**Comment by StevenClontz** [comment]
closed by #150
