### ISSUE TITLE
Improve readme instructions for development; target python v3.6.8

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#86]
The readme starts by asking developers to install and configure pyenv, but that is only available on non-windows machines.  I think this is only needed as a validation that the user has an up-to-date python install; I think we can just ask them to do a `python --version` and ensure it is greater than the minimum python version found in .python-version.

**Comment by StevenClontz** [comment]
NB it's not sufficient to allow for developers to have ≥3.6.x, as they may introduce features that rely on ≥3.7. Which is why I added infrastructure to help them ensure they're using the canonical version. Of course someone can contribute using a higher version, but we'll need to test it on 3.6.

**Comment by oscarlevin** [comment]
That makes sense.  I've been trying to do this step this morning, using pyenv-win.  I'll update the readme with instructions if there is much difference.

The first issue I've run into is: on `pyenv install "$(cat .python-version)"` I get `pyenv-install: definition not found: 3.6.12`.  Looking at the available versions (on `Mirror: https://www.python.org/ftp/python` ising `pyenv install --list`, I don't see any 3.6 releases above 3.6.8.  Should we roll back .python-version to that?

**Comment by StevenClontz** [comment]
https://www.python.org/ftp/python/3.6.12/ is a thing - maybe it's not on
Windows? (You missed it due to the lack of leading zeroes.)

**Comment by StevenClontz** [comment]
Fix https://github.com/PreTeXtBook/pretext-cli/blob/main/setup.py#L9 to not have redundant python version specs

**Comment by StevenClontz** [comment]
Add `python -m pipenv --rm` to ensure removal of old virtual environments.

**Comment by StevenClontz** [comment]
Remind devs that they need to have the right Pipfile.lock (make sure you're on a clean commit).
