### ISSUE TITLE
lint for pep8 naming

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#879]
> Would it perhaps be possible to add this as something reported by the styling tools?   https://github.com/PyCQA/pep8-naming

_Originally posted by @skiadas in https://github.com/PreTeXtBook/pretext-cli/pull/878#discussion_r1890621898_

**Comment by skiadas** [comment]
Oops I also started this on #881 
I have a commit that fixes the parts that I recently added, if you can grab that and incorporate it.
