### ISSUE TITLE
WebWork

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#9]

**Comment by daverosoff** [comment]
I'm working on adding this—almost got it, I think.

**Comment by oscarlevin** [comment]
Awesome.  Let me know if we need to update the pretext-core version to incorporate the newly announced assemblage workflow.

**Comment by daverosoff** [comment]
> Awesome. Let me know if we need to update the pretext-core version to incorporate the newly announced assemblage workflow.

I would like to do this, please.

**Comment by oscarlevin** [comment]
I'm away from my computer for the next few days.  You could pull the latest matchbook and copy over the xsl and pretext folders to our static.  Just update the readme with the commit.






Oscar Levin,  Associate Professor
School of Mathematical Sciences,  University of Northern Colorado
Campus Box 122,  Greeley, CO 80639
phone: (970) 351-2380<tel:(970)%20351-2380>    fax: (970) 351-1225<tel:(970)%20351-1225>



-------- Original message --------
