### ISSUE TITLE
`pretext init` builds `project.ptx` and `requirements.txt` and `publication/publication.ptx`

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#95]

**Comment by oscarlevin** [comment]
Inject defaults when they are missing.

**Comment by oscarlevin** [comment]
I wonder how difficult it would be to set up a `pretext modernize` that updates the project in various ways to eliminate depreciation warnings.  Most of these related to the publisher file are string params, so might be in custom xsl...

**Comment by StevenClontz** [comment]
Related(?): I want to start tracking the CLI version in `<project/>`. Eventually I want to provide `pretext upgrade` where a version Y>X of the CLI takes a `<project/>` marked as version X and makes all the changes to source that are reasonable to get it up to version Y. Particularly if things are deprecated from X to Y, it'd be nice to provide an automated upgrade path.

**Comment by oscarlevin** [comment]
At a minimum, we should build a publisher file on `pretext new` that contains defaults for all supported options.

**Comment by oscarlevin** [comment]
Consider this real-life example: after `pretext new` and a few successful builds, the author decides to add a webwork problem.  They correctly run `pretext build html -w` but the cli complains that there is no webwork-representations.ptx available.  That's because in the publisher file, they didn't have `<source webwork-problems="..\generated-assets\webwork\webwork-representations.ptx">`.   

I have updated the template publication file to have this as a commented line, which should help anyone started from scratch, but what should we do if the author loses this or uses an older version?  We could add the `@webwork-problems` with the correct value automatically.  Or we could output a warning to the console with directions of what to copy/paste into the publication file.  Or we could copy their publication file and insert the new attribute creating a publication-generated.ptx (backing up any previous version of such a file) that they could then copy over when they see what changed?

**Comment by StevenClontz** [comment]
I think we should refuse to build webwork for a target whose publication file doesn't specify `<source webwork-problems="foo"/>`, and tell the user to set it. Similarly we should refuse to build diagrams if `<directory/>` isn't set.

**Comment by StevenClontz** [comment]
That said, why don't we just set `<source webwork-problems="..\generated-assets\webwork\webwork-representations.ptx">` in the generated pub file by default? It seems to work fine on a document with no webwork. Even if you build webwork on a document that doesn't use it, it just creates a bare `<webwork/>` element in the representations file and everything proceeds A-OK.

**Comment by StevenClontz** [comment]
> That said, why don't we just set `<source webwork-problems="..\generated-assets\webwork\webwork-representations.ptx">` in the generated pub file by default? It seems to work fine on a document with no webwork. Even if you build webwork on a document that doesn't use it, it just creates a bare `<webwork/>` element in the representations file and everything proceeds A-OK.

This is done for 0.4, we'll punt the rest to 0.5

**Comment by StevenClontz** [comment]
To address the above concerns, we should update `pretext init` to build all three basic config-ish files. If any one exists at the default location, build it with a timestamp in the filename to allow user to review and rename/edit/copy/etc.
