### ISSUE TITLE
refactored `pretext new` directory structure

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#96]
Based on discussion with @oscarlevin here's the new directory structure we're aiming towards. @rbeezer the goal for 0.3 is to dump everything for XSL and your Python script to work inside of `tmp/` (including copies of the core XSL and Python script) so we can move things around as necessary. But I know you're also working on "image management", and I'd like to stay in the spirit what you have in mind.

- `assets/`

  contains images and other static files that are used by various build targets, and distributed in `assets/` subdirectory of HTML builds

    - `example.jpg`

      example static image

- `docs/`

  required subdirectory to publish via GitHub Pages

    - `index.html`

- `output/` (gitignored)

  contains subdirectories for each build target: `latex/`, `html/`

- `publication/`

  contains publisher files

    - `main.ptx`

- `source/`

  contains pretext files

    - `main.ptx`

- `tmp/` (gitignored)

  stores temporary files to satisfy how the core PreTeXt script is hardcoded to work

- `xsl/`

  contains custom XSL files

    - `custom-common.xsl`

      example custom XSL

- `.gitignore`

  standard gitignore file

- `Pipfile`

  Pipenv manifest for easily spinning up virtual environment for book with all necessary dependencies (at least the CLI)

- `project.ptx`

  manifest XML file that stores equivalent of `.ptxconfig` from previous CLI versions, `pretext.cfg` from the core script, and the `[major].[minor]` version of the CLI used for this project. CLI travels up through the file system for this file to know where the root of the project is (so running `pretext` commands inside the `source` subdirectory is equivalent to running them in the root.

- `project-user.ptx` (gitignored)

  settings here override `project.ptx`

- `README.md`

  README describing how to install CLI and build the document

**Comment by rbeezer** [comment]
General strategy is for publisher (author, really) to specify two directories, relative to main source file, which hold

* external media - photographs, audio, video, data for plots, etc.
* generated media - images for now, everything that is born as PTX source

These two directories **could** be structured further by type of media (or whatever) if author chooses.

In author's source, the above two directories are no longer needed in things like `@source` attributes, but further structure from subdirectories **would** be needed.

Conversions "know" where such files live and scripts can copy them to scratch directories during builds.

When a script converts source (e.g. TikZ) to an image (say SVG) the script will "know" where an author means for these files to live (e.g. some scratch directory or some location tracked by a repo).

So...

I think your work here to establish a project's directory structure is going to be really valuable.  So please give it a lot of thought, and when practice dictates a change, don't be afraid to make a change for the better.

If the two directories above have a predictable location, all the better - you can write them into a publisher file as part of your "new" routine.

PS Writing this is making me somewhat conflicted about if these directories are "docinfo" or part of a publisher file...

**Comment by rbeezer** [comment]
And now I've re-read your post for a third time.  ;-)

I like to have all my messing around in my system /tmp because
* I've made it reside in RAM, for speed
* I've made it reside in RAM, so I don't trash my SSD

It is hard-coded precisely to be /tmp purposely, so no author takes it to be something permanent, and it is less likely to be part of a repository.

Who is managing the `.gitignore`?  I've seen too many HTML and PDF files being tracked.

**Comment by StevenClontz** [comment]
> PS Writing this is making me somewhat conflicted about if these directories are "docinfo" or part of a publisher file...

N.B. that I'm pushing for a pattern of *three* sources of truth: `<pretext/>`, `<publication/>`, and the new `<project/>`. The final one would handle true absolutes of the project, such as how many different publication targets the project has and what their XML filepaths are, and the default configuration of the CLI. I don't think `<pretext/>` should ever care about the user's filesystem, but I think media might be the concern of `<publication/>` vs `<project/>` since different publication targets might reasonably use different assets (e.g. maybe one publication aims for a small filesize footprint and uses more compressed images).

Unless it's reasonable to isolate all system-specific info to `<project/>` which is read by Python to do any necessary shuffling around of the system, and then `<publication/>` and `<pretext/>` can assume they live in a world where all external files necessary for the build are always in the right place.

> I like to have all my messing around in my system /tmp because

How does this work for Windows? In any case I think for Linux users symlinking `PROJECT_ROOT/tmp` to `/tmp` might be the right way to get your results with my proposed CLI workflow, but I admit I haven't worked with `/tmp` before (and most potential authors will never care about this optimization).

> Who is managing the .gitignore? I've seen too many HTML and PDF files being tracked.

I'm not sure I follow, but the only time HTML/PDF gets tracked by default is when they are copied into `docs/` (perhaps via `pretext publish`) for GitHub Pages. The CLI tries to encourage the user to make separate commits for this process to isolate the messiness, but it's up to the user in any case. (This seemed to be the least evil option, since I wanted as little Git involved in the CLI's simple publication workflow.) WIP builds go into an ignored `output/`.

That said, I just peeked at a colleague who's been using the CLI, and they are definitely mixing in the results of `pretext publish` with changes to source. So https://github.com/PreTeXtBook/pretext-cli/issues/97 is now a thing.

**Comment by oscarlevin** [comment]
This is completed by the templates and image management.
