### ISSUE TITLE
Ensure `pretext publish` only works when git is being used; refuse to `pretext publish` if git status is dirty, unless providing `--force` option

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#97]

**Comment by oscarlevin** [comment]
It might be worth thinking about other publishing workflows that might not rely on github pages.  Or a situation where github pages are hosted from a separate repo.

**Comment by StevenClontz** [comment]
I guess there might be a reason to specify, probably in `<project/>`, where to put built files intended for distribution rather than hardcoding `docs/`. Definitely worth discussion, but right now I'm leaning towards purposely not providing any further support on actually doing this distribution beyond one simple GitHub Pages workflow, as that may be beyond the scope of the CLI.

**Comment by StevenClontz** [comment]
We didn't do this exactly, but the publish workflow in 0.3 closes this.
