### ISSUE TITLE
Decide when to parse xml

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#98]
As mentioned in #38, we currently parse the main ptx file multiple times (to check for particular elements, to actually build, eventually to validate).  It might be more efficient to parse once and pass the lxml object to various functions instead of the path to the source file.

However, parsing does not take too much time.  The massive ORCCA adds roughly .3 seconds to the run time each time you invoke `ET.parse(source)`; AATA is about half of this.  

Are there other reasons to be careful?

**Comment by StevenClontz** [comment]
NB: I have the worst time keeping ElementTrees and Elements straight in StevenClontz/checkit - that distinction is the most obnoxious part of using lxml IMO. I need to refactor that project, and I think the right solution is this: always use Elements unless you're explicitly planning to read or write from the disk. But I need to research the distinction more.

**Comment by oscarlevin** [comment]
I believe this is no longer relevant after the recent objectification effort, but reopen if you disagree.
