### ISSUE TITLE
pretext new [template]

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#99]
In the UTMOST workshop right now, someone mentioned that they want to use PreTeXt the standard for how they put all their course materials online, including daily/weekly online materials like assignments, lecture notes, syllabus, and course information, etc.

It would be fairly easy to set up a "course" using the same `pretext build && pretext publish` workflow.  But we could support a standard course setup to get people started.  Eventually, we could include new xsl to allow for chunking pdfs for handouts (I have a lot of this done already for myself, so it would be a pretty easy new feature to offer).

**Comment by StevenClontz** [comment]
I wonder if this isn't a special case of a more general boilerplate issue. What if this was implemented by having a course template repo that can be maintained as a PreTeXt project directly? Then we could support `pretext new --from-template PreTeXtBook/pretext-course-template` and then someone who doesn't deal with Python programming but thinks a lot about authoring good PreTeXt documents could maintain a https://github.com/PreTeXtBook/pretext-course-template repo.

**Comment by oscarlevin** [comment]
I like this idea.  Maybe `PreTeXtBook/project-templates` could hold any number of template folders: `course`, `book`, `article`, `slides`, `conference`, etc, with more added as people find new ways to use PreTeXt.

In terms of implementation, there are ways to create projects from templates like this (although I don't know any offhand).  Alternatively, we could just have the entire folder structure provided and have sample ptx files that the CLI inserts user supplied project info (title, chapter title, etc).  We could even encourage the use of a single xml "outline" file that has this information (filled in by the user) and have the CLI insert the values in the correct place in the templates.

**Comment by StevenClontz** [comment]
I think one repo = one template is more flexible, so then anyone can create their own usable template without having to PR against the PreTeXtBook organization repo. I also like that these template repos could also model how an author would scaffold their own project's repo.

Rather than having this feature manipulate the XML, I think that responsibility could be factored out to more general project management, e.g. maybe `pretext new "My Great Book"` should be syntactic sugar for `pretext new` and `pretext update --title="My Great Book"`, regardless of if a template is used.

**Comment by oscarlevin** [comment]
So would the PreTeXtBook organization not host the templates?  I suppose there is nothing stopping both individuals from hosting templates from their own github and also having a few model templates inside one or more PreTeXtBook repositories.  

I don't have an opinion right now whether `pretext new --from-template https://github.com/oscarlevin/pretext-templates/course` should automatically initiate the "update" of titles and such.  I agree that there wouldn't be a separate process for each template.  I continue to be nervous about having the CLI write changes to the source files though.  One way around this would be to have clearly replaceable contents of titles inside the templates (which could be replaced by hand or by the cli).

**Comment by StevenClontz** [comment]
I think we want to support non-PreTeXtBook org templates, e.g. you may want to fork the official course template to prefill some information about your course and have your students use that fork.
